//
//  Test.h
//  AntiJailbreak
//
//  Created by 梁泽 on 2019/6/19.
//  Copyright © 2019 梁泽. All rights reserved.
//

#import <Foundation/Foundation.h>

#pragma mark - 越狱配置
#pragma mark -
static NSString * bunlderID = @"app.xianka.com";
static NSString * myDylibName = @"qiankdylib";
static NSArray *jailbreakFileAtPath(){
    return @[
             myDylibName,
             @"cydia",
             @"Cydia",
             @"/Applications/Cydia.app/Cydia",
             @"/Applications/Cydia.app",
             @"/Applications/FakeCarrier.app",
             @"/Applications/Icy.app",
             @"/Applications/Iny.app",
             @"/Applications/iFile.app",
             @"/Applications/Activator.app",
             @"/Applications/IntelliScreen.app",
             @"/Applications/MxTube.app",
             @"/Applications/RockApp.app",
             @"/Applications/SBSettings.app",
             @"/Applications/blackra1n.app",
             @"/User/Applications/",
             @"/Library/Activator",
             @"/Library/Flipswitch",
             @"/Library/Frameworks/CydiaSubstrate.framework",
             @"/Library/MobileSubstrate",
             @"/Library/MobileSubstrate/DynamicLibraries",
             @"/Library/MobileSubstrate/DynamicLibraries/LiveClock.plist",
             @"/Library/MobileSubstrate/DynamicLibraries/Veency.plist",
             @"/Library/MobileSubstrate/MobileSubstrate.dylib",
             @"/Library/MobileSubstrateMobileSubstrate.dylib",
             @"/Library/Switchs",
             @"/System/Library/LaunchDaemons/com.ikey.bbot.plist",
             @"/System/Library/LaunchDaemons/com.saurik.Cydia.Startup.plist",
             @"/bin/bash",
             @"/bin/sh",
             @"/bin/su",
             @"/etc/apt",
             @"/etc/apt/",
             @"/etc/clutch.conf",
             @"/etc/clutch_cracked.plist",
             @"/etc/ssh/sshd_config",
             @"/private/vstb_writable_check",
             @"/private/etc/fstab",
             @"/private/Miitomo",
             @"/private/var/lib/apt",
             @"/private/var/lib/apt/",
             @"/private/var/lib/cydia/",
             @"/var/lib/cydia/",
             @"/private/var/tmp/cydia.log",
             @"/private/var/mobile/Library/SBSettings/Themes",
             @"/private/var/mobileLibrary/SBSettingsThemes/",
             @"/private/var/stash",
             @"/private/var/stash/",
             @"/private/var/tmp/Cydia.log",
             @"/usr/arm-apple-darwin9",
             @"/usr/bin/ssh",
             @"/usr/bin/sshd",
             @"/usr/binsshd",
             @"/usr/sbinsshd",
             @"/usr/lib/pam",
             @"/usr/lib/python2.5",
             @"/usr/libexec/cydia",
             @"/usr/libexec/cydia/",
             @"/usr/libexec/sftp-server",
             @"/usr/libexec/ssh-keysign",
             @"/usr/sbin/sshd",
             @"/var/cache/apt",
             @"/var/cache/apt/",
             @"/var/cache/clutch.plist",
             @"/var/cache/clutch_cracked.plist",
             @"/var/lib/apt",
             @"/var/lib/apt/",
             @"/var/lib/clutch/overdrive.dylib",
             @"/var/lib/cydia",
             @"/var/lib/dpkg/info",
             @"/var/log/syslog",
             @"/var/root/Documents/Cracked/",
             @"/var/tmp/cydia.log",
             @"/var/stash/Library/Ringstones",
             @"/var/stash/Library/Wallpaper",
             @"/var/stash/usr/include",
             @"/var/stash/usr/libexec",
             @"/var/stash/usr/share",
             @"/Systetem/Library/LaunchDaemons/com.ikey.bbot.plist",
             @"/System/Library/LaunchDaemons/com.saurik.Cy@dia.Startup.plist",
             @"/Library/MobileSubstrate/MobileSubstrate.dylib",
             @"/var/cache/apt/",
             @"/var/lib/apt/",
             @"/var/log/syslog",
             @"/bin/bash",
             @"/bin/sh",
             @"/etc/apt/",
             @"/etc/ssh/sshd_config",
             @"/usr/libexec/ssh-keysign",
             @"/Library/MobileSubstrate/MobileSubstrate.dylib",
             @"/var/cache/apt",
             @"/var/log/syslog",
             @"/var/tmp/cydia.log",
             @"/bin/bash",
             @"/bin/sh",
             @"/usr/sbin/sshd",
             @"/etc/apt",
             @"/var/root/.tastest",
             @"/Library/Preferences/com.apple.security.plist",
             @"/private/var/mobile/home/duh",
             @"/etc/rel",
             @"/System/Library/LaunchDaemons/com.apple.period.plist",
             @"/System/Library/LaunchDaemons/com.apple.ksyslog.plist",
             @"/private/var/mobile/home/syslog",
             @"/private/var/mobile/home/sshd",
             @"/Library/MobileSubstrate/DynamicLibraries/sfbase.dylib",
             @"/usr/lib/libsubstrate.dylib",
             @"/boot",
             @"/library/MobileSubstrate/MobileSubstrate.dylib",
             @"/mnt",
             //             @"/lib",
             @"/panguaxe",
             @"/panguaxe.installed",
             @"/private/",
             @"/private/var/mobile/Media/panguaxe.installed",
             @"/private/var/lib/dpkg/info/io.pangu.axe7.list",
             @"/private/var/lib/dpkg/info/io.pangu.axe7.prerm",
             @"/System/Library/LaunchDaemons/io.pangu.axe.untether.plist",
             @"/private/var/lib/dpkg/info/taiguntether83x.extrainst_",
             @"/private/var/lib/dpkg/info/taiguntether83x.list",
             @"/private/var/lib/dpkg/info/taiguntether83x.preinst",
             @"/private/var/lib/dpkg/info/taiguntether83x.prerm",
             @"/taig/",
             @"/taig/taig",
             @"/private/var/lib/dpkg/info/io.pangu.fuxiqin9.list",
             @"/private/var/lib/dpkg/info/io.pangu.fuxiqin9.prerm",
             @"/pguntether",
             @"/var/stash/",
             @"/var/stash",
             @"/private/var/cache/apt/",
             @"/private/var/log/syslog",
             @"/private/etc/apt/",
             @"/private/etc/ssh/sshd_config",
             @"/var/mobile/Library/Application Support/Flex3/patches.plist",
             @"/private/etc/dpkg/origins/debian",
             @"/bin/gunzip",
             @"/bin/gzip",
             @"/bin/tar",
             @"/Library/MobileSubstrate/DynamicLibraries/",
             @"/private/var/cache/apt",
             @"/etc/fstab",
             @"/bin/ps",
             @"/Systetem/Library/LaunchDaemons/com.ikey.bbot.plist",
             @"/Library/MobileSubstrate/DynamicLibraries/xCon.dylib",
             @"/usr/lib/TsProtePass.dylib",
             @"/var/stash/Library/Ringtones",
             @"/var/stash/usr/arm-apple-darwin9",
             @"/private/masbog.txt",
             @"/usr/bin/cycript",
             @"/usr/bin/cynject",
             @"/usr/sbin/frida-server",
             @"/private/var/db/stash/",
             @"/var/tmp//ct.shutdown",
             @"/var/tmp/ct.shutdown",
             @"/var/tmp//cydia.log",
             @"/var/tmp//pgloader",
             @"/var/tmp/pgloader",
             @"/var/tmp//.pangu93loaded",
             @"/var/tmp/.pangu93loaded",
             @"/var/tmp//RestoreFromBackupLock",
             @"/var/tmp/RestoreFromBackupLock",
             @"/Library/LaunchDaemons/com.openssh.sshd.plist",
             @"/private/var/db/stash",
             @"/bin/mv",
             @"/private/jailbreak.txt",
             @"/Library/MobileSubstrate/",
             @"var/lib/apt",
             @"/private/var/TestPB16.file",
             @"/etc/TestPB16.file",
             @"/Applications/TestPB16.file",
             @"/System/Library/Caches/com.apple.dyld/enable-dylibs-to-override-cache",
             //             @"/usr/lib/libmis.dylib", iOS代码签名有关
             @"/usr/lib/pangu_xpcd.dylib",
             @"/System/Library/LaunchDaemons/io.pangu.untether.plist",
             @"/xuanyuansword",
             @"/xuanyuansword.installed",
             @"/evasi0n7",
             @"/System/Library/LaunchDaemons/com.evad3rs.evasi0n7.untether.plist",
             @"/usr/lib/libpatcyh.dylib",
             @"/usr/share/bigboss/icons/bigboss.png",
             @"/Library/MobileSubstrate/DynamicLibraries/tsProtector.dylib",
             @"/Library/PreferenceBundles/tsProtectorSettings.bundle",
             @"/Library/PreferenceLoader/Preferences/tsProtectorSettings.plist",
             @"/private/var/lib/xcon",
             @"/Library/MobileSubstrate/DynamicLibraries/MobileSafety.dylib",
             @"/.cydia_no_stash",
             @"/.installed_yaluX",
             @"/private/var/log/apt/term.log",
             @"/Library/LaunchDaemons/re.frida.server.plist",
             @"/usr/sbin/frida-server",
             @"/sbin/reboot",
             @"/Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate",
             @"/etc/ssh",
             @"Library/MobileSubstrate",
             @"Library/MobileSubstrate/DynamicLibraries",
             @"/private/var/lib",
             @"/private/var/mobile/Library/SBSettings",
             @"/var/cache",
             @"/var/lib",
             @"/etc/ssh",
             @"/User/Library/Cydia",
             @"/private/var/evasi0n", //238
             ];
}
#pragma mark -
#pragma mark - 临时声明
extern int ptrace(int request, pid_t pid, caddr_t addr, int data);
extern int     system(const char *s1);

#pragma mark -
#pragma mark - 安全防护类
