//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UIAlertViewDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class CALayer, NSDictionary, NSString, UIButton, UIImageView, UITextField, UIView;

@interface AuthCodeViewController : UIViewController <UITextFieldDelegate, UIAlertViewDelegate>
{
    UIView *authCodeView;
    CALayer *_maskLayer;
    NSString *_base64String;
    CDUnknownBlockType _mBlock;
    NSDictionary *_params;
    UIImageView *_imageView;
    UIButton *_sureBtn;
    UITextField *_input;
}

+ (id)showWithParam:(id)arg1 SelectBlock:(CDUnknownBlockType)arg2;
@property(retain, nonatomic) UITextField *input; // @synthesize input=_input;
@property(retain, nonatomic) UIButton *sureBtn; // @synthesize sureBtn=_sureBtn;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) NSDictionary *params; // @synthesize params=_params;
@property(copy, nonatomic) CDUnknownBlockType mBlock; // @synthesize mBlock=_mBlock;
@property(retain, nonatomic) NSString *base64String; // @synthesize base64String=_base64String;
@property(retain, nonatomic) CALayer *maskLayer; // @synthesize maskLayer=_maskLayer;
- (void).cxx_destruct;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)didTapImageView;
- (void)setupUI;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

