//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString;

@interface BXHttpClient : NSObject
{
    _Bool tryed1_0_0_1;
    NSString *_homeURL;
    NSString *_contactURL;
    _Bool _release;
    unsigned long long _netWorkEnviormnt;
    NSString *_host;
    NSString *_baseUrl;
    NSString *_staticUrl;
    NSString *_baseUrl_API;
    NSString *_socket;
    NSString *_socketCertificationName;
    CDUnknownBlockType _completionBlock;
    NSDictionary *_hostDic;
}

+ (id)shareInstance;
@property(retain, nonatomic) NSDictionary *hostDic; // @synthesize hostDic=_hostDic;
@property(copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
@property(nonatomic, getter=isRelease) _Bool release; // @synthesize release=_release;
@property(retain, nonatomic) NSString *socketCertificationName; // @synthesize socketCertificationName=_socketCertificationName;
@property(retain, nonatomic) NSString *socket; // @synthesize socket=_socket;
@property(retain, nonatomic) NSString *baseUrl_API; // @synthesize baseUrl_API=_baseUrl_API;
@property(retain, nonatomic) NSString *staticUrl; // @synthesize staticUrl=_staticUrl;
@property(retain, nonatomic) NSString *baseUrl; // @synthesize baseUrl=_baseUrl;
@property(retain, nonatomic) NSString *host; // @synthesize host=_host;
@property(nonatomic) unsigned long long netWorkEnviormnt; // @synthesize netWorkEnviormnt=_netWorkEnviormnt;
- (void).cxx_destruct;
- (id)lastEnableHostKey;
- (void)animationFinished:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)exitApplication;
- (void)goHome;
- (void)contactCustomer;
- (void)alert;
- (void)handleAlert;
- (void)handleJsonDict:(id)arg1;
- (void)setUpWithAdress:(id)arg1;
- (void)pingIP:(id)arg1 host:(id)arg2 block:(CDUnknownBlockType)arg3;
- (void)filterValidUrlWithInfoString:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)Github_getHostBlock:(CDUnknownBlockType)arg1;
- (void)Github_Query;
- (void)configProductEnvWithIP:(id)arg1 host:(id)arg2;
- (void)try1_0_0_1;
- (void)getHttpIPAdressWithDnsProvider:(id)arg1;
- (void)configAPI:(CDUnknownBlockType)arg1;
- (void)changeNetWorkEnviormnt:(unsigned long long)arg1;

@end

