//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSString;

@interface JPUSHAddress : NSObject <NSCopying>
{
    NSString *_host;
    unsigned short _port;
    NSString *_httpWrapAddress;
}

@property(copy, nonatomic) NSString *httpWrapAddress; // @synthesize httpWrapAddress=_httpWrapAddress;
@property(nonatomic) unsigned short port; // @synthesize port=_port;
@property(copy, nonatomic) NSString *host; // @synthesize host=_host;
- (void).cxx_destruct;
- (id)description;
- (_Bool)isEqual:(id)arg1;
- (id)absoluteString;
- (id)infoDictionary;
- (id)analyseResourcePath:(id)arg1;
- (_Bool)p_addressVerify:(id)arg1 port:(unsigned short)arg2;
- (id)initWithString:(id)arg1 ResourceByAddress:(id)arg2;
- (id)initWithString:(id)arg1;
- (id)initWithDictionary:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

