//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NIMKitTimerHolderDelegate-Protocol.h"

@class NIMKitTimerHolder, NSMutableDictionary, NSString;

@interface NIMKitNotificationFirer : NSObject <NIMKitTimerHolderDelegate>
{
    NSMutableDictionary *_cachedInfo;
    NIMKitTimerHolder *_timer;
    double _timeInterval;
}

@property(nonatomic) double timeInterval; // @synthesize timeInterval=_timeInterval;
@property(retain, nonatomic) NIMKitTimerHolder *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) NSMutableDictionary *cachedInfo; // @synthesize cachedInfo=_cachedInfo;
- (void).cxx_destruct;
- (void)onNIMKitTimerFired:(id)arg1;
- (void)addFireInfo:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

