//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface NIMKitResourceResizer : NSObject
{
    double _scale;
}

+ (id)sharedResizer;
@property(nonatomic) double scale; // @synthesize scale=_scale;
- (id)videoThumbnailURL:(id)arg1;
- (id)imageThumbnailURL:(id)arg1;
- (struct CGSize)resizeWidth:(double)arg1 height:(double)arg2;
- (id)resize:(id)arg1 width:(double)arg2 height:(double)arg3;
- (id)init;

@end

