//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NIMSession, NSString;

@interface NIMKitFirerInfo : NSObject
{
    NIMSession *_session;
    NSString *_notificationName;
}

@property(copy, nonatomic) NSString *notificationName; // @synthesize notificationName=_notificationName;
@property(retain, nonatomic) NIMSession *session; // @synthesize session=_session;
- (void).cxx_destruct;
- (id)saveIdentity;
- (id)fireObject;

@end

