//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSDictionary.h>

@interface NSDictionary (NIMKit)
- (double)nimkit_jsonDouble:(id)arg1;
- (unsigned long long)nimkit_jsonUnsignedLongLong:(id)arg1;
- (long long)nimkit_jsonLongLong:(id)arg1;
- (long long)nimkit_jsonInteger:(id)arg1;
- (_Bool)nimkit_jsonBool:(id)arg1;
- (id)nimkit_jsonStringArray:(id)arg1;
- (id)nimkit_jsonArray:(id)arg1;
- (id)nimkit_jsonDict:(id)arg1;
- (id)nimkit_jsonString:(id)arg1;
@end

