//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NIMSessionConfig-Protocol.h"

@class NIMSession, NSString;

@interface NTESSessionConfig : NSObject <NIMSessionConfig>
{
    NIMSession *_session;
}

@property(retain, nonatomic) NIMSession *session; // @synthesize session=_session;
- (void).cxx_destruct;
- (id)loadChartletEmoticonCatalog;
- (long long)recordType;
- (_Bool)autoFetchAttachment;
- (_Bool)disableProximityMonitor;
- (_Bool)shouldHandleReceiptForMessage:(id)arg1;
- (id)inputBarItemTypes;
- (_Bool)shouldHandleReceipt;
- (id)mediaItems;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

