//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface NTESSessionMsgConverter : NSObject
{
}

+ (id)msgWithRedPacketTip:(id)arg1;
+ (id)msgWithRedPacket:(id)arg1;
+ (id)msgWithTip:(id)arg1;
+ (id)msgWithWhiteboardAttachment:(id)arg1;
+ (id)msgWithChartletAttachment:(id)arg1;
+ (id)msgWithFileData:(id)arg1 extension:(id)arg2;
+ (id)msgWithFilePath:(id)arg1;
+ (id)msgWithSnapchatAttachment:(id)arg1;
+ (id)msgWithJenKenPon:(id)arg1;
+ (id)msgWithVideo:(id)arg1;
+ (id)msgWithAudio:(id)arg1;
+ (id)generateImageMessage:(id)arg1;
+ (id)msgWithImagePath:(id)arg1;
+ (id)msgWithImage:(id)arg1;
+ (id)msgWithText:(id)arg1;

@end

