//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class DiamondSumBaseView, NSString, UIButton, UIImageView, UILabel;
@protocol PropsRechargeViewDelegate;

@interface PropsRechargeView : UIView
{
    NSString *_titiString;
    NSString *_number;
    id <PropsRechargeViewDelegate> _delegate;
    UILabel *_titieLabel;
    DiamondSumBaseView *_diamondSumBaseView;
    UIImageView *_iocn;
    UIImageView *_arrowIocn;
    UIButton *_btn;
}

@property(retain, nonatomic) UIButton *btn; // @synthesize btn=_btn;
@property(retain, nonatomic) UIImageView *arrowIocn; // @synthesize arrowIocn=_arrowIocn;
@property(retain, nonatomic) UIImageView *iocn; // @synthesize iocn=_iocn;
@property(retain, nonatomic) DiamondSumBaseView *diamondSumBaseView; // @synthesize diamondSumBaseView=_diamondSumBaseView;
@property(retain, nonatomic) UILabel *titieLabel; // @synthesize titieLabel=_titieLabel;
@property(nonatomic) __weak id <PropsRechargeViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) NSString *number; // @synthesize number=_number;
- (void).cxx_destruct;
- (void)clickBtn;
- (id)init;

@end

