//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class NSObject;
@protocol OS_dispatch_source;

@interface UIButton (Delay)
@property(nonatomic) _Bool isNeedDelay;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *timer;
@property(nonatomic) long long delayInterval;
- (void)handleAction:(id)arg1;
- (void)sendAction:(SEL)arg1 to:(id)arg2 forEvent:(id)arg3;
@end

