//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MRTManagedObject.h"

@class MRTTitleID, NSDate, NSNumber, NSString;

@interface _MRTTitle : MRTManagedObject
{
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
+ (id)entityInManagedObjectContext:(id)arg1;
+ (id)entityName;
+ (id)insertInManagedObjectContext:(id)arg1;
- (void)setPrimitiveSortIndexValue:(short)arg1;
- (short)primitiveSortIndexValue;
@property short sortIndexValue;
@property(readonly, nonatomic) MRTTitleID *objectID;

// Remaining properties
@property(retain, nonatomic) NSString *nameDescription; // @dynamic nameDescription;
@property(retain, nonatomic) NSString *nameTitle; // @dynamic nameTitle;
@property(retain, nonatomic) NSNumber *sortIndex; // @dynamic sortIndex;
@property(retain, nonatomic) NSDate *timeCreated; // @dynamic timeCreated;
@property(retain, nonatomic) NSDate *timeUpdated; // @dynamic timeUpdated;

@end

