//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Marriott18MonthDayPickerView.h"

#import "MRTContinuousPickerViewDataSource-Protocol.h"

@interface _TtC8Marriott18MonthDayPickerView (Marriott) <MRTContinuousPickerViewDataSource>
- (long long)continuousPickerView:(id)arg1 numberOfRowsInComponent:(long long)arg2;
- (long long)numberOfComponentsInContinuousPickerView:(id)arg1;
- (_Bool)continuousPickerView:(id)arg1 isContinuousInComponent:(long long)arg2;
@end

