//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ADBAnalyticsTrackTimedAction : NSObject
{
    struct sqlite3 *_database;
    struct sqlite3_stmt *_sqlInsertAction;
    struct sqlite3_stmt *_sqlUpdateAction;
    struct sqlite3_stmt *_sqlUpdateAllActionsClearAdjusted;
    struct sqlite3_stmt *_sqlSelectAction;
    struct sqlite3_stmt *_sqlDeleteAction;
    struct sqlite3_stmt *_sqlDeleteAllActions;
    struct sqlite3_stmt *_sqlExistsAction;
    struct sqlite3_stmt *_sqlInsertContextData;
    struct sqlite3_stmt *_sqlUpdateContextData;
    struct sqlite3_stmt *_sqlSelectContextDataForAction;
    struct sqlite3_stmt *_sqlDeleteContextDataForAction;
    struct sqlite3_stmt *_sqlDeleteContextDataForAllActions;
    struct sqlite3_stmt *_sqlExistsContextDataByActionAndKey;
}

+ (id)copyWithZone:(struct _NSZone *)arg1;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedInstance;
@property(nonatomic) struct sqlite3_stmt *sqlExistsContextDataByActionAndKey; // @synthesize sqlExistsContextDataByActionAndKey=_sqlExistsContextDataByActionAndKey;
@property(nonatomic) struct sqlite3_stmt *sqlDeleteContextDataForAllActions; // @synthesize sqlDeleteContextDataForAllActions=_sqlDeleteContextDataForAllActions;
@property(nonatomic) struct sqlite3_stmt *sqlDeleteContextDataForAction; // @synthesize sqlDeleteContextDataForAction=_sqlDeleteContextDataForAction;
@property(nonatomic) struct sqlite3_stmt *sqlSelectContextDataForAction; // @synthesize sqlSelectContextDataForAction=_sqlSelectContextDataForAction;
@property(nonatomic) struct sqlite3_stmt *sqlUpdateContextData; // @synthesize sqlUpdateContextData=_sqlUpdateContextData;
@property(nonatomic) struct sqlite3_stmt *sqlInsertContextData; // @synthesize sqlInsertContextData=_sqlInsertContextData;
@property(nonatomic) struct sqlite3_stmt *sqlExistsAction; // @synthesize sqlExistsAction=_sqlExistsAction;
@property(nonatomic) struct sqlite3_stmt *sqlDeleteAllActions; // @synthesize sqlDeleteAllActions=_sqlDeleteAllActions;
@property(nonatomic) struct sqlite3_stmt *sqlDeleteAction; // @synthesize sqlDeleteAction=_sqlDeleteAction;
@property(nonatomic) struct sqlite3_stmt *sqlSelectAction; // @synthesize sqlSelectAction=_sqlSelectAction;
@property(nonatomic) struct sqlite3_stmt *sqlUpdateAllActionsClearAdjusted; // @synthesize sqlUpdateAllActionsClearAdjusted=_sqlUpdateAllActionsClearAdjusted;
@property(nonatomic) struct sqlite3_stmt *sqlUpdateAction; // @synthesize sqlUpdateAction=_sqlUpdateAction;
@property(nonatomic) struct sqlite3_stmt *sqlInsertAction; // @synthesize sqlInsertAction=_sqlInsertAction;
@property(nonatomic) struct sqlite3 *database; // @synthesize database=_database;
- (void)dealloc;
- (void)resetDatabase;
- (void)deleteActionByID:(int)arg1;
- (id)getAction:(id)arg1;
- (void)updateContextDataForAction:(id)arg1 data:(id)arg2;
- (void)insertAction:(id)arg1 data:(id)arg2 startTime:(double)arg3;
- (void)initializeDatabase;
- (void)clearAllAdjustedStartTimes;
- (void)updateAllAdjustedStartTimes:(long long)arg1;
- (_Bool)hasAction:(id)arg1;
- (void)endAction:(id)arg1 logic:(CDUnknownBlockType)arg2;
- (void)updateAction:(id)arg1 data:(id)arg2;
- (void)startAction:(id)arg1 data:(id)arg2;
- (id)init;
- (id)autorelease;
- (id)retain;
- (oneway void)release;
- (unsigned long long)retainCount;

@end

