//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AGSensorInfoManager;

@interface AGTelemetryManager : NSObject
{
    AGSensorInfoManager *_sensorManager;
}

@property(readonly) AGSensorInfoManager *sensorManager; // @synthesize sensorManager=_sensorManager;
- (void).cxx_destruct;
- (id)getSignals:(id)arg1 sensorSignals:(id)arg2;
- (id)getUserAgent;
- (id)getSystemUptime;
- (id)getDeviceFreeStorage;
- (id)getDeviceTotatStorage;
- (id)getDeviceTotalRAM;
- (id)getDeviceResolutionBrightness;
- (id)getDeviceResolutionDensity;
- (id)getDeviceResolutionWidth;
- (id)getDeviceResolutionHeight;
- (id)getDeviceNumCores;
- (id)getDeviceModelNo;
- (id)getDeviceModelName;
- (id)init;

@end

