//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewController.h>

#import "ATSurveyViewModelDelegate-Protocol.h"
#import "ApptentiveCollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"
#import "UITextViewDelegate-Protocol.h"

@class ApptentiveInteractionController, ApptentiveSurveyGreetingView, ApptentiveSurveySubmitButton, ApptentiveSurveyViewModel, NSIndexPath, NSString, UIBarButtonItem, UIColor, UIView;

@interface ApptentiveSurveyViewController : UICollectionViewController <UICollectionViewDelegateFlowLayout, UITextViewDelegate, UITextFieldDelegate, ApptentiveCollectionViewDataSource, ATSurveyViewModelDelegate>
{
    double _lineHeightOfQuestionFont;
    ApptentiveSurveyViewModel *_viewModel;
    ApptentiveInteractionController *_interactionController;
    ApptentiveSurveyGreetingView *_headerView;
    UIView *_headerBackgroundView;
    UIView *_footerView;
    UIView *_footerBackgroundView;
    ApptentiveSurveySubmitButton *_submitButton;
    UIBarButtonItem *_missingRequiredItem;
    NSIndexPath *_editingIndexPath;
    double _iOS9ToolbarInset;
}

@property(nonatomic) double iOS9ToolbarInset; // @synthesize iOS9ToolbarInset=_iOS9ToolbarInset;
@property(retain, nonatomic) NSIndexPath *editingIndexPath; // @synthesize editingIndexPath=_editingIndexPath;
@property(retain, nonatomic) UIBarButtonItem *missingRequiredItem; // @synthesize missingRequiredItem=_missingRequiredItem;
@property(retain, nonatomic) ApptentiveSurveySubmitButton *submitButton; // @synthesize submitButton=_submitButton;
@property(retain, nonatomic) UIView *footerBackgroundView; // @synthesize footerBackgroundView=_footerBackgroundView;
@property(retain, nonatomic) UIView *footerView; // @synthesize footerView=_footerView;
@property(retain, nonatomic) UIView *headerBackgroundView; // @synthesize headerBackgroundView=_headerBackgroundView;
@property(retain, nonatomic) ApptentiveSurveyGreetingView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) ApptentiveInteractionController *interactionController; // @synthesize interactionController=_interactionController;
@property(retain, nonatomic) ApptentiveSurveyViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (void).cxx_destruct;
- (void)maybeAnimateOtherSizeChangeAtIndexPath:(id)arg1;
- (void)setToolbarHidden:(_Bool)arg1;
- (void)adjustForKeyboard:(id)arg1;
- (void)viewModel:(id)arg1 didDeselectAnswerAtIndexPath:(id)arg2;
- (void)viewModelValidationChanged:(id)arg1 isValid:(_Bool)arg2;
- (void)textFieldDidEndEditing:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)textFieldChanged:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)textViewDidEndEditing:(id)arg1;
- (void)textViewDidChange:(id)arg1;
- (_Bool)textViewShouldEndEditing:(id)arg1;
- (void)textViewDidBeginEditing:(id)arg1;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForFooterInSection:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (_Bool)collectionView:(id)arg1 shouldDeselectItemAtIndexPath:(id)arg2;
- (_Bool)collectionView:(id)arg1 shouldSelectItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didDeselectItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
@property(readonly, nonatomic) UIColor *backgroundColor;
@property(readonly, nonatomic) UIColor *invalidColor;
@property(readonly, nonatomic) UIColor *validColor;
- (_Bool)sectionAtIndexIsValid:(long long)arg1;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
@property(readonly, nonatomic) double lineHeightOfQuestionFont; // @synthesize lineHeightOfQuestionFont=_lineHeightOfQuestionFont;
- (void)showAbout:(id)arg1;
- (void)close:(id)arg1;
- (void)submit:(id)arg1;
- (void)sizeDidUpdate:(id)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)dealloc;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

