//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FiR3FiParseMaster, NSArray, NSDictionary, NSInvocation, NSString, NSTNMovieWatcher;

@interface EnsightenInstructionProcessor : NSObject
{
    NSDictionary *opcodes;
    id currentValue;
    int instructionPointer;
    NSInvocation *invocation;
    FiR3FiParseMaster *parseMaster;
    NSTNMovieWatcher *movieWatcher;
    NSArray *args;
    NSString *_taggedClass;
    NSString *_taggedSelector;
}

@property(nonatomic) NSString *taggedSelector; // @synthesize taggedSelector=_taggedSelector;
@property(nonatomic) NSString *taggedClass; // @synthesize taggedClass=_taggedClass;
@property(retain, nonatomic) id currentValue; // @synthesize currentValue;
@property(nonatomic) NSInvocation *invocation; // @synthesize invocation;
@property(retain, nonatomic) NSArray *args; // @synthesize args;
- (void).cxx_destruct;
- (void)resetState;
- (void)iterateWithSelectors:(id)arg1;
- (void)setMoviePlaybackQuePoints:(id)arg1;
- (void)stringFromClass:(id)arg1;
- (id)getRegValOrUseImmediate:(id)arg1;
- (void)respondsToSel:(id)arg1;
- (void)setReturnValue:(id)arg1;
- (void)getReturnValue:(id)arg1;
- (void)crumb:(id)arg1;
- (void)timedAction:(id)arg1;
- (void)setAdBreak:(id)arg1;
- (void)setMovieChapters:(id)arg1;
- (void)saveValueToDefaults:(id)arg1;
- (void)removeValueFromDefaults:(id)arg1;
- (void)getValueFromDefaults:(id)arg1;
- (void)alter:(id)arg1;
- (void)performOperation:(id)arg1;
- (void)getCurrentVCObj:(id)arg1;
- (void)assertCurrentVC:(id)arg1;
- (void)getCell:(id)arg1;
- (void)evalJS:(id)arg1;
- (void)stringify:(id)arg1;
- (void)getArg:(id)arg1;
- (void)getClass:(id)arg1;
- (void)setInvArg:(id)arg1;
- (void)getInvArg:(id)arg1;
- (void)getInvTarget:(id)arg1;
- (void)getViewElement:(id)arg1;
- (void)getDLObject:(id)arg1;
- (void)sendMessage:(id)arg1;
- (void)end:(id)arg1;
- (void)jumpIfNZ:(id)arg1;
- (void)jumpIfZ:(id)arg1;
- (void)compare:(id)arg1;
- (void)prepend:(id)arg1;
- (void)append:(id)arg1;
- (void)cut:(id)arg1;
- (void)count:(id)arg1;
- (void)length:(id)arg1;
- (void)split:(id)arg1;
- (void)search:(id)arg1;
- (void)replace:(id)arg1;
- (void)setRegister:(id)arg1;
- (void)setRegisterCV:(id)arg1;
- (void)setCV:(id)arg1;
- (void)initializeIntstructions;
- (id)init;
- (id)executeInstructions:(id)arg1;
- (id)executeSingleInstruction:(id)arg1;

@end

