//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface LegicBlePluginConversionHelper : NSObject
{
}

+ (unsigned long long)getProjectIDFromFilenameData:(id)arg1;
+ (unsigned long long)getProjectIDFromFilename:(id)arg1;
+ (id)computeMD5:(id)arg1;
+ (id)dataToBase64:(id)arg1;
+ (id)base64ToData:(id)arg1;

@end

