//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface LegicProfileIds : NSObject
{
    int profileId;
}

- (id)getProfileIdString;
- (int)getProfileId;
- (void)setProfileId:(int)arg1;
- (void)setProfileIdWithString:(id)arg1;
- (id)initWithProfileId:(int)arg1;
- (id)initWithString:(id)arg1;

@end

