//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MRTCommonUI/MRTStyledLabel.h>

@class MRTRewardsArcSegment;

@interface MRTArcSegmentLabel : MRTStyledLabel
{
    MRTRewardsArcSegment *_arcSegment;
}

@property(retain, nonatomic) MRTRewardsArcSegment *arcSegment; // @synthesize arcSegment=_arcSegment;
- (void).cxx_destruct;
- (void)update;
- (id)init;

@end

