//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MRTAbstractSettingsViewController.h"

#import "MFMailComposeViewControllerDelegate-Protocol.h"
#import "SFSafariViewControllerDelegate-Protocol.h"

@class MRTConsumer, MRTNotificationsRegistrationController, MRTStyledButton, MRTStyledLabel, NSString, UIUserNotificationSettings;

@interface MRTAccountSettingsViewController : MRTAbstractSettingsViewController <MFMailComposeViewControllerDelegate, SFSafariViewControllerDelegate>
{
    MRTStyledLabel *_nameLabel;
    MRTStyledLabel *_disclosureLabel;
    MRTStyledButton *_signOutButton;
    UIUserNotificationSettings *_grantedSettings;
    MRTConsumer *_consumer;
    MRTNotificationsRegistrationController *_registrationController;
}

@property(retain, nonatomic) MRTNotificationsRegistrationController *registrationController; // @synthesize registrationController=_registrationController;
@property(readonly, nonatomic) MRTConsumer *consumer; // @synthesize consumer=_consumer;
@property(retain, nonatomic) UIUserNotificationSettings *grantedSettings; // @synthesize grantedSettings=_grantedSettings;
@property(nonatomic) __weak MRTStyledButton *signOutButton; // @synthesize signOutButton=_signOutButton;
@property(nonatomic) __weak MRTStyledLabel *disclosureLabel; // @synthesize disclosureLabel=_disclosureLabel;
@property(nonatomic) __weak MRTStyledLabel *nameLabel; // @synthesize nameLabel=_nameLabel;
- (void).cxx_destruct;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (id)guestServicesNotificationCellHeaderString;
- (id)signOutButtonString;
- (id)disclosureLabelString;
- (void)signOutTapped:(id)arg1;
- (void)remoteNotificationSettingsTapped:(id)arg1;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(long long)arg2 error:(id)arg3;
- (void)careersTapped:(id)arg1;
- (void)shopMarriottTapped:(id)arg1;
- (void)cityGuidesTapped:(id)arg1;
- (void)showFullSite:(id)arg1;
- (void)ourBrandsTapped:(id)arg1;
- (void)aboutMarriottTapped:(id)arg1;
- (void)aboutThisAppTapped:(id)arg1;
- (void)giveUsFeedbackTapped:(id)arg1;
- (void)configureMailComposeController:(id)arg1;
- (void)contactUsTapped:(id)arg1;
- (void)privacyPolicyTapped:(id)arg1;
- (void)termsAndConditionsTapped:(id)arg1;
- (void)communicationOptionsTapped:(id)arg1;
- (void)manageProfileTapped:(id)arg1;
- (void)attemptToChangeTouchIDToEnabled:(_Bool)arg1 withSender:(id)arg2;
- (void)touchIDSettingChanged:(id)arg1;
- (void)marketingNotificationValueChanged:(id)arg1;
- (id)communicationOptions;
- (void)notificationValueChanged:(id)arg1;
- (void)safariViewControllerDidFinish:(id)arg1;
- (void)navigateToExternalURL:(id)arg1;
- (id)appNavigationIdentifier;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)notificationsRegistrationDidUpdate;
- (void)setupItems;
- (void)addMarriottInternationalItemsToArray:(id)arg1 titles:(id)arg2;
- (void)addSupportAndInformationItemsToArray:(id)arg1 titles:(id)arg2;
- (void)addNotificationAndDevicePreferencesItemsToArray:(id)arg1 titles:(id)arg2;
- (void)addAccountItemsToArray:(id)arg1 titles:(id)arg2;
- (void)setSectionItems:(id)arg1 titles:(id)arg2;
- (void)dealloc;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

