//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"

@class MRTActivityIndicatorView, MRTContextButtonItem, MRTFindReservationViewController, MRTRefreshControl, MRTReservationContainer, MRTTitleSegmentedControl, NSLayoutConstraint, NSString, UICollectionView, UILabel, UIView;

@interface MRTAllReservationsViewController : UIViewController <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
{
    MRTReservationContainer *_reservationContainer;
    UICollectionView *_collectionView;
    MRTRefreshControl *_refreshControl;
    UIView *_headerView;
    MRTFindReservationViewController *_presentedFindController;
    NSLayoutConstraint *_segmentLeftMargin;
    NSLayoutConstraint *_segmentRightMargin;
    MRTTitleSegmentedControl *_reservationsSegmentControl;
    MRTActivityIndicatorView *_pagedFetchActivityIndicator;
    UIView *_headerLabelContainer;
    UILabel *_headerLabel;
    NSLayoutConstraint *_headerContentHeightConstraint;
    NSLayoutConstraint *_headerContentTopConstraint;
    NSLayoutConstraint *_headerContentBottomConstraint;
    unsigned long long _currentlySelectedSegmentedIndex;
    MRTContextButtonItem *_findReservationContextButton;
}

+ (void)resetAllCoachMarks;
+ (id)findReservationCoachMarkSkipText;
+ (id)findReservationCoachMarkMessage;
@property(retain, nonatomic) MRTContextButtonItem *findReservationContextButton; // @synthesize findReservationContextButton=_findReservationContextButton;
@property(nonatomic) unsigned long long currentlySelectedSegmentedIndex; // @synthesize currentlySelectedSegmentedIndex=_currentlySelectedSegmentedIndex;
@property(nonatomic) __weak NSLayoutConstraint *headerContentBottomConstraint; // @synthesize headerContentBottomConstraint=_headerContentBottomConstraint;
@property(nonatomic) __weak NSLayoutConstraint *headerContentTopConstraint; // @synthesize headerContentTopConstraint=_headerContentTopConstraint;
@property(nonatomic) __weak NSLayoutConstraint *headerContentHeightConstraint; // @synthesize headerContentHeightConstraint=_headerContentHeightConstraint;
@property(nonatomic) __weak UILabel *headerLabel; // @synthesize headerLabel=_headerLabel;
@property(nonatomic) __weak UIView *headerLabelContainer; // @synthesize headerLabelContainer=_headerLabelContainer;
@property(nonatomic) __weak MRTActivityIndicatorView *pagedFetchActivityIndicator; // @synthesize pagedFetchActivityIndicator=_pagedFetchActivityIndicator;
@property(nonatomic) __weak MRTTitleSegmentedControl *reservationsSegmentControl; // @synthesize reservationsSegmentControl=_reservationsSegmentControl;
@property(nonatomic) __weak NSLayoutConstraint *segmentRightMargin; // @synthesize segmentRightMargin=_segmentRightMargin;
@property(nonatomic) __weak NSLayoutConstraint *segmentLeftMargin; // @synthesize segmentLeftMargin=_segmentLeftMargin;
@property(nonatomic) __weak MRTFindReservationViewController *presentedFindController; // @synthesize presentedFindController=_presentedFindController;
@property(nonatomic) __weak UIView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) MRTRefreshControl *refreshControl; // @synthesize refreshControl=_refreshControl;
@property(nonatomic) __weak UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) MRTReservationContainer *reservationContainer; // @synthesize reservationContainer=_reservationContainer;
- (void).cxx_destruct;
- (id)findReservationCoachMarkConfiguration;
- (_Bool)_findReservationCoachMarkIsCompleted;
- (void)_markFindReservationCoachMarkAsComplete;
- (void)_closeCoachMark;
- (void)_handleCoachMarkSkipTap;
- (_Bool)_shouldShowFindReservationCoachMark;
- (void)showFindReservationCoachMarkIfNeeded;
- (id)findReservationButtonTitle;
- (id)missingStayText;
- (id)pastStaysInformationalText;
- (void)unwindToReservationInfo:(id)arg1;
- (void)confirmationInfoButtonTappedForReservationCell:(id)arg1;
- (id)localizedStringForBookingLabel;
- (void)trackUpdatedAnalyticsPageWithIndex:(unsigned long long)arg1;
- (void)_titleSegmentedControlValueChanged:(id)arg1;
- (void)_transitionToSegmentWithIndex:(unsigned long long)arg1;
- (unsigned long long)reservationType;
- (void)navigateToPath:(id)arg1;
- (void)viewNeedsUpdateForNoReservations;
- (void)updateHeaderWithText:(id)arg1;
- (unsigned long long)numberOfListItems;
- (unsigned long long)numberOfCardItems;
- (id)mainList;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (struct CGSize)setupCellSizeForIndexPath:(id)arg1 layout:(id)arg2 collectionView:(id)arg3;
- (id)setupFooterReservationCellForIndexPath:(id)arg1 collectionView:(id)arg2;
- (id)setupEmptyReservationListCellForIndexPath:(id)arg1 collectionView:(id)arg2;
- (id)setupNonActiveReservationCellForIndexPath:(id)arg1 collectionView:(id)arg2;
- (id)setupActiveReservationCellForIndexPath:(id)arg1 collectionView:(id)arg2;
- (id)setupPastReservationCellForIndexPath:(id)arg1 collectionView:(id)arg2;
- (id)typeOfCellForIndexPath:(id)arg1 collectionView:(id)arg2;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (void)scrollViewDidScroll:(id)arg1;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (_Bool)isListEmpty;
- (id)_showStayViewControllerForReservation:(id)arg1 withPage:(unsigned long long)arg2;
- (id)existingStayContainerForReservation:(id)arg1;
- (id)indexPathForReservation:(id)arg1;
- (id)reservationForIndexPath:(id)arg1;
- (void)findReservationButtonTapped:(id)arg1;
- (void)reservationChanged:(id)arg1;
- (void)_redisplayReservations;
- (void)_refresh:(id)arg1;
- (void)showPartialErrorMessage;
- (void)updateHeaderShadow;
- (void)traitCollectionDidChange:(id)arg1;
- (void)oneButtonOverlayLayoutMarginsWillChange:(struct UIEdgeInsets)arg1;
- (id)viewControllerForAppNavigationIdentifier:(id)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)refreshReservations;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)rewardsAccount;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

