//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MRTObject.h"

#import "NSCopying-Protocol.h"

@class MRTGender;

@interface MRTConsumerName : MRTObject <NSCopying>
{
    MRTGender *_gender;
}

@property(retain, nonatomic) MRTGender *gender; // @synthesize gender=_gender;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (_Bool)isEqualToMRTConsumerName:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)differencesWith:(id)arg1;

@end

