//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "MRTChatMessagingProvider-Protocol.h"

@class MRTReservation, NSMutableOrderedSet, NSOrderedSet, NSString, NSTimer;
@protocol NSObject;

@interface MRTChatSalesforceDataController : NSObject <MRTChatMessagingProvider>
{
    _Bool _currentlyReachable;
    NSString *confirmationNumber;
    MRTReservation *reservation;
    NSString *serviceRequestId;
    id <NSObject> _reachabilityObserver;
    NSTimer *_pollingTimer;
    CDUnknownBlockType _pollingCompletion;
    NSString *_chatFeedElementId;
    NSMutableOrderedSet *_messageSet;
}

@property(retain, nonatomic) NSMutableOrderedSet *messageSet; // @synthesize messageSet=_messageSet;
@property(copy, nonatomic) NSString *chatFeedElementId; // @synthesize chatFeedElementId=_chatFeedElementId;
@property(copy, nonatomic) CDUnknownBlockType pollingCompletion; // @synthesize pollingCompletion=_pollingCompletion;
@property(retain, nonatomic) NSTimer *pollingTimer; // @synthesize pollingTimer=_pollingTimer;
@property(nonatomic) _Bool currentlyReachable; // @synthesize currentlyReachable=_currentlyReachable;
@property(retain, nonatomic) id <NSObject> reachabilityObserver; // @synthesize reachabilityObserver=_reachabilityObserver;
@property(copy, nonatomic) NSString *serviceRequestId; // @synthesize serviceRequestId;
@property(retain, nonatomic) MRTReservation *reservation; // @synthesize reservation;
@property(copy, nonatomic) NSString *confirmationNumber; // @synthesize confirmationNumber;
- (void).cxx_destruct;
- (void)pollForNewMessages;
- (void)pollingTimerFired:(id)arg1;
- (void)stopMessagePolling;
- (void)startMessagePollingWithCompletion:(CDUnknownBlockType)arg1;
- (double)pollingInterval;
- (void)fetchNewerMessagesWithCompletion:(CDUnknownBlockType)arg1;
- (void)fetchOlderMessagesWithCompletion:(CDUnknownBlockType)arg1;
- (void)fetchMessagesInDirection:(unsigned long long)arg1 timestamp:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)postMessageWithText:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)insertCannedMessageText:(id)arg1;
- (unsigned long long)addMessages:(id)arg1 forFeedId:(id)arg2;
- (_Bool)addMessage:(id)arg1;
@property(readonly, nonatomic) NSOrderedSet *sentOrReceivedMessageSet;
- (unsigned long long)indexOfMessage:(id)arg1;
- (id)messageAtIndex:(unsigned long long)arg1;
@property(readonly, nonatomic) unsigned long long messageCount;
- (void)setupChatConversationWithCompletion:(CDUnknownBlockType)arg1;
- (unsigned long long)removeSetupDelayMessage;
- (void)addSetupDelayMessage;
- (void)startReachabilityMonitoring;
@property(readonly, nonatomic) NSString *providerName;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

