//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MRTLookupType, NSString;

@interface MRTCreditCardFieldModel : NSObject
{
    MRTLookupType *_cardType;
    NSString *_nameOnCardString;
    NSString *_cardNumberString;
    NSString *_expiryDateString;
}

@property(copy, nonatomic) NSString *expiryDateString; // @synthesize expiryDateString=_expiryDateString;
@property(copy, nonatomic) NSString *cardNumberString; // @synthesize cardNumberString=_cardNumberString;
@property(copy, nonatomic) NSString *nameOnCardString; // @synthesize nameOnCardString=_nameOnCardString;
@property(copy, nonatomic) MRTLookupType *cardType; // @synthesize cardType=_cardType;
- (void).cxx_destruct;

@end

