//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableSet, NSString, NSTimer;
@protocol OS_dispatch_queue;

@interface MRTCache : NSObject
{
    double _expirationAgeInSeconds;
    NSString *_cacheName;
    id _memoryCache;
    id _dateModifiedDict;
    id _dateAccessedDict;
    NSMutableSet *_keySet;
    NSObject<OS_dispatch_queue> *_cacheQueue;
    NSObject<OS_dispatch_queue> *_dateAccessedQueue;
    NSTimer *_purgeTimer;
}

@property(retain, nonatomic) NSTimer *purgeTimer; // @synthesize purgeTimer=_purgeTimer;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *dateAccessedQueue; // @synthesize dateAccessedQueue=_dateAccessedQueue;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *cacheQueue; // @synthesize cacheQueue=_cacheQueue;
@property(retain, nonatomic) NSMutableSet *keySet; // @synthesize keySet=_keySet;
@property(retain, nonatomic) id dateAccessedDict; // @synthesize dateAccessedDict=_dateAccessedDict;
@property(retain, nonatomic) id dateModifiedDict; // @synthesize dateModifiedDict=_dateModifiedDict;
@property(retain, nonatomic) id memoryCache; // @synthesize memoryCache=_memoryCache;
@property(copy, nonatomic) NSString *cacheName; // @synthesize cacheName=_cacheName;
@property(nonatomic) double expirationAgeInSeconds; // @synthesize expirationAgeInSeconds=_expirationAgeInSeconds;
- (void).cxx_destruct;
- (void)_purgeTimerFired:(id)arg1;
- (id)allKeys;
- (id)objectForKey:(id)arg1 newerThanInterval:(double)arg2 cacheDate:(id *)arg3;
- (_Bool)isKey:(id)arg1 beyondInterval:(double)arg2;
- (void)queuedRemoveObjectForKey:(id)arg1;
- (void)queuedSetObject:(id)arg1 forKey:(id)arg2;
- (id)queuedObjectForKey:(id)arg1;
- (void)queuedSetDateModified:(id)arg1 forKey:(id)arg2;
- (void)queuedSetDateAccessed:(id)arg1 forKey:(id)arg2;
- (id)queuedDateAccessedForKey:(id)arg1;
- (id)queuedDateAddedForKey:(id)arg1;
- (void)setModifiedDate:(id)arg1 forKey:(id)arg2;
- (void)removeObjectForKey:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)objectForKey:(id)arg1;
- (id)dateAccessedForKey:(id)arg1;
- (id)dateModifiedForKey:(id)arg1;
- (id)initWithName:(id)arg1 dumpMemoryWhenBackgrounded:(_Bool)arg2;
- (id)initWithName:(id)arg1;

@end

