//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "MRTChatTextFieldViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class MRTActivityIndicatorView, MRTChatTableHeaderView, MRTChatTextFieldView, MRTChatTitleView, MRTReservation, NSLayoutConstraint, NSObject, NSString, UIColor, UITableView, UIView;
@protocol MRTChatMessagingProvider, OS_dispatch_semaphore;

@interface MRTChatViewController : UIViewController <UITableViewDataSource, UITableViewDelegate, UITextFieldDelegate, MRTChatTextFieldViewDelegate>
{
    _Bool _shouldDismissPresentingController;
    _Bool _activityIndicatorVisible;
    _Bool _sending;
    _Bool _animatePollingResponse;
    _Bool _hasViewAppeared;
    _Bool _shouldScrollToBottomOnLayout;
    NSString *_serviceRequestComment;
    UIViewController *_presentingController;
    NSString *_propertyIdentifier;
    UIColor *_propertyColor;
    CDUnknownBlockType _closeBlock;
    MRTReservation *_reservation;
    UITableView *_tableView;
    MRTChatTextFieldView *_textFieldView;
    MRTChatTitleView *_titleView;
    NSLayoutConstraint *_titleWidthConstraint;
    UIView *_inputView;
    UIView *_inputAccessoryView;
    MRTChatTableHeaderView *_tableHeaderView;
    UIView *_sectionHeaderView;
    UIView *_activityFooterView;
    MRTActivityIndicatorView *_activityIndicatorView;
    id <MRTChatMessagingProvider> _chatMessagingProvider;
    NSObject<OS_dispatch_semaphore> *_chatSetupCompleteSemaphore;
}

+ (void)setActiveChatViewController:(id)arg1;
+ (id)activeChatViewController;
@property(retain, nonatomic) NSObject<OS_dispatch_semaphore> *chatSetupCompleteSemaphore; // @synthesize chatSetupCompleteSemaphore=_chatSetupCompleteSemaphore;
@property(nonatomic) _Bool shouldScrollToBottomOnLayout; // @synthesize shouldScrollToBottomOnLayout=_shouldScrollToBottomOnLayout;
@property(nonatomic) _Bool hasViewAppeared; // @synthesize hasViewAppeared=_hasViewAppeared;
@property(nonatomic) _Bool animatePollingResponse; // @synthesize animatePollingResponse=_animatePollingResponse;
@property(nonatomic, getter=isSending) _Bool sending; // @synthesize sending=_sending;
@property(nonatomic, getter=isActivityIndicatorVisible) _Bool activityIndicatorVisible; // @synthesize activityIndicatorVisible=_activityIndicatorVisible;
@property(retain, nonatomic) id <MRTChatMessagingProvider> chatMessagingProvider; // @synthesize chatMessagingProvider=_chatMessagingProvider;
@property(retain, nonatomic) MRTActivityIndicatorView *activityIndicatorView; // @synthesize activityIndicatorView=_activityIndicatorView;
@property(retain, nonatomic) UIView *activityFooterView; // @synthesize activityFooterView=_activityFooterView;
@property(retain, nonatomic) UIView *sectionHeaderView; // @synthesize sectionHeaderView=_sectionHeaderView;
@property(retain, nonatomic) MRTChatTableHeaderView *tableHeaderView; // @synthesize tableHeaderView=_tableHeaderView;
@property(retain, nonatomic) UIView *inputAccessoryView; // @synthesize inputAccessoryView=_inputAccessoryView;
@property(retain, nonatomic) UIView *inputView; // @synthesize inputView=_inputView;
@property(retain, nonatomic) NSLayoutConstraint *titleWidthConstraint; // @synthesize titleWidthConstraint=_titleWidthConstraint;
@property(nonatomic) __weak MRTChatTitleView *titleView; // @synthesize titleView=_titleView;
@property(retain, nonatomic) MRTChatTextFieldView *textFieldView; // @synthesize textFieldView=_textFieldView;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) MRTReservation *reservation; // @synthesize reservation=_reservation;
@property(copy, nonatomic) CDUnknownBlockType closeBlock; // @synthesize closeBlock=_closeBlock;
@property(retain, nonatomic) UIColor *propertyColor; // @synthesize propertyColor=_propertyColor;
@property(copy, nonatomic) NSString *propertyIdentifier; // @synthesize propertyIdentifier=_propertyIdentifier;
@property(nonatomic) __weak UIViewController *presentingController; // @synthesize presentingController=_presentingController;
@property(nonatomic) _Bool shouldDismissPresentingController; // @synthesize shouldDismissPresentingController=_shouldDismissPresentingController;
@property(copy, nonatomic) NSString *serviceRequestComment; // @synthesize serviceRequestComment=_serviceRequestComment;
- (void).cxx_destruct;
- (_Bool)isChatViewControllerForServiceRequestId:(id)arg1 withReservationConfirmation:(id)arg2;
- (void)removePushNotificationListener;
- (void)addPushNotificationListener;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)sendButtonTouchedWithText:(id)arg1;
- (void)postChatMessageWithText:(id)arg1;
- (void)scrollToLastChatMessageAnimated:(_Bool)arg1;
- (void)_insertRowsForAddedMessageCount:(unsigned long long)arg1 atIndex:(unsigned long long)arg2;
- (void)_deleteRowsForRemovedMessageCount:(unsigned long long)arg1 atIndex:(unsigned long long)arg2;
- (void)updateRowsForOriginalMessageCount:(unsigned long long)arg1 newMessageCount:(unsigned long long)arg2 atIndex:(unsigned long long)arg3;
- (void)keyboardWillChangeFrame:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)fetchNewerMessages;
- (void)fetchOlderMessages:(id)arg1;
- (void)fetchInitialMessages;
- (void)beginPollingForChatMessages;
- (void)closeButtonTouched:(id)arg1;
@property(readonly, nonatomic) NSString *serviceRequestId;
- (long long)preferredStatusBarStyle;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (_Bool)canBecomeFirstResponder;
- (void)viewDidLayoutSubviews;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)updateTitleViewWidth:(double)arg1;
- (void)checkFirstResponder;
- (_Bool)resignFirstResponder;
- (void)viewDidLoad;
- (void)setupTitleHeader;
- (void)setupTableView;
- (void)setupActivityFooterView;
- (void)setupSectionHeaderView;
- (id)appNavigationIdentifier;
- (void)dealloc;
- (id)initWithChatMessagingProvider:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

