//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDateComponents, NSNumber, NSString, NSTimeZone;

@interface MRTDynamicContentFetchContext : NSObject
{
    _Bool _lyftEnabled;
    NSString *_propertyCity;
    NSString *_propertyCode;
    NSString *_brandCode;
    NSString *_confirmationNumber;
    NSDateComponents *_startDateComponents;
    NSDateComponents *_endDateComponents;
    NSDateComponents *_propertyCheckOutTimeComponents;
    NSDateComponents *_stayCheckOutTimeComponents;
    NSTimeZone *_propertyTimeZone;
    NSString *_propertyCountry;
    NSString *_memberLevel;
    NSString *_memberLevelCode;
    NSString *_memberCity;
    NSString *_memberCountry;
    NSString *_deviceLanguage;
    NSString *_stayStatus;
    NSNumber *_mobileDiningEnabledOrNil;
    NSNumber *_hotelShuttleEnabledOrNil;
    NSNumber *_inGuestArrivalPlanningPeriodOrNil;
    NSNumber *_inGuestDeparturePlanningPeriodOrNil;
    NSNumber *_chatStatusChangedOrNil;
    NSNumber *_serviceRequestStatusChangedOrNil;
    NSString *_checkInStatusTag;
    NSString *_stayStatusTag;
    NSString *_lateCheckoutStatusTag;
    NSString *_mobileKeyStatusTag;
    NSString *_pmsTypeTag;
    NSString *_stayTimeTag;
    NSNumber *_hasRequestedGuestServicesTag;
    NSNumber *_isCheckInPreviouslySeenTag;
    NSNumber *_isCheckOutPreviouslySeenTag;
    NSNumber *_didKeyDownloadFailTag;
    struct CLLocationCoordinate2D _propertyLocation;
    struct CLLocationCoordinate2D _userLocation;
}

@property(retain, nonatomic) NSNumber *didKeyDownloadFailTag; // @synthesize didKeyDownloadFailTag=_didKeyDownloadFailTag;
@property(retain, nonatomic) NSNumber *isCheckOutPreviouslySeenTag; // @synthesize isCheckOutPreviouslySeenTag=_isCheckOutPreviouslySeenTag;
@property(retain, nonatomic) NSNumber *isCheckInPreviouslySeenTag; // @synthesize isCheckInPreviouslySeenTag=_isCheckInPreviouslySeenTag;
@property(retain, nonatomic) NSNumber *hasRequestedGuestServicesTag; // @synthesize hasRequestedGuestServicesTag=_hasRequestedGuestServicesTag;
@property(copy, nonatomic) NSString *stayTimeTag; // @synthesize stayTimeTag=_stayTimeTag;
@property(copy, nonatomic) NSString *pmsTypeTag; // @synthesize pmsTypeTag=_pmsTypeTag;
@property(copy, nonatomic) NSString *mobileKeyStatusTag; // @synthesize mobileKeyStatusTag=_mobileKeyStatusTag;
@property(copy, nonatomic) NSString *lateCheckoutStatusTag; // @synthesize lateCheckoutStatusTag=_lateCheckoutStatusTag;
@property(copy, nonatomic) NSString *stayStatusTag; // @synthesize stayStatusTag=_stayStatusTag;
@property(copy, nonatomic) NSString *checkInStatusTag; // @synthesize checkInStatusTag=_checkInStatusTag;
@property(nonatomic) struct CLLocationCoordinate2D userLocation; // @synthesize userLocation=_userLocation;
@property(nonatomic, getter=isLyftEnabled) _Bool lyftEnabled; // @synthesize lyftEnabled=_lyftEnabled;
@property(retain, nonatomic) NSNumber *serviceRequestStatusChangedOrNil; // @synthesize serviceRequestStatusChangedOrNil=_serviceRequestStatusChangedOrNil;
@property(retain, nonatomic) NSNumber *chatStatusChangedOrNil; // @synthesize chatStatusChangedOrNil=_chatStatusChangedOrNil;
@property(retain, nonatomic) NSNumber *inGuestDeparturePlanningPeriodOrNil; // @synthesize inGuestDeparturePlanningPeriodOrNil=_inGuestDeparturePlanningPeriodOrNil;
@property(retain, nonatomic) NSNumber *inGuestArrivalPlanningPeriodOrNil; // @synthesize inGuestArrivalPlanningPeriodOrNil=_inGuestArrivalPlanningPeriodOrNil;
@property(retain, nonatomic) NSNumber *hotelShuttleEnabledOrNil; // @synthesize hotelShuttleEnabledOrNil=_hotelShuttleEnabledOrNil;
@property(retain, nonatomic) NSNumber *mobileDiningEnabledOrNil; // @synthesize mobileDiningEnabledOrNil=_mobileDiningEnabledOrNil;
@property(copy, nonatomic) NSString *stayStatus; // @synthesize stayStatus=_stayStatus;
@property(copy, nonatomic) NSString *deviceLanguage; // @synthesize deviceLanguage=_deviceLanguage;
@property(copy, nonatomic) NSString *memberCountry; // @synthesize memberCountry=_memberCountry;
@property(copy, nonatomic) NSString *memberCity; // @synthesize memberCity=_memberCity;
@property(copy, nonatomic) NSString *memberLevelCode; // @synthesize memberLevelCode=_memberLevelCode;
@property(copy, nonatomic) NSString *memberLevel; // @synthesize memberLevel=_memberLevel;
@property(copy, nonatomic) NSString *propertyCountry; // @synthesize propertyCountry=_propertyCountry;
@property(nonatomic) struct CLLocationCoordinate2D propertyLocation; // @synthesize propertyLocation=_propertyLocation;
@property(retain, nonatomic) NSTimeZone *propertyTimeZone; // @synthesize propertyTimeZone=_propertyTimeZone;
@property(retain, nonatomic) NSDateComponents *stayCheckOutTimeComponents; // @synthesize stayCheckOutTimeComponents=_stayCheckOutTimeComponents;
@property(retain, nonatomic) NSDateComponents *propertyCheckOutTimeComponents; // @synthesize propertyCheckOutTimeComponents=_propertyCheckOutTimeComponents;
@property(retain, nonatomic) NSDateComponents *endDateComponents; // @synthesize endDateComponents=_endDateComponents;
@property(retain, nonatomic) NSDateComponents *startDateComponents; // @synthesize startDateComponents=_startDateComponents;
@property(copy, nonatomic) NSString *confirmationNumber; // @synthesize confirmationNumber=_confirmationNumber;
@property(copy, nonatomic) NSString *brandCode; // @synthesize brandCode=_brandCode;
@property(copy, nonatomic) NSString *propertyCode; // @synthesize propertyCode=_propertyCode;
@property(copy, nonatomic) NSString *propertyCity; // @synthesize propertyCity=_propertyCity;
- (void).cxx_destruct;
- (id)endDateString;
- (id)startDateString;
- (id)contextDateFormatter;
- (id)init;

@end

