//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MRTDynamicContentContainer.h"

@interface MRTDynamicContentContainer (Application)
+ (void)updatePlacePassFeatureEnabled;
+ (void)load;
- (id)_stayMainMboxes;
- (id)_checkoutConfirmationTilePath;
- (id)_checkinConfirmationTilePath;
- (_Bool)shouldShowLyftContentWithUserLocation:(struct CLLocationCoordinate2D)arg1 propertyCode:(id)arg2;
- (id)_fetchContextForReservation:(id)arg1;
- (id)_memberLevelForAccount:(id)arg1;
- (void)fetchContentForStayMainWithReservation:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)fetchContentForCheckoutConfirmationWithReservation:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)fetchContentForCheckinConfirmationWithReservation:(id)arg1 completion:(CDUnknownBlockType)arg2;
@end

