//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class UIColor;

@interface MRTGradientStop : NSObject
{
    UIColor *_color;
    double _location;
}

+ (id)gradientStopWithColor:(id)arg1 location:(double)arg2;
@property(nonatomic) double location; // @synthesize location=_location;
@property(retain, nonatomic) UIColor *color; // @synthesize color=_color;
- (void).cxx_destruct;
- (id)initWithColor:(id)arg1 location:(double)arg2;

@end

