//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class MRTGradientView, MRTNotification, MRTReservation, MRTStyledButton, UIButton, UIImageView, UILabel, UIScrollView;

@interface MRTInAppMessageViewController : UIViewController
{
    _Bool _haveSetImage;
    MRTReservation *_reservation;
    MRTNotification *_notification;
    UILabel *_dateRangeLabel;
    UILabel *_hotelNameLabel;
    UILabel *_titleLabel;
    UIImageView *_imageView;
    UILabel *_upgradeFlagLabel;
    UILabel *_messageLabel;
    MRTStyledButton *_dismissButton;
    UIButton *_notNowButton;
    MRTGradientView *_gradientView;
    UIScrollView *_scrollView;
}

@property(nonatomic) _Bool haveSetImage; // @synthesize haveSetImage=_haveSetImage;
@property(nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) __weak MRTGradientView *gradientView; // @synthesize gradientView=_gradientView;
@property(nonatomic) __weak UIButton *notNowButton; // @synthesize notNowButton=_notNowButton;
@property(nonatomic) __weak MRTStyledButton *dismissButton; // @synthesize dismissButton=_dismissButton;
@property(nonatomic) __weak UILabel *messageLabel; // @synthesize messageLabel=_messageLabel;
@property(nonatomic) __weak UILabel *upgradeFlagLabel; // @synthesize upgradeFlagLabel=_upgradeFlagLabel;
@property(nonatomic) __weak UIImageView *imageView; // @synthesize imageView=_imageView;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak UILabel *hotelNameLabel; // @synthesize hotelNameLabel=_hotelNameLabel;
@property(nonatomic) __weak UILabel *dateRangeLabel; // @synthesize dateRangeLabel=_dateRangeLabel;
@property(retain, nonatomic) MRTNotification *notification; // @synthesize notification=_notification;
@property(retain, nonatomic) MRTReservation *reservation; // @synthesize reservation=_reservation;
- (void).cxx_destruct;
- (id)notNowButtonTitle;
- (id)dismissButtonTitle;
- (id)analyticsCloseButtonKey;
- (void)trackNotNowTapped;
- (void)trackCloseButtonClicked;
- (void)notNowTapped:(id)arg1;
- (void)closeButtonClicked:(id)arg1;
- (void)enableNotNowButtonIfNeeded;
- (void)enableUpgradeLabelIfNeeded;
- (id)messageForRoom:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithReservation:(id)arg1 notification:(id)arg2;

@end

