//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MRTLifetimeDetailCell.h"

@class UIImageView;

@interface MRTLifetimeDetailImageCell : MRTLifetimeDetailCell
{
    UIImageView *_ambassadorImage;
}

@property(retain, nonatomic) UIImageView *ambassadorImage; // @synthesize ambassadorImage=_ambassadorImage;
- (void).cxx_destruct;
- (id)ambassadorImageString;
- (void)awakeFromNib;

@end

