//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MRTAPIV2Request.h"

@class NSString;

@interface MRTPaymentMethodGetAPIRequest : MRTAPIV2Request
{
    _Bool _isFetchingSinglePaymentMethod;
    NSString *_paymentMethodId;
}

@property(copy, nonatomic) NSString *paymentMethodId; // @synthesize paymentMethodId=_paymentMethodId;
@property(nonatomic) _Bool isFetchingSinglePaymentMethod; // @synthesize isFetchingSinglePaymentMethod=_isFetchingSinglePaymentMethod;
- (void).cxx_destruct;
- (id)transformResponse:(id)arg1 error:(id *)arg2;
- (id)initWithPaymentMethod:(id)arg1;
- (id)initWithCreditCard:(id)arg1 consumer:(id)arg2;

@end

