//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSString;

@interface MRTPartialAppNavigationNode : NSObject
{
    NSString *_identifier;
    unsigned long long _identifierType;
    NSString *_paramKey;
    NSString *_paramValue;
    NSMutableDictionary *_parameters;
}

@property(retain, nonatomic) NSMutableDictionary *parameters; // @synthesize parameters=_parameters;
@property(copy, nonatomic) NSString *paramValue; // @synthesize paramValue=_paramValue;
@property(copy, nonatomic) NSString *paramKey; // @synthesize paramKey=_paramKey;
@property(nonatomic) unsigned long long identifierType; // @synthesize identifierType=_identifierType;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (void)reset;
- (void)moveParameterKeyAndValueToParameters;
- (id)node;
- (id)init;

@end

