//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MRTObject.h"

@class NSArray, NSNumber, NSString;

@interface MRTPool : MRTObject
{
    _Bool _onProperty;
    _Bool _outdoor;
    _Bool _indoor;
    _Bool _towelsProvided;
    _Bool _heated;
    _Bool _childrensPool;
    NSString *_identifier;
    NSString *_name;
    NSString *_poolDescription;
    NSArray *_operationHours;
    NSNumber *_distanceInMeters;
}

@property(nonatomic, getter=hasChildrensPool) _Bool childrensPool; // @synthesize childrensPool=_childrensPool;
@property(nonatomic, getter=isHeated) _Bool heated; // @synthesize heated=_heated;
@property(nonatomic, getter=hasTowelsProvided) _Bool towelsProvided; // @synthesize towelsProvided=_towelsProvided;
@property(nonatomic, getter=isIndoor) _Bool indoor; // @synthesize indoor=_indoor;
@property(nonatomic, getter=isOutdoor) _Bool outdoor; // @synthesize outdoor=_outdoor;
@property(nonatomic, getter=isOnProperty) _Bool onProperty; // @synthesize onProperty=_onProperty;
@property(retain, nonatomic) NSNumber *distanceInMeters; // @synthesize distanceInMeters=_distanceInMeters;
@property(copy, nonatomic) NSArray *operationHours; // @synthesize operationHours=_operationHours;
@property(copy, nonatomic) NSString *poolDescription; // @synthesize poolDescription=_poolDescription;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (long long)compare:(id)arg1;
- (void)assignFeaturesWithJSONDictionary:(id)arg1;
- (void)assignDistanceWithJSONDictionary:(id)arg1;
- (void)assignOperationHoursWithJSONDictionary:(id)arg1;
- (void)setValuesForKeysWithDictionary:(id)arg1;

@end

