//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MRTAPIV2Request.h"

@interface MRTPropertyInfoAPIRequest : MRTAPIV2Request
{
}

- (id)imageInfoForPhototourImage:(id)arg1 type:(id)arg2 context:(id)arg3;
- (id)roomImageInfosInPhototour:(id)arg1 context:(id)arg2;
- (id)roomIdentifiersFromPhototourDict:(id)arg1;
- (void)addFirstImageOfCategory:(id)arg1 inPhototour:(id)arg2 toProperty:(id)arg3;
- (id)firstImageOfCategory:(id)arg1 inPhototour:(id)arg2;
- (id)imageInfoForRoomIdentifier:(id)arg1 inProperty:(id)arg2;
- (unsigned long long)_roomTypeScoreForImageInfo:(id)arg1;
- (id)hotelLogoDictionariesFromArray:(id)arg1;
- (void)addImageDictionaries:(id)arg1 toInfo:(id)arg2;
- (id)validImageDictionariesFromArray:(id)arg1;
- (id)transformResponse:(id)arg1 error:(id *)arg2;
- (id)fetchRequestForIdentifier:(id)arg1;
- (id)propertyIncludes;
- (id)initWithMarshaCodes:(id)arg1;

@end

