//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MRTObject.h"

#import "NSCopying-Protocol.h"

@class NSDateComponents, NSNumber, NSString;

@interface MRTRequestedService : MRTObject <NSCopying>
{
    NSString *_optionId;
    NSString *_serviceDescription;
    NSString *_destination;
    NSDateComponents *_dueDate;
    NSString *_maxWaitTime;
    NSNumber *_quantity;
    NSString *_customerName;
    NSString *_comment;
}

@property(copy, nonatomic) NSString *comment; // @synthesize comment=_comment;
@property(copy, nonatomic) NSString *customerName; // @synthesize customerName=_customerName;
@property(copy, nonatomic) NSNumber *quantity; // @synthesize quantity=_quantity;
@property(copy, nonatomic) NSString *maxWaitTime; // @synthesize maxWaitTime=_maxWaitTime;
@property(copy, nonatomic) NSDateComponents *dueDate; // @synthesize dueDate=_dueDate;
@property(copy, nonatomic) NSString *destination; // @synthesize destination=_destination;
@property(copy, nonatomic) NSString *serviceDescription; // @synthesize serviceDescription=_serviceDescription;
@property(copy, nonatomic) NSString *optionId; // @synthesize optionId=_optionId;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)JSONDictionaryRepresentation;
- (id)dueDateISO8601TimestampFormatter;
- (id)dateFormatterForKey:(id)arg1;
- (id)initWithServiceOption:(id)arg1;

@end

