//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MRTCommonUI/MRTCollectionViewCell.h>

@class MRTConsumer, MRTGradientView, MRTStyledButton, NSArray, NSLayoutConstraint, NSMutableArray, NSOperationQueue, UIImageView, UILabel, UIStackView, UIView;

@interface MRTRewardsProgressContainerCollectionViewCell : MRTCollectionViewCell
{
    _Bool _isAnimating;
    MRTConsumer *_consumer;
    unsigned long long _type;
    MRTGradientView *_gradientView;
    UIView *_topMirroredBackgroundView;
    UILabel *_memberNumberTitleLabel;
    MRTStyledButton *_memberNumberAndCardButton;
    UILabel *_consumerNameLabel;
    UILabel *_consumerLevelLabel;
    NSLayoutConstraint *_nameLevelVerticalConstraint;
    UIStackView *_subContentStackView;
    UIImageView *_badgeImageView;
    NSLayoutConstraint *_badgeImageViewWidthConstraint;
    NSLayoutConstraint *_badgeImageViewHeightConstraint;
    MRTStyledButton *_subNameButton;
    UIView *_footerView;
    UIView *_footerBackgroundView;
    NSArray *_marginConstraints;
    NSLayoutConstraint *_currentStatusContentTopMarginConstraint;
    NSMutableArray *_animationItems;
    NSOperationQueue *_animationQueue;
}

+ (void)clearAlreadyAnimatedCellTypes;
+ (void)initialize;
@property(retain, nonatomic) NSOperationQueue *animationQueue; // @synthesize animationQueue=_animationQueue;
@property(nonatomic) _Bool isAnimating; // @synthesize isAnimating=_isAnimating;
@property(retain, nonatomic) NSMutableArray *animationItems; // @synthesize animationItems=_animationItems;
@property(nonatomic) __weak NSLayoutConstraint *currentStatusContentTopMarginConstraint; // @synthesize currentStatusContentTopMarginConstraint=_currentStatusContentTopMarginConstraint;
@property(retain, nonatomic) NSArray *marginConstraints; // @synthesize marginConstraints=_marginConstraints;
@property(nonatomic) __weak UIView *footerBackgroundView; // @synthesize footerBackgroundView=_footerBackgroundView;
@property(nonatomic) __weak UIView *footerView; // @synthesize footerView=_footerView;
@property(nonatomic) __weak MRTStyledButton *subNameButton; // @synthesize subNameButton=_subNameButton;
@property(nonatomic) __weak NSLayoutConstraint *badgeImageViewHeightConstraint; // @synthesize badgeImageViewHeightConstraint=_badgeImageViewHeightConstraint;
@property(nonatomic) __weak NSLayoutConstraint *badgeImageViewWidthConstraint; // @synthesize badgeImageViewWidthConstraint=_badgeImageViewWidthConstraint;
@property(nonatomic) __weak UIImageView *badgeImageView; // @synthesize badgeImageView=_badgeImageView;
@property(nonatomic) __weak UIStackView *subContentStackView; // @synthesize subContentStackView=_subContentStackView;
@property(nonatomic) __weak NSLayoutConstraint *nameLevelVerticalConstraint; // @synthesize nameLevelVerticalConstraint=_nameLevelVerticalConstraint;
@property(nonatomic) __weak UILabel *consumerLevelLabel; // @synthesize consumerLevelLabel=_consumerLevelLabel;
@property(nonatomic) __weak UILabel *consumerNameLabel; // @synthesize consumerNameLabel=_consumerNameLabel;
@property(nonatomic) __weak MRTStyledButton *memberNumberAndCardButton; // @synthesize memberNumberAndCardButton=_memberNumberAndCardButton;
@property(nonatomic) __weak UILabel *memberNumberTitleLabel; // @synthesize memberNumberTitleLabel=_memberNumberTitleLabel;
@property(retain, nonatomic) UIView *topMirroredBackgroundView; // @synthesize topMirroredBackgroundView=_topMirroredBackgroundView;
@property(nonatomic) __weak MRTGradientView *gradientView; // @synthesize gradientView=_gradientView;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(retain, nonatomic) MRTConsumer *consumer; // @synthesize consumer=_consumer;
- (void).cxx_destruct;
- (id)yearsAsStatusOrHigherText;
- (void)performAnimationWithDelay:(double)arg1;
- (void)willBeDisplayed;
- (void)updateConstraints;
- (void)tapLifetimeStatusInfoButton:(id)arg1;
- (void)tapBenefitsButton:(id)arg1;
- (id)lifetimeTitleString;
- (id)benefitsTitleString;
- (void)updateAccessibility;
- (void)traitCollectionDidChange:(id)arg1;
- (void)resetValuesWithType:(unsigned long long)arg1 consumer:(id)arg2;
- (void)buildLifetimeViewWithTextColor:(id)arg1 andConsumer:(id)arg2;
- (void)buildCurrentViewWithTextColor:(id)arg1 andConsumer:(id)arg2;
- (void)resetWithConsumer:(id)arg1 andType:(unsigned long long)arg2;
- (void)updateNameLabelFontWithTraits:(id)arg1;
- (void)updateColorsWithConsumer:(id)arg1 withType:(unsigned long long)arg2;
- (void)consumerChanged;
- (void)dealloc;
- (void)awakeFromNib;

@end

