//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MRTReviewReservationTableCell.h"

@class UILabel;

@interface MRTReservationConfirmationHeaderTableCell : MRTReviewReservationTableCell
{
    UILabel *_confirmHeaderLabel;
    UILabel *_confirmationNumberLabel;
    UILabel *_confirmationEmailLabel;
}

@property(nonatomic) __weak UILabel *confirmationEmailLabel; // @synthesize confirmationEmailLabel=_confirmationEmailLabel;
@property(nonatomic) __weak UILabel *confirmationNumberLabel; // @synthesize confirmationNumberLabel=_confirmationNumberLabel;
@property(nonatomic) __weak UILabel *confirmHeaderLabel; // @synthesize confirmHeaderLabel=_confirmHeaderLabel;
- (void).cxx_destruct;

@end

