//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MRTRewardsAccountTableCell.h"

#import "UICollectionViewDataSource-Protocol.h"

@class MRTStyledLabel, NSString, UIButton, UICollectionView;

@interface MRTRewardsFavoritesCell : MRTRewardsAccountTableCell <UICollectionViewDataSource>
{
    UICollectionView *_favoritesCollectionView;
    UIButton *_manageButton;
    MRTStyledLabel *_savedHotelsLabel;
}

+ (_Bool)isVisibleInController:(id)arg1;
@property(nonatomic) __weak MRTStyledLabel *savedHotelsLabel; // @synthesize savedHotelsLabel=_savedHotelsLabel;
@property(nonatomic) __weak UIButton *manageButton; // @synthesize manageButton=_manageButton;
@property(nonatomic) __weak UICollectionView *favoritesCollectionView; // @synthesize favoritesCollectionView=_favoritesCollectionView;
- (void).cxx_destruct;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)resetValuesWithConsumer:(id)arg1 inViewController:(id)arg2;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

