//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MRTReservationViewController.h"

#import "MRTGuestEditInfoHandler-Protocol.h"
#import "MRTReviewReservationButtonsDelegate-Protocol.h"
#import "MRTReviewReservationCancelButtonDelegate-Protocol.h"

@class MRTAddPaymentMethodParams, MRTEditGuestInfoViewController, MRTGuest, MRTReviewReservationHeaderTableCell, MRTShoppingCart, MRTStyledButton, MRTStyledLabel, NSLayoutConstraint, NSMutableArray, NSString, UIImageView, UIView;

@interface MRTReviewReservationViewController : MRTReservationViewController <MRTReviewReservationCancelButtonDelegate, MRTReviewReservationButtonsDelegate, MRTGuestEditInfoHandler>
{
    _Bool _saveGuestInfoToProfile;
    id _delegate;
    NSString *_selectedRateTabType;
    MRTStyledButton *_floatingBookButton;
    MRTStyledButton *_floatingCancelButton;
    UIView *_floatingBookButtonBackgroundView;
    UIImageView *_floatingBookButtonErrorImageView;
    MRTStyledLabel *_floatingBookButtonPriceLabel;
    MRTStyledLabel *_floatingBookButtonScrollToBookLabel;
    NSLayoutConstraint *_floatingButtonViewTrailingConstraint;
    NSLayoutConstraint *_floatingButtonViewLeadingConstraint;
    NSLayoutConstraint *_floatingBookButtonCenterHorizontallyConstraint;
    NSLayoutConstraint *_floatingBookButtonPriceTopConstraint;
    MRTShoppingCart *_cart;
    MRTEditGuestInfoViewController *_editGuestInfoViewController;
    MRTGuest *_guest;
    MRTReviewReservationHeaderTableCell *_headerTableCell;
    MRTAddPaymentMethodParams *_addPaymentMethodParams;
    unsigned long long _profileSaveCount;
    NSMutableArray *_profileSaveErrors;
}

@property(retain, nonatomic) NSMutableArray *profileSaveErrors; // @synthesize profileSaveErrors=_profileSaveErrors;
@property(nonatomic) unsigned long long profileSaveCount; // @synthesize profileSaveCount=_profileSaveCount;
@property(retain, nonatomic) MRTAddPaymentMethodParams *addPaymentMethodParams; // @synthesize addPaymentMethodParams=_addPaymentMethodParams;
@property(retain, nonatomic) MRTReviewReservationHeaderTableCell *headerTableCell; // @synthesize headerTableCell=_headerTableCell;
@property(retain, nonatomic) MRTGuest *guest; // @synthesize guest=_guest;
@property(retain, nonatomic) MRTEditGuestInfoViewController *editGuestInfoViewController; // @synthesize editGuestInfoViewController=_editGuestInfoViewController;
@property(nonatomic) _Bool saveGuestInfoToProfile; // @synthesize saveGuestInfoToProfile=_saveGuestInfoToProfile;
@property(retain, nonatomic) MRTShoppingCart *cart; // @synthesize cart=_cart;
@property(retain, nonatomic) NSLayoutConstraint *floatingBookButtonPriceTopConstraint; // @synthesize floatingBookButtonPriceTopConstraint=_floatingBookButtonPriceTopConstraint;
@property(retain, nonatomic) NSLayoutConstraint *floatingBookButtonCenterHorizontallyConstraint; // @synthesize floatingBookButtonCenterHorizontallyConstraint=_floatingBookButtonCenterHorizontallyConstraint;
@property(nonatomic) __weak NSLayoutConstraint *floatingButtonViewLeadingConstraint; // @synthesize floatingButtonViewLeadingConstraint=_floatingButtonViewLeadingConstraint;
@property(nonatomic) __weak NSLayoutConstraint *floatingButtonViewTrailingConstraint; // @synthesize floatingButtonViewTrailingConstraint=_floatingButtonViewTrailingConstraint;
@property(nonatomic) __weak MRTStyledLabel *floatingBookButtonScrollToBookLabel; // @synthesize floatingBookButtonScrollToBookLabel=_floatingBookButtonScrollToBookLabel;
@property(nonatomic) __weak MRTStyledLabel *floatingBookButtonPriceLabel; // @synthesize floatingBookButtonPriceLabel=_floatingBookButtonPriceLabel;
@property(retain, nonatomic) UIImageView *floatingBookButtonErrorImageView; // @synthesize floatingBookButtonErrorImageView=_floatingBookButtonErrorImageView;
@property(nonatomic) __weak UIView *floatingBookButtonBackgroundView; // @synthesize floatingBookButtonBackgroundView=_floatingBookButtonBackgroundView;
@property(retain, nonatomic) MRTStyledButton *floatingCancelButton; // @synthesize floatingCancelButton=_floatingCancelButton;
@property(nonatomic) __weak MRTStyledButton *floatingBookButton; // @synthesize floatingBookButton=_floatingBookButton;
@property(copy, nonatomic) NSString *selectedRateTabType; // @synthesize selectedRateTabType=_selectedRateTabType;
@property(nonatomic) __weak id delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)termsAndConditionsLinkTitle;
- (id)termsAndConditions;
- (id)alertAreYouSureTitle;
- (id)alertNeverMindButtonTitle;
- (id)changeStayDatesAlertButtonTitle;
- (id)changeStayDatesAlertMessage;
- (id)changeRoomAlertButtonTitle;
- (id)changeRoomAlertMessage;
- (id)floatingBookButtonAcceptTermsErrorText;
- (id)floatingBookButtonGuestErrorText;
- (id)floatingBookButtonPaymentErrorText;
- (void)_reportURLReplacementFailureForAttributedString:(id)arg1;
- (void)handlePaymentMethod:(id)arg1 creditCardFieldModel:(id)arg2 addPaymentMethodParams:(id)arg3;
- (void)updateGuestInfo:(id)arg1 saveToProfile:(_Bool)arg2;
- (id)appNavigationIdentifier;
- (void)callButtonPressed:(id)arg1;
- (id)dequeueReviewReservationBookButtonCell;
- (id)dequeueReviewReservationAcceptTermsCell:(long long)arg1;
- (id)dequeuePaymentMethodCell;
- (id)dequeueGuestInfoCell;
- (id)dequeueModifyReservationHeaderCell;
- (id)dequeueChargesHeaderCell;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)viewDidLayoutSubviews;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)oneButtonOverlayLayoutMarginsWillChange:(struct UIEdgeInsets)arg1;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)updateFloatingButtonConstraints:(double)arg1;
- (void)scrollToCell:(long long)arg1 atScrollPosition:(long long)arg2;
- (void)floatingBookButtonClicked:(id)arg1;
- (void)floatingCancelButtonClicked:(id)arg1;
- (void)fadeInDoneButton;
- (void)reportError:(id)arg1 underlying:(id)arg2;
- (id)enterNewPaymentMethodText;
- (id)modifyEnterNewPaymentMethodText;
- (id)bookingFailedErrorText;
- (id)guestInformationMissingErrorText;
- (id)guestInformationMissingEmailErrorText;
- (_Bool)hasValidGuestInformationForBooking;
- (void)disableInteraction;
- (void)enableInteraction;
- (void)displayTripAPIError:(id)arg1;
- (_Bool)isPaymentError:(id)arg1;
- (void)unwindToReservationInfo;
- (void)displayProfileSaveErrorMessage;
- (void)displayProfileSaveSuccessMessage;
- (void)displayNeedToEarnMorePointsMessage;
- (void)displaySaveProfileGroupResults;
- (void)_addPaymentMethodToConsumerAccountCompletion:(CDUnknownBlockType)arg1;
- (void)_updateConsumerWithGuestInfoCompletion:(CDUnknownBlockType)arg1;
- (void)_updateConsumerPreferencesCompletion:(CDUnknownBlockType)arg1;
- (void)saveUserProfile;
- (void)_fetchConsumerRewardsBalance:(CDUnknownBlockType)arg1;
- (_Bool)hasEnoughPointsForRedemption;
- (void)reportBookingError:(id)arg1;
- (void)bookTrip;
- (id)reservationRetrievalErrorText;
- (void)determineValidPaymentMethod;
- (void)propertyUpdated:(id)arg1;
- (void)prepareWithProduct:(id)arg1 searchRequest:(id)arg2;
- (void)checkAcceptedCreditCardTypes;
- (id)profileMergedWithAddons;
- (_Bool)isPointsAdvanceReservation;
- (_Bool)isBookingPointsAdvanceReservationOutsideRedemptionWindow;
- (void)_loadBookingConfirmationController;
- (_Bool)hasUnbookableErrors;
- (void)unwindToCalendar;
- (void)userDidSwitchAcceptance:(id)arg1;
- (void)showChangeStayDatesAlert;
- (void)showChangeRoomAlert;
- (void)showAlertWithMessage:(id)arg1 proceedButtonTitle:(id)arg2 proceedAction:(CDUnknownBlockType)arg3;
- (void)showSingleActionAlertWithMessage:(id)arg1 proceedButtonTitle:(id)arg2 proceedAction:(CDUnknownBlockType)arg3;
- (void)dismiss;
- (void)setFixedBookButtonErrorText:(id)arg1;
- (void)updateBookButtonMessages;
- (_Bool)guestInfoHasError;
- (_Bool)paymentMethodHasError;
- (void)updatePricingCells;
- (void)computeAddOns;
- (void)postGuest;
- (void)fetchProductTotalsViaCart;
- (void)trackMissingProductData;
- (void)fetchProductRules;
- (id)createCartErrorText;
- (void)showCartFailureAlert;
- (void)postShoppingCart;
- (void)hideRetrievingRatesIndicator;
- (void)showRetrievingRatesIndicator;
- (id)loadingReviewScreenString;
- (void)viewDidAppear:(_Bool)arg1;
- (_Bool)isBookSearchViewControllerInStack;
- (id)analyticsPageName;
- (id)consumerPreferencesFetchFailedText;
- (void)fetchConsumerPreferencesWithCompletion:(CDUnknownBlockType)arg1;
- (void)fetchStatementCreditOffer:(CDUnknownBlockType)arg1;
- (void)checkIfAbleToProceedWithSuiteNights;
- (void)updateAddOns;
- (void)dealloc;
- (void)viewDidLoad;
- (long long)preferredStatusBarStyle;
- (id)cellTypeOrdering;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

