//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MRTReviewReservationTableCell.h"

@class UILabel;

@interface MRTReviewReservationChargesDetailCell : MRTReviewReservationTableCell
{
    UILabel *_dateRange;
    UILabel *_price;
}

@property(nonatomic) __weak UILabel *price; // @synthesize price=_price;
@property(nonatomic) __weak UILabel *dateRange; // @synthesize dateRange=_dateRange;
- (void).cxx_destruct;
- (void)awakeFromNib;

@end

