//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface MRTSummaryOfChargesModel : NSObject
{
    NSMutableArray *_lineItems;
}

@property(retain, nonatomic) NSMutableArray *lineItems; // @synthesize lineItems=_lineItems;
- (void).cxx_destruct;
- (id)_combinedAccessibilityLabelWithLeft:(id)arg1 right:(id)arg2;
- (void)addLineItemWithLeftText:(id)arg1 leftAccessibilityText:(id)arg2 rightText:(id)arg3 rightAccessibilityText:(id)arg4;
- (void)addLineItemWithLeftText:(id)arg1 rightText:(id)arg2;
- (void)addHeaderWithText:(id)arg1 accessibilityText:(id)arg2;
- (void)addHeaderWithText:(id)arg1;
- (id)init;

@end

