//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MRTObject.h"

@class NSArray, NSString;

@interface MRTStayParams : MRTObject
{
    NSString *_customerIdentifier;
    NSString *_reservationIdentifier;
    NSArray *_confirmationNumbers;
    NSString *_deviceId;
}

@property(copy, nonatomic) NSString *deviceId; // @synthesize deviceId=_deviceId;
@property(retain, nonatomic) NSArray *confirmationNumbers; // @synthesize confirmationNumbers=_confirmationNumbers;
@property(copy, nonatomic) NSString *reservationIdentifier; // @synthesize reservationIdentifier=_reservationIdentifier;
@property(copy, nonatomic) NSString *customerIdentifier; // @synthesize customerIdentifier=_customerIdentifier;
- (void).cxx_destruct;
- (id)keyAliases;

@end

