//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MRTCommonUI/MRTParallaxTableViewCell.h>

@class MRTStyledLabel;

@interface MRTStaySectionHeaderCell : MRTParallaxTableViewCell
{
    MRTStyledLabel *_headerLabel;
}

@property(nonatomic) __weak MRTStyledLabel *headerLabel; // @synthesize headerLabel=_headerLabel;
- (void).cxx_destruct;
- (void)setHeaderTitle:(id)arg1;

@end

