//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MRTCommonUI/MRTParallaxTableViewCell.h>

@class MRTGradientView, MRTRemoteImageView, MRTStyledLabel, NSArray, NSString, NSURL, UIImageView, UILabel, UIStackView, UIView, _MRTStayMainBottomProtectionView;

@interface MRTStayMainTableViewCell : MRTParallaxTableViewCell
{
    NSArray *_marginConstraints;
    UILabel *_addressLabel;
    UILabel *_callLabel;
    MRTRemoteImageView *_hotelImageView;
    UIView *_largeTappableView;
    MRTStyledLabel *_hotelNameLabel;
    MRTGradientView *_gradientView;
    UIView *_darkenView;
    _MRTStayMainBottomProtectionView *_bottomProtectionView;
    UIImageView *_brandImageView;
    UILabel *_dateLabel;
    UILabel *_confirmationNumberLabel;
    NSURL *_imageURL;
    NSString *_propertyCode;
    NSString *_analyticsPageName;
    UIView *_topBGView;
    UIStackView *_addressStackView;
}

@property(retain, nonatomic) UIStackView *addressStackView; // @synthesize addressStackView=_addressStackView;
@property(retain, nonatomic) UIView *topBGView; // @synthesize topBGView=_topBGView;
@property(copy, nonatomic) NSString *analyticsPageName; // @synthesize analyticsPageName=_analyticsPageName;
@property(copy, nonatomic) NSString *propertyCode; // @synthesize propertyCode=_propertyCode;
@property(copy, nonatomic) NSURL *imageURL; // @synthesize imageURL=_imageURL;
@property(retain, nonatomic) UILabel *confirmationNumberLabel; // @synthesize confirmationNumberLabel=_confirmationNumberLabel;
@property(retain, nonatomic) UILabel *dateLabel; // @synthesize dateLabel=_dateLabel;
@property(retain, nonatomic) UIImageView *brandImageView; // @synthesize brandImageView=_brandImageView;
@property(retain, nonatomic) _MRTStayMainBottomProtectionView *bottomProtectionView; // @synthesize bottomProtectionView=_bottomProtectionView;
@property(retain, nonatomic) UIView *darkenView; // @synthesize darkenView=_darkenView;
@property(retain, nonatomic) MRTGradientView *gradientView; // @synthesize gradientView=_gradientView;
@property(retain, nonatomic) MRTStyledLabel *hotelNameLabel; // @synthesize hotelNameLabel=_hotelNameLabel;
@property(retain, nonatomic) UIView *largeTappableView; // @synthesize largeTappableView=_largeTappableView;
@property(retain, nonatomic) MRTRemoteImageView *hotelImageView; // @synthesize hotelImageView=_hotelImageView;
@property(retain, nonatomic) UILabel *callLabel; // @synthesize callLabel=_callLabel;
@property(retain, nonatomic) UILabel *addressLabel; // @synthesize addressLabel=_addressLabel;
@property(nonatomic) __weak NSArray *marginConstraints; // @synthesize marginConstraints=_marginConstraints;
- (void).cxx_destruct;
- (struct CGSize)suggestedHotelImageSizeForCellSize:(struct CGSize)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)updateWithTintColor:(id)arg1;
- (void)addressSectionTapped;
- (id)accessibilityLabel;
- (void)awakeFromNib;
- (id)largeTappableViewAccessibilityLabel;
- (void)_updateImageProtectionWithKeyColor:(id)arg1 reservation:(id)arg2;
- (id)_propertyOrCachedPropertyForReservation:(id)arg1;
- (id)_defaultKeyColorForReservation:(id)arg1;
- (void)_resetWithNoPropertyImageForReservation:(id)arg1;
- (void)_updateControlsWithReservation:(id)arg1;
- (id)_brandFallbackRemoteImageForReservation:(id)arg1;
- (id)_propertyRemoteImageForReservation:(id)arg1;
- (id)_stubPropertyRemoteImageForReseration:(id)arg1;
- (void)_updateHotelImageWithRemoteImages:(id)arg1 imageSizeInPixels:(struct CGSize)arg2 reservation:(id)arg3;
- (void)setValuesWithReservation:(id)arg1 imageCache:(id)arg2 imageSizeInPoints:(struct CGSize)arg3;

@end

