//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MRTConsumer, MRTRewardsAccount, MRTRewardsSummary, MRTWalletPassTemplate, NSString;

@interface MRTWalletPass : NSObject
{
    NSString *_name;
    MRTConsumer *_consumer;
    MRTRewardsAccount *_rewardsAccount;
    MRTRewardsSummary *_rewardsSummary;
    MRTWalletPassTemplate *_walletPassTemplate;
    NSString *_passTypeIdentifier;
    NSString *_teamIdentifier;
    NSString *_serialNumber;
}

+ (id)walletDateStringForDate:(id)arg1;
+ (_Bool)isWalletSupported;
+ (_Bool)isAppFeatureEnabled;
@property(copy, nonatomic) NSString *serialNumber; // @synthesize serialNumber=_serialNumber;
@property(copy, nonatomic) NSString *teamIdentifier; // @synthesize teamIdentifier=_teamIdentifier;
@property(copy, nonatomic) NSString *passTypeIdentifier; // @synthesize passTypeIdentifier=_passTypeIdentifier;
@property(retain, nonatomic) MRTWalletPassTemplate *walletPassTemplate; // @synthesize walletPassTemplate=_walletPassTemplate;
@property(retain, nonatomic) MRTRewardsSummary *rewardsSummary; // @synthesize rewardsSummary=_rewardsSummary;
@property(retain, nonatomic) MRTRewardsAccount *rewardsAccount; // @synthesize rewardsAccount=_rewardsAccount;
@property(retain, nonatomic) MRTConsumer *consumer; // @synthesize consumer=_consumer;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)rewardsLevelAttributed;
- (id)rewardsPointsLabelText;
- (id)contactGlobalRewardsNumber;
- (id)contactGlobalReservationsNumber;
- (id)contactRewardsNumber;
- (id)contactReservationsNumber;
- (id)contactGlobalRewardsLabelText;
- (id)contactGlobalReservationsLabelText;
- (id)contactRewardsLabelText;
- (id)contactReservationsLabelText;
- (id)organizationName;
- (id)colonSpacing;
- (id)rewardsMemberURL;
- (id)goldMemberURL;
- (id)silverMemberURL;
- (id)platinumMemberURL;
- (id)storeIdentifier;
- (void)signPassWithCompletion:(CDUnknownBlockType)arg1;
- (id)apiRequestParametersForPassTemplate:(id)arg1;
- (void)updateWalletWithCompletion:(CDUnknownBlockType)arg1;
- (id)passSubstitutionValues;
- (id)apiRequestTypeCode;
- (id)passFromUsersWallet;
- (_Bool)otherPassPreconditions;
- (id)initWithName:(id)arg1 consumer:(id)arg2;

@end

