//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface NSTNOptOutChoice : NSObject
{
    _Bool _choice;
}

@property _Bool choice; // @synthesize choice=_choice;
- (void)loadSavedChoice;
- (void)saveChoice;
- (void)updateChoice:(_Bool)arg1;
- (id)choiceString;
- (void)loadDefault;
- (id)init;

@end

