//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "CloudVoiceChatBotDelegate-Protocol.h"

@class NSString;
@protocol CloudVoiceChatBotProtocol;

@interface ChatRobotManage : NSObject <CloudVoiceChatBotDelegate>
{
    id <CloudVoiceChatBotProtocol> _chatBotManager;
}

+ (id)sharedInstances;
@property(retain, nonatomic) id <CloudVoiceChatBotProtocol> chatBotManager; // @synthesize chatBotManager=_chatBotManager;
- (void).cxx_destruct;
- (void)recoreCompletionWithResult:(long long)arg1 msg:(id)arg2 ext1:(id)arg3;
- (void)openWebChatPage;
- (void)openChatPage;
- (void)initWithAppid:(id)arg1 uuid:(id)arg2;
- (void)stopRecord;
- (void)startRecord:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

