//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LTBaseView.h"

#import "UITextFieldDelegate-Protocol.h"
#import "UIWebViewDelegate-Protocol.h"

@class NSString, UIImageView, UIWebView;

@interface GameProblemView : LTBaseView <UITextFieldDelegate, UIWebViewDelegate>
{
    UIWebView *_web;
    UIImageView *_logoImageView;
}

@property(retain, nonatomic) UIImageView *logoImageView; // @synthesize logoImageView=_logoImageView;
@property(retain, nonatomic) UIWebView *web; // @synthesize web=_web;
- (void).cxx_destruct;
- (void)interfacePortrait;
- (void)createViews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

