//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GXGBDMessage_Object, NSString;

@protocol GXGBDMessageStore <NSObject>
- (void)clear:(NSString *)arg1;
- (NSString *)storeMessage:(GXGBDMessage_Object *)arg1 msgId:(NSString *)arg2 taskId:(NSString *)arg3 appId:(NSString *)arg4;
- (_Bool)hasStoredMsgId:(NSString *)arg1 taskId:(NSString *)arg2 appId:(NSString *)arg3;
- (GXGBDMessage_Object *)retriveMsgById:(NSString *)arg1;
@end

