//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (CSS)
- (id)ysf_stringByDecodingCSSContentAttribute;
- (id)ysf_arrayOfCSSShadowsWithCurrentTextSize:(double)arg1 currentColor:(id)arg2;
- (struct UIEdgeInsets)ysf_DTEdgeInsetsRelativeToCurrentTextSize:(double)arg1 textScale:(double)arg2;
- (double)ysf_pixelSizeOfCSSMeasureRelativeToCurrentTextSize:(double)arg1 textScale:(double)arg2;
- (_Bool)ysf_isCSSLengthValue;
- (id)ysf_dictionaryOfCSSStyles;
@end

