//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface QYKFGetSessionInfoById : NSObject
{
    CDUnknownBlockType _byYxIdcb;
}

+ (id)sharedInstance;
@property(copy, nonatomic) CDUnknownBlockType byYxIdcb; // @synthesize byYxIdcb=_byYxIdcb;
- (void).cxx_destruct;
- (long long)GetSessionIdByYxId:(id)arg1;
- (void)registerByYxIdCallback:(CDUnknownBlockType)arg1;

@end

