//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "ZXCaptureDelegate-Protocol.h"

@class NSString, UIImageView, ZXCapture;

@interface ScanViewController : UIViewController <ZXCaptureDelegate>
{
    struct CGAffineTransform _captureSizeTransform;
    NSString *callback;
    UIImageView *_centerView;
    ZXCapture *_capture;
}

@property(retain, nonatomic) ZXCapture *capture; // @synthesize capture=_capture;
@property(retain, nonatomic) UIImageView *centerView; // @synthesize centerView=_centerView;
@property(retain, nonatomic) NSString *callback; // @synthesize callback;
- (void)cancelBtnClick:(id)arg1;
- (void)captureResult:(id)arg1 result:(id)arg2;
- (id)barcodeFormatToString:(int)arg1;
- (void)didReceiveMemoryWarning;
- (void)applyRectOfInterest:(long long)arg1;
- (void)applyOrientation;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

