//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface UIView (MJExtension)
@property(nonatomic) struct CGPoint ysf_origin;
@property(nonatomic) struct CGSize ysf_size;
@property(nonatomic) double ysf_h;
@property(nonatomic) double ysf_w;
@property(nonatomic) double ysf_y;
@property(nonatomic) double ysf_x;
@end

