//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSString;

@interface YSF_NIMRSAConfig : NSObject <NSCoding>
{
    NSString *_module;
    long long _version;
    long long _crc32;
}

+ (id)keyFilepath;
+ (id)readLocalConfig;
+ (id)config:(id)arg1 version:(long long)arg2;
@property(nonatomic) long long crc32; // @synthesize crc32=_crc32;
@property(nonatomic) long long version; // @synthesize version=_version;
@property(retain, nonatomic) NSString *module; // @synthesize module=_module;
- (void).cxx_destruct;
- (long long)calcCRC:(id)arg1 version:(long long)arg2;
- (_Bool)isValidConfig;
- (_Bool)save;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

