//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol YSF_NIMResourceManager <NSObject>
- (NSString *)convertHttpToHttps:(NSString *)arg1;
- (void)cleanResourceCacheWithBlock:(void (^)(NSError *))arg1;
- (void)deleteFileByPath:(NSString *)arg1 completionBlock:(void (^)(NSError *))arg2;
- (void)cancelTask:(NSString *)arg1;
- (void)download:(NSString *)arg1 filepath:(NSString *)arg2 progress:(void (^)(double))arg3 completion:(void (^)(NSError *))arg4;
- (void)upload:(NSString *)arg1 progress:(void (^)(double))arg2 completion:(void (^)(NSString *, NSError *))arg3;
@end

