//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface YSF_NIMCustomSystemNotification : NSObject
{
    _Bool _sendToOnlineUsersOnly;
    double _timestamp;
    NSString *_sender;
    NSString *_receiver;
    long long _receiverType;
    NSString *_content;
    NSString *_apnsContent;
    long long _msgId;
}

@property(nonatomic) long long msgId; // @synthesize msgId=_msgId;
@property(copy, nonatomic) NSString *apnsContent; // @synthesize apnsContent=_apnsContent;
@property(nonatomic) _Bool sendToOnlineUsersOnly; // @synthesize sendToOnlineUsersOnly=_sendToOnlineUsersOnly;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
@property(nonatomic) long long receiverType; // @synthesize receiverType=_receiverType;
@property(copy, nonatomic) NSString *receiver; // @synthesize receiver=_receiver;
@property(copy, nonatomic) NSString *sender; // @synthesize sender=_sender;
@property(nonatomic) double timestamp; // @synthesize timestamp=_timestamp;
- (void).cxx_destruct;
- (long long)receiverType:(const struct Property *)arg1;
- (id)description;
- (void)commonInit;
- (id)initWithPorperty:(const struct Property *)arg1;
- (id)initWithContent:(id)arg1;
- (id)init;

@end

