//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "YSF_NIMMessageObject-Protocol.h"
#import "YSF_NIMMessageObject_Private-Protocol.h"

@class NSString, UIImage, YSF_NIMImageOption, YSF_NIMMessage;

@interface YSF_NIMImageObject : NSObject <YSF_NIMMessageObject_Private, YSF_NIMMessageObject>
{
    YSF_NIMMessage *_message;
    NSString *_displayName;
    YSF_NIMImageOption *_option;
    long long _fileLength;
    NSString *_md5;
    NSString *_fileName;
    UIImage *_image;
    NSString *_url;
    struct CGSize _size;
}

@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(copy, nonatomic) NSString *fileName; // @synthesize fileName=_fileName;
@property(nonatomic) struct CGSize size; // @synthesize size=_size;
@property(copy, nonatomic) NSString *md5; // @synthesize md5=_md5;
@property(nonatomic) long long fileLength; // @synthesize fileLength=_fileLength;
@property(retain, nonatomic) YSF_NIMImageOption *option; // @synthesize option=_option;
@property(copy, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
@property(nonatomic) __weak YSF_NIMMessage *message; // @synthesize message=_message;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *thumbPath;
@property(readonly, copy, nonatomic) NSString *path;
@property(readonly, copy, nonatomic) NSString *thumbUrl;
- (id)thumbName;
- (id)imageName;
- (id)prepareForDownLoad;
- (id)prepareForSend;
- (id)thumbText;
- (long long)type;
- (id)uploadURL;
- (void)setUploadURL:(id)arg1;
- (id)fileParamForDownload;
- (_Bool)needUpload;
- (id)filepathForUpload;
- (void)decodeWithContent:(id)arg1;
- (id)encodeContent;
- (id)init;
- (id)initWithImage:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

