//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface YSFInputEmoticonLayout : NSObject
{
    _Bool _emoji;
    long long _rows;
    long long _columes;
    long long _itemCountInPage;
    double _cellWidth;
    double _cellHeight;
    double _imageWidth;
    double _imageHeight;
}

@property(nonatomic) _Bool emoji; // @synthesize emoji=_emoji;
@property(nonatomic) double imageHeight; // @synthesize imageHeight=_imageHeight;
@property(nonatomic) double imageWidth; // @synthesize imageWidth=_imageWidth;
@property(nonatomic) double cellHeight; // @synthesize cellHeight=_cellHeight;
@property(nonatomic) double cellWidth; // @synthesize cellWidth=_cellWidth;
@property(nonatomic) long long itemCountInPage; // @synthesize itemCountInPage=_itemCountInPage;
@property(nonatomic) long long columes; // @synthesize columes=_columes;
@property(nonatomic) long long rows; // @synthesize rows=_rows;
- (id)initCharletLayout:(double)arg1;
- (id)initEmojiLayout:(double)arg1;

@end

