//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "YSFAttributedTextContentViewDelegate-Protocol.h"

@class NSString, YSFAttributedTextView;

@interface YSFQuickReplyPreviewView : UIView <YSFAttributedTextContentViewDelegate>
{
    _Bool _isRichContent;
    CDUnknownBlockType _cancelBlock;
    CDUnknownBlockType _sendBlock;
    UIView *_contentView;
    YSFAttributedTextView *_textView;
    NSString *_contentText;
}

@property(nonatomic) _Bool isRichContent; // @synthesize isRichContent=_isRichContent;
@property(copy, nonatomic) NSString *contentText; // @synthesize contentText=_contentText;
@property(retain, nonatomic) YSFAttributedTextView *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(copy, nonatomic) CDUnknownBlockType sendBlock; // @synthesize sendBlock=_sendBlock;
@property(copy, nonatomic) CDUnknownBlockType cancelBlock; // @synthesize cancelBlock=_cancelBlock;
- (void).cxx_destruct;
- (struct CGSize)getContentSizeWithText:(id)arg1;
- (id)attributedString:(id)arg1;
- (id)attributedTextContentView:(id)arg1 viewForAttachment:(id)arg2 frame:(struct CGRect)arg3;
- (void)onTapConfirmButton:(id)arg1;
- (void)onTapCancelButton:(id)arg1;
- (void)initUI;
- (id)initWithContent:(id)arg1 isRichContent:(_Bool)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

