//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "YSF_NIMCustomAttachment-Protocol.h"

@class NSString;

@interface YSFWelcome : NSObject <YSF_NIMCustomAttachment>
{
    long long _command;
    NSString *_userId;
    NSString *_deviceId;
    long long _sessionId;
    NSString *_welcome;
}

+ (id)objectByDict:(id)arg1;
@property(copy, nonatomic) NSString *welcome; // @synthesize welcome=_welcome;
@property(nonatomic) long long sessionId; // @synthesize sessionId=_sessionId;
@property(copy, nonatomic) NSString *deviceId; // @synthesize deviceId=_deviceId;
@property(copy, nonatomic) NSString *userId; // @synthesize userId=_userId;
@property(nonatomic) long long command; // @synthesize command=_command;
- (void).cxx_destruct;
- (id)encodeAttachment;
- (id)thumbText;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

