//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface JPushExtensionLog : NSObject
{
    _Bool _logOff;
}

+ (void)logWithFormat:(id)arg1;
+ (void)setLogOff;
+ (id)share;
@property(nonatomic) _Bool logOff; // @synthesize logOff=_logOff;
- (void)logWithMessage:(id)arg1;
- (void)setLogOff;

@end

