//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface UMSociallHandlerInfo : NSObject
{
    NSMutableDictionary *_sociallHandlerInfoDic;
}

+ (id)defaultManager;
@property(retain, nonatomic) NSMutableDictionary *sociallHandlerInfoDic; // @synthesize sociallHandlerInfoDic=_sociallHandlerInfoDic;
- (void).cxx_destruct;
- (id)allPlatformType;
- (id)doAllPlatformType;
- (Class)sociallHandlerWithPlatformType:(long long)arg1;
- (Class)doSociallHandlerWithPlatformType:(long long)arg1;
- (long long)addSociallHandlerWithClass:(Class)arg1 withPlatformType:(long long)arg2;
- (long long)doAddSociallHandlerWithClass:(Class)arg1 withPlatformType:(long long)arg2;
- (long long)addSociallHandlerWithClass:(Class)arg1 withPlatformTypes:(id)arg2;
- (_Bool)doCheckSociallHandlerWithPlatformType:(long long)arg1;
- (_Bool)checkValidPlatformType:(long long)arg1;
- (_Bool)checkUserDefinePlatformType:(long long)arg1;
- (_Bool)checkPredefinePlatformType:(long long)arg1;
- (id)init;

@end

