# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'EmptyTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EmptyTest
#  pod 'JZTComponent', :path => '~/Documents/GitHub/JZTComponent'
#  pod 'CCTweakTool', :path => '~/Documents/GitHub/CCTweakTool'
end
