//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MyCamGPUFilter.h"

@interface AlphaColorFilter : MyCamGPUFilter
{
}

- (void)setColor2:(float)arg1 andG:(float)arg2 andB:(float)arg3 andA:(float)arg4 andTransParency:(float)arg5;
- (id)init;

@end

