//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString, SCNMaterialProperty, UIImage;

@interface MCThreeDMaterialProperty : NSObject
{
    float _intensity;
    int _mType;
    NSString *_content;
    double _frameDuration;
    long long _frameCount;
    NSString *_folderPath;
    SCNMaterialProperty *_correspondSCMMaterialProperty;
    NSArray *_images;
    UIImage *_singleIm;
    long long _playedTimes;
    double _currentFrameTime;
    long long _currentFrameIndex;
    double _beginTime;
}

@property(nonatomic) double beginTime; // @synthesize beginTime=_beginTime;
@property(nonatomic) long long currentFrameIndex; // @synthesize currentFrameIndex=_currentFrameIndex;
@property(nonatomic) double currentFrameTime; // @synthesize currentFrameTime=_currentFrameTime;
@property(nonatomic) long long playedTimes; // @synthesize playedTimes=_playedTimes;
@property(retain, nonatomic) UIImage *singleIm; // @synthesize singleIm=_singleIm;
@property(retain, nonatomic) NSArray *images; // @synthesize images=_images;
@property(nonatomic) int mType; // @synthesize mType=_mType;
@property(retain, nonatomic) SCNMaterialProperty *correspondSCMMaterialProperty; // @synthesize correspondSCMMaterialProperty=_correspondSCMMaterialProperty;
@property(retain, nonatomic) NSString *folderPath; // @synthesize folderPath=_folderPath;
@property(nonatomic) float intensity; // @synthesize intensity=_intensity;
@property(nonatomic) long long frameCount; // @synthesize frameCount=_frameCount;
@property(nonatomic) double frameDuration; // @synthesize frameDuration=_frameDuration;
@property(retain, nonatomic) NSString *content; // @synthesize content=_content;
- (void).cxx_destruct;
@property(readonly, nonatomic) UIImage *currentIm;
- (void)advanceTime;
- (_Bool)isFolder:(id)arg1;
- (void)preloadImWithFileName:(id)arg1;
- (void)preloadImsWithFolderName:(id)arg1;
- (id)initWithDictionary:(id)arg1 andFolderPath:(id)arg2;

@end

