//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MyCamGPUFilter.h"

@interface PortraitBeautyProcess : MyCamGPUFilter
{
    double _opttype;
    double _whiten;
    double _skinFilter;
    double _smoothMag;
}

@property(nonatomic) double smoothMag; // @synthesize smoothMag=_smoothMag;
@property(nonatomic) double skinFilter; // @synthesize skinFilter=_skinFilter;
@property(nonatomic) double whiten; // @synthesize whiten=_whiten;
@property(nonatomic) double opttype; // @synthesize opttype=_opttype;
- (id)init;

@end

