//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCPayControlLogic.h"

#import "FaceRecogPayHandlerDelegate-Protocol.h"
#import "WCPayGetUserExInfoCgiDelegate-Protocol.h"
#import "WCPayPayPwdViewControllerDelegate-Protocol.h"
#import "WCPayRealnameInfoViewControllerDelegate-Protocol.h"
#import "WCPayRealnameSuccessViewControllerDelegate-Protocol.h"

@class FaceRecogPayHandler, GetRealnameWordingRsp, NSString, WCPayGetUserExInfoCgi, WCPayRealnameAuthenReq, WCPayRealnameAuthenResp, WCPaySetUserExInfoCgi;

@interface WCPayRealnameVerifyLogic : WCPayControlLogic <WCPayRealnameSuccessViewControllerDelegate, FaceRecogPayHandlerDelegate, WCPayGetUserExInfoCgiDelegate, WCPayRealnameInfoViewControllerDelegate, WCPayPayPwdViewControllerDelegate>
{
    GetRealnameWordingRsp *_wording;
    WCPayGetUserExInfoCgi *_getUserExInfoCgi;
    WCPaySetUserExInfoCgi *_setUserExInfoCgi;
    WCPayRealnameAuthenResp *_authenResp;
    WCPayRealnameAuthenReq *_authenReq;
    FaceRecogPayHandler *_faceHandler;
}

@property(retain) FaceRecogPayHandler *faceHandler; // @synthesize faceHandler=_faceHandler;
@property(retain) WCPayRealnameAuthenReq *authenReq; // @synthesize authenReq=_authenReq;
@property(retain) WCPayRealnameAuthenResp *authenResp; // @synthesize authenResp=_authenResp;
@property(retain, nonatomic) WCPaySetUserExInfoCgi *setUserExInfoCgi; // @synthesize setUserExInfoCgi=_setUserExInfoCgi;
@property(retain, nonatomic) WCPayGetUserExInfoCgi *getUserExInfoCgi; // @synthesize getUserExInfoCgi=_getUserExInfoCgi;
@property(retain) GetRealnameWordingRsp *wording; // @synthesize wording=_wording;
- (void).cxx_destruct;
- (void)WCPayViewControllerDidBeRemoved:(id)arg1;
- (void)OnFinishedWCPayLogic:(id)arg1 CompleteStatus:(int)arg2;
- (void)onWCPayRealnameSuccessViewControllerDone;
- (void)OnGetBindQueryInfo:(id)arg1 Error:(id)arg2;
- (void)onErrorAlertViewDismiss:(id)arg1;
- (void)SetPayPwdNext:(id)arg1;
- (void)VerifyPayPwdNext:(id)arg1;
- (void)PayPwdRightActionBack;
- (void)PayPwdBack;
- (void)passwordInit;
- (void)OnRealnameAuthen:(id)arg1 Error:(id)arg2;
- (void)FillRealnameInfoNext:(id)arg1;
- (void)FillRealnameInfoCancel;
- (void)FillRealnameInfoLayoutV2ClickConfirm:(id)arg1;
- (_Bool)FillRealnameInfoLayoutV2;
- (id)FillRealnameInfoWording;
- (void)faceRecogPayHandlerDidCancel:(id)arg1;
- (void)faceRecogPayHandlerDidFinish:(id)arg1;
- (void)startFaceReg;
- (void)onWCPayBindCardConfirmViewControllerBack;
- (void)onWCPayBindCardConfirmViewControllerConfirm:(_Bool)arg1;
- (void)getUserExInfoCgi:(id)arg1 didFailWithError:(id)arg2;
- (void)getUserExInfoCgi:(id)arg1 didGetResponse:(id)arg2;
- (void)startLogic;
- (void)stopLogic;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

