//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UISearchController.h>

@class MMTagSearchBar;

@interface WCSearchController : UISearchController
{
    MMTagSearchBar *_wcSearchBar;
}

@property(retain, nonatomic) MMTagSearchBar *wcSearchBar; // @synthesize wcSearchBar=_wcSearchBar;
- (void).cxx_destruct;
- (void)presentViewController:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (id)searchBar;
- (void)viewDidLoad;
- (void)initCustomSearchBar;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)dealloc;
- (id)initWithSearchResultsController:(id)arg1;

@end

