//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

#import "MMConfigMgrExt-Protocol.h"
#import "MMService-Protocol.h"

@class NSString;

@interface WCStoryConfigureMgr : MMService <MMService, MMConfigMgrExt>
{
    unsigned long long _headerShowLimitCount;
    unsigned long long _entranceInTimelineOfTimeDuration;
}

@property(nonatomic) unsigned long long entranceInTimelineOfTimeDuration; // @synthesize entranceInTimelineOfTimeDuration=_entranceInTimelineOfTimeDuration;
@property(nonatomic) unsigned long long headerShowLimitCount; // @synthesize headerShowLimitCount=_headerShowLimitCount;
- (void)onMMDynamicConfigUpdated;
- (void)setupDynamicValue;
- (void)dealloc;
- (void)onServiceInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

