//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString, UIColor;

@interface CameraImageRecognizer : NSObject
{
    struct _IplImage *_iplImg;
    int _recognizeLeft;
    int _recognizeRight;
    int _recognizeTop;
    int _recognizeBottom;
    _Bool _syncModeEnabled;
    _Bool _histogramEqualizationEnabled;
    _Bool _skinColorCalssifyEnabled;
    UIColor *_faceAvgColor;
    NSArray *_histogramColorMap;
    long long _skinColorLevel;
    NSString *_skinColorDescription;
    NSArray *_skinColorTable;
}

@property(retain, nonatomic) NSArray *skinColorTable; // @synthesize skinColorTable=_skinColorTable;
@property(copy, nonatomic) NSString *skinColorDescription; // @synthesize skinColorDescription=_skinColorDescription;
@property(nonatomic) long long skinColorLevel; // @synthesize skinColorLevel=_skinColorLevel;
@property(retain, nonatomic) NSArray *histogramColorMap; // @synthesize histogramColorMap=_histogramColorMap;
@property(retain, nonatomic) UIColor *faceAvgColor; // @synthesize faceAvgColor=_faceAvgColor;
@property(nonatomic) _Bool skinColorCalssifyEnabled; // @synthesize skinColorCalssifyEnabled=_skinColorCalssifyEnabled;
@property(nonatomic) _Bool histogramEqualizationEnabled; // @synthesize histogramEqualizationEnabled=_histogramEqualizationEnabled;
@property(nonatomic) _Bool syncModeEnabled; // @synthesize syncModeEnabled=_syncModeEnabled;
- (void).cxx_destruct;
- (id)colorFromHexStr:(id)arg1;
- (void)recognizeSkinColorLevel:(id)arg1;
- (void)histogramEqualization:(struct _IplImage *)arg1;
- (void)recognizeImage:(id)arg1 withFaceFeature:(id)arg2 inFaceMode:(_Bool)arg3;
- (void)_cleanResource;
- (void)dealloc;
- (id)init;

@end

