//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MCMeshUtils : NSObject
{
}

+ (int)totalTriangleOfMeshX:(int)arg1 Y:(int)arg2;
+ (void)generateMeshVertex:(float *)arg1 fragment:(float *)arg2 xCount:(int)arg3 yCount:(int)arg4 imageRect:(struct CGRect)arg5;
+ (void)generateMeshFragment:(float *)arg1 xCount:(int)arg2 yCount:(int)arg3 imageRect:(struct CGRect)arg4;
+ (void)generateMeshVertex:(float *)arg1 xCount:(int)arg2 yCount:(int)arg3 imageRect:(struct CGRect)arg4;

@end

