//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MMITransmitKvData, MMVoidCallback, MMVoidITransmitKvDataCallback, NSString;

@protocol MMKPlatformUIRouter <NSObject>
- (void)openUrlScheme:(NSString *)arg1;
- (void)gotoExternApp:(NSString *)arg1 errcode:(int)arg2 returnKey:(NSString *)arg3;
- (void)openTinyAppImpl:(NSString *)arg1 path:(NSString *)arg2 version:(NSString *)arg3 completionCallback:(MMVoidCallback *)arg4;
- (void)openTinyApp:(NSString *)arg1 path:(NSString *)arg2 version:(NSString *)arg3;
- (void)openWebImpl:(MMITransmitKvData *)arg1 callback:(MMVoidITransmitKvDataCallback *)arg2;
- (void)openWeb:(MMITransmitKvData *)arg1;
@end

