//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CPUImageFilter.h"

@class UIImage;

@interface OilPaint : CPUImageFilter
{
    int m_blur;
    int m_smooth;
    int m_flag;
    float m_mix;
    int step;
    UIImage *reslut;
}

- (void).cxx_destruct;
- (void)setProperty:(id)arg1 value:(id)arg2;
- (id)main;
- (char *)processOneSlicePixels:(id)arg1;
- (char *)FilterProcessPixels:(id)arg1;
- (id)FilterProcess;
- (void)addWithTexture:(struct _Image *)arg1 andFlag:(_Bool)arg2;
- (id)initWithBlur:(int)arg1 andSmooth:(int)arg2 andFlag:(int)arg3;

@end

