//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "CLLocationManagerDelegate-Protocol.h"

@class CLLocation, CLLocationManager, NSMutableArray, NSString;

@interface WMCSpeedDirectionManager : NSObject <CLLocationManagerDelegate>
{
    int _currentRegion;
    int _currentSpeedLogo;
    CLLocation *_currentWMCLocation;
    double _currentHeading;
    double _currentSpeed;
    double _currentPointerAngle;
    CLLocationManager *_locationManager;
    NSMutableArray *_speedWindow;
}

+ (id)sharedManager;
+ (void)initialize;
@property(retain, nonatomic) NSMutableArray *speedWindow; // @synthesize speedWindow=_speedWindow;
@property(retain, nonatomic) CLLocationManager *locationManager; // @synthesize locationManager=_locationManager;
@property(nonatomic) int currentSpeedLogo; // @synthesize currentSpeedLogo=_currentSpeedLogo;
@property(nonatomic) double currentPointerAngle; // @synthesize currentPointerAngle=_currentPointerAngle;
@property(nonatomic) int currentRegion; // @synthesize currentRegion=_currentRegion;
@property(nonatomic) double currentSpeed; // @synthesize currentSpeed=_currentSpeed;
@property(nonatomic) double currentHeading; // @synthesize currentHeading=_currentHeading;
@property(retain, nonatomic) CLLocation *currentWMCLocation; // @synthesize currentWMCLocation=_currentWMCLocation;
- (void).cxx_destruct;
- (double)directionFrom:(struct CLLocationCoordinate2D)arg1 to:(struct CLLocationCoordinate2D)arg2;
- (int)speedLogo:(double)arg1;
- (double)pointerAngle:(double)arg1;
- (int)headingRegion:(double)arg1;
- (id)headingDescription:(double)arg1;
- (void)locationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2;
- (void)locationManager:(id)arg1 didUpdateLocations:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateToLocation:(id)arg2 fromLocation:(id)arg3;
- (void)shutdown;
- (void)startup;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

