//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface Growing : NSObject
{
}

+ (void)track:(id)arg1 withNumber:(id)arg2 andVariable:(id)arg3;
+ (void)track:(id)arg1 withVariable:(id)arg2;
+ (void)track:(id)arg1 withNumber:(id)arg2;
+ (void)track:(id)arg1;
+ (void)setPeopleVariableWithKey:(id)arg1 andNumberValue:(id)arg2;
+ (void)setPeopleVariableWithKey:(id)arg1 andStringValue:(id)arg2;
+ (void)setPeopleVariable:(id)arg1;
+ (void)setVisitor:(id)arg1;
+ (void)setEvarWithKey:(id)arg1 andNumberValue:(id)arg2;
+ (void)setEvarWithKey:(id)arg1 andStringValue:(id)arg2;
+ (void)setEvar:(id)arg1;
+ (void)clearUserId;
+ (void)setUserId:(id)arg1;
+ (id)getSessionId;
+ (id)getVisitUserId;
+ (id)getDeviceId;
+ (void)setDeviceIDModeToCustomBlock:(CDUnknownBlockType)arg1;
+ (void)setZone:(id)arg1;
+ (void)setReportHost:(id)arg1;
+ (void)registerRealtimeReportHandler:(CDUnknownBlockType)arg1;
+ (void)registerDeeplinkHandler:(CDUnknownBlockType)arg1;
+ (void)setWsHost:(id)arg1;
+ (void)setGtaHost:(id)arg1;
+ (void)setAssetsHost:(id)arg1;
+ (void)setDataHost:(id)arg1;
+ (void)setTrackerHost:(id)arg1;
+ (unsigned long long)getDailyDataLimit;
+ (void)setDailyDataLimit:(unsigned long long)arg1;
+ (double)getFlushInterval;
+ (void)setFlushInterval:(double)arg1;
+ (void)enableDataCollect;
+ (void)disableDataCollect;
+ (void)disable;
+ (void)resetSessionIDAndSendVstByCS1OldValue:(id)arg1 cs1NewValue:(id)arg2;
+ (void)setCS1Value:(id)arg1;
+ (void)setEncryptStringBlock:(CDUnknownBlockType)arg1;
+ (_Bool)getDisablePushTrack;
+ (void)disablePushTrack:(_Bool)arg1;
+ (void)setEnableDiagnose:(_Bool)arg1;
+ (_Bool)getEnableLog;
+ (void)setEnableLog:(_Bool)arg1;
+ (void)startWithAccountId:(id)arg1 withSampling:(double)arg2;
+ (void)startWithAccountId:(id)arg1;
+ (_Bool)handleUrl:(id)arg1;
+ (long long)getAspectMode;
+ (void)setAspectMode:(long long)arg1;
+ (id)sdkVersion;
+ (void)sendPage:(id)arg1;
+ (void)setAppVariableWithKey:(id)arg1 andNumberValue:(id)arg2;
+ (void)setAppVariableWithKey:(id)arg1 andStringValue:(id)arg2;
+ (void)setAppVariable:(id)arg1;
+ (void)setPageVariableWithKey:(id)arg1 andNumberValue:(id)arg2 toViewController:(id)arg3;
+ (void)setPageVariableWithKey:(id)arg1 andStringValue:(id)arg2 toViewController:(id)arg3;
+ (void)setPageVariable:(id)arg1 toViewController:(id)arg2;
+ (void)setImp:(_Bool)arg1;
+ (_Bool)isTrackingWebView;
+ (void)enableHybridHashTag:(_Bool)arg1;
+ (void)enableAllWebViews:(_Bool)arg1;
+ (void)setHybridJSSDKUrlPrefix:(id)arg1;
+ (id)autoTrackKitVersion;

@end

