//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <OfferWallBase/JCORENetChannelProtocol-Protocol.h>

@class NSData;

@protocol JCORETcpProtocol <JCORENetChannelProtocol>
@property(nonatomic) unsigned char protocolType;
@property(nonatomic) unsigned char version;

@optional
@property(nonatomic) int autoRetryCount;
@property(nonatomic) unsigned char controlFlag;
@property(nonatomic) unsigned long long seed;
@property(nonatomic) unsigned long long uid;
@property(nonatomic) unsigned short rid;
@property(nonatomic) unsigned char algorithm;
- (NSData *)bodyData;
- (NSData *)headData;
@end

