//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MOBFDevice : NSObject
{
}

+ (int)wifiLevel;
+ (id)cpuType;
+ (id)networkInfo;
+ (struct CGSize)nativeScreenSize;
+ (id)getSysInfoByName:(char *)arg1;
+ (id)currentNetworkInfo;
+ (long long)diskSpace;
+ (double)physicalMemory;
+ (id)ipAddress:(unsigned long long)arg1;
+ (id)currentLanguage;
+ (id)idfv;
+ (id)bssid;
+ (id)ssid;
+ (id)duid;
+ (_Bool)isPad;
+ (id)runningProcesses;
+ (_Bool)hasJailBroken;
+ (long long)versionCompare:(id)arg1;
+ (id)mobileNetworkCode;
+ (id)mobileCountryCode;
+ (id)carrierName;
+ (id)carrier;
+ (unsigned long long)currentNetworkType;
+ (id)deviceModel;
+ (id)macAddress;
+ (void)load;

@end

