//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <OfferWallBase/NSNetServiceBrowserDelegate-Protocol.h>
#import <OfferWallBase/NSNetServiceDelegate-Protocol.h>
#import <OfferWallBase/OWBonjourServiceFinderDelegate-Protocol.h>

@class NSMutableArray, NSMutableDictionary, NSNetServiceBrowser, NSString;

@interface OWBonjourManager : NSObject <NSNetServiceBrowserDelegate, NSNetServiceDelegate, OWBonjourServiceFinderDelegate>
{
    NSNetServiceBrowser *_netServiceTypeBrowser;
    NSMutableArray *_serviceTypes;
    NSMutableDictionary *_services;
    NSMutableDictionary *_serviceInfo;
    NSMutableArray *_finders;
}

+ (id)defaultManager;
@property(retain, nonatomic) NSMutableArray *finders; // @synthesize finders=_finders;
@property(retain, nonatomic) NSMutableDictionary *serviceInfo; // @synthesize serviceInfo=_serviceInfo;
@property(retain, nonatomic) NSMutableDictionary *services; // @synthesize services=_services;
@property(retain, nonatomic) NSMutableArray *serviceTypes; // @synthesize serviceTypes=_serviceTypes;
@property(retain, nonatomic) NSNetServiceBrowser *netServiceTypeBrowser; // @synthesize netServiceTypeBrowser=_netServiceTypeBrowser;
- (void).cxx_destruct;
- (void)serviceFinderDidStop:(id)arg1;
- (void)serviceFinder:(id)arg1 didNotFind:(id)arg2;
- (void)serviceFinder:(id)arg1 didFindService:(id)arg2;
- (void)netServiceDidStop:(id)arg1;
- (void)netService:(id)arg1 didNotResolve:(id)arg2;
- (void)netServiceDidResolveAddress:(id)arg1;
- (void)netServiceBrowser:(id)arg1 didFindService:(id)arg2 moreComing:(_Bool)arg3;
- (void)netServiceBrowser:(id)arg1 didNotSearch:(id)arg2;
- (void)netServiceBrowserDidStopSearch:(id)arg1;
- (void)netServiceBrowserWillSearch:(id)arg1;
- (void)addServiceInfo:(id)arg1 ofService:(id)arg2;
- (void)resolveAllServices;
- (void)searchAllServiceTypes;
- (void)searchAllServices;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

