//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSTimer;

@interface OWMaintenanceManager : NSObject
{
    _Bool _isTestDevice;
    NSArray *_planArray;
    NSTimer *_timer;
}

+ (id)defaultManager;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(nonatomic) _Bool isTestDevice; // @synthesize isTestDevice=_isTestDevice;
@property(copy, nonatomic) NSArray *planArray; // @synthesize planArray=_planArray;
- (void).cxx_destruct;
- (void)maintenanceAlert:(id)arg1 message:(id)arg2;
- (void)noticeAlert:(id)arg1 message:(id)arg2;
- (id)getUrl;
- (_Bool)runtimeCheck;
- (void)startCheck;
- (void)pull;
- (void)update;
- (void)start;

@end

