//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSString;

@interface OWSocketMessage : NSObject
{
    unsigned char _cmd1;
    unsigned char _cmd2;
    int _length;
    NSData *_body;
    long long _magicNumber;
    long long _timestamp;
    NSData *_sign;
    NSString *_deviceUuid;
    NSString *_deviceUuidSecret;
    NSData *_payload;
}

@property(retain, nonatomic) NSData *payload; // @synthesize payload=_payload;
@property(copy, nonatomic) NSString *deviceUuidSecret; // @synthesize deviceUuidSecret=_deviceUuidSecret;
@property(copy, nonatomic) NSString *deviceUuid; // @synthesize deviceUuid=_deviceUuid;
@property(retain, nonatomic) NSData *sign; // @synthesize sign=_sign;
@property(nonatomic) long long timestamp; // @synthesize timestamp=_timestamp;
@property(nonatomic) long long magicNumber; // @synthesize magicNumber=_magicNumber;
@property(nonatomic) int length; // @synthesize length=_length;
@property(retain, nonatomic) NSData *body; // @synthesize body=_body;
@property(nonatomic) unsigned char cmd2; // @synthesize cmd2=_cmd2;
@property(nonatomic) unsigned char cmd1; // @synthesize cmd1=_cmd1;
- (void).cxx_destruct;

@end

