//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSString;
@protocol PhonePingDelegate;

@interface PhonePing : NSObject
{
    int socket_client;
    struct sockaddr_in remote_addr;
    _Bool _isPing;
    _Bool _isStopPingThread;
    int _pingPacketCount;
    id <PhonePingDelegate> _delegate;
    NSString *_host;
    NSDate *_sendDate;
}

@property(nonatomic) int pingPacketCount; // @synthesize pingPacketCount=_pingPacketCount;
@property(retain, nonatomic) NSDate *sendDate; // @synthesize sendDate=_sendDate;
@property(retain, nonatomic) NSString *host; // @synthesize host=_host;
@property(nonatomic) _Bool isStopPingThread; // @synthesize isStopPingThread=_isStopPingThread;
@property(nonatomic) _Bool isPing; // @synthesize isPing=_isPing;
@property(retain, nonatomic) id <PhonePingDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)reporterPingResWithSorceIp:(id)arg1 ttl:(int)arg2 timeMillSecond:(float)arg3 seq:(int)arg4 icmpId:(int)arg5 dataSize:(int)arg6 pingStatus:(long long)arg7;
- (_Bool)receiverRemoteIpPingRes;
- (void)sendAndrecevPingPacket;
- (void)startPingHosts:(id)arg1 packetCount:(int)arg2;
- (id)convertDomainToIp:(id)arg1;
- (_Bool)settingUHostSocketAddressWithHost:(id)arg1;
- (void)stopPing;
- (id)init;

@end

