//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary;

@interface PNetInfoTool : NSObject
{
    NSDictionary *_ipInfoDict;
    NSDictionary *_wifiDict;
}

+ (id)getIPAddresses;
+ (id)shareInstance;
@property(copy, nonatomic) NSDictionary *wifiDict; // @synthesize wifiDict=_wifiDict;
@property(copy, nonatomic) NSDictionary *ipInfoDict; // @synthesize ipInfoDict=_ipInfoDict;
- (void).cxx_destruct;
- (id)pGetNetworkType;
- (id)pGetCellIpv4;
- (id)pGetWifiIpv6;
- (id)pGetSubNetMask;
- (id)pGetWifiIpv4;
- (id)pGetBSSID;
- (id)pGetSSID;
- (void)refreshNetInfo;

@end

