//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, NSString;

@interface XGConfig : NSObject
{
    _Bool _connectToDebugServer;
    _Bool _needRegister;
    _Bool _registerFromMSDK;
    _Bool _traceOn;
    unsigned int _appId;
    NSString *_keyForKeyChain;
    NSString *_appkey;
    NSString *_account;
    NSString *_tokenTag;
    NSArray *_deviceTags;
    NSString *_deviceToken;
    NSString *_connectHost;
    unsigned long long _connectPort;
    NSString *_idfa;
    NSMutableArray *_tokenTags;
    NSString *_currentTag;
}

+ (id)getInstance;
@property(nonatomic) _Bool traceOn; // @synthesize traceOn=_traceOn;
@property(copy, nonatomic) NSString *currentTag; // @synthesize currentTag=_currentTag;
@property(retain, nonatomic) NSMutableArray *tokenTags; // @synthesize tokenTags=_tokenTags;
@property(nonatomic) _Bool registerFromMSDK; // @synthesize registerFromMSDK=_registerFromMSDK;
@property(retain, nonatomic) NSString *idfa; // @synthesize idfa=_idfa;
@property(nonatomic) unsigned long long connectPort; // @synthesize connectPort=_connectPort;
@property(retain, nonatomic) NSString *connectHost; // @synthesize connectHost=_connectHost;
@property _Bool needRegister; // @synthesize needRegister=_needRegister;
@property(retain, nonatomic) NSString *deviceToken; // @synthesize deviceToken=_deviceToken;
@property(readonly, nonatomic) NSArray *deviceTags; // @synthesize deviceTags=_deviceTags;
@property(retain, nonatomic) NSString *tokenTag; // @synthesize tokenTag=_tokenTag;
@property(retain, nonatomic) NSString *account; // @synthesize account=_account;
@property unsigned int appId; // @synthesize appId=_appId;
@property(retain, nonatomic) NSString *appkey; // @synthesize appkey=_appkey;
@property(nonatomic) _Bool connectToDebugServer; // @synthesize connectToDebugServer=_connectToDebugServer;
@property(retain, nonatomic) NSString *keyForKeyChain; // @synthesize keyForKeyChain=_keyForKeyChain;
- (void).cxx_destruct;
- (unsigned short)getReportPort;
- (id)getReportURL;
@property(getter=isDebugEnable) _Bool debugEnable;
- (_Bool)isStarted;
- (id)init;

@end

