//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <OfferWallBase/XGJceObject.h>

@interface XGJceObjectV2 : XGJceObject
{
}

+ (id)jceType;
- (void)__unpack:(id)arg1;
- (void)__pack:(id)arg1;
- (id)jcePropsDescription;
- (id)jceRefObject;
- (id)jceType;

@end

