//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSURL;

@interface _IMYWebImageURLFormatter : NSObject
{
    _Bool _isGIF;
    NSURL *_url;
    long long _quality;
    long long _type;
    unsigned long long _mode;
    struct CGSize _size;
}

+ (_Bool)containHostWithURL:(id)arg1 hosts:(id)arg2;
+ (id)checkImageExtensionWithPath:(id)arg1;
+ (id)imageURLFormatterWithURL:(id)arg1;
@property(nonatomic) _Bool isGIF; // @synthesize isGIF=_isGIF;
@property(nonatomic) unsigned long long mode; // @synthesize mode=_mode;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(nonatomic) long long quality; // @synthesize quality=_quality;
@property(nonatomic) struct CGSize size; // @synthesize size=_size;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
- (void).cxx_destruct;
- (id)denyImageURL;
- (id)encodeImageURL;

@end

