//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _PSDHTTPHook : NSObject
{
}

+ (_Bool)shouldIgnoreRequest:(id)arg1;
+ (void)setIgnoreBlock:(CDUnknownBlockType)arg1;
+ (void)hookNSURLSession;
+ (void)injectHook;
+ (void)load;
+ (void)hookNSURLSessionTask;
+ (void)hookNSURLConnection;
+ (void)swizzleAFResumeForClass:(Class)arg1;
+ (void)swizzleResumeForClass:(Class)arg1;
+ (void)AF_ResumeNotification:(id)arg1;
- (void)_psd_resume;

@end

