//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AlibcTradeShowParams, AlibcTradeTaokeParams, NSDictionary;

@interface AlibcContextData : NSObject
{
    AlibcTradeShowParams *_showParams;
    NSDictionary *_param;
    AlibcTradeTaokeParams *_taokeParam;
    CDUnknownBlockType _onTradeSuccess;
    CDUnknownBlockType _onTradeFailure;
}

@property(copy, nonatomic) CDUnknownBlockType onTradeFailure; // @synthesize onTradeFailure=_onTradeFailure;
@property(copy, nonatomic) CDUnknownBlockType onTradeSuccess; // @synthesize onTradeSuccess=_onTradeSuccess;
@property(retain, nonatomic) AlibcTradeTaokeParams *taokeParam; // @synthesize taokeParam=_taokeParam;
@property(retain, nonatomic) NSDictionary *param; // @synthesize param=_param;
@property(retain, nonatomic) AlibcTradeShowParams *showParams; // @synthesize showParams=_showParams;
- (void).cxx_destruct;
- (_Bool)isForceH5;

@end

