//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CalendarLogic, NSArray, NSDate;

@interface CalendarMonth : UIView
{
    long long numberOfDaysInWeek;
    long long selectedButton;
    NSDate *selectedDate;
    UIView *_contentView;
    CalendarLogic *_calendarLogic;
    NSArray *_datesIndex;
    NSArray *_buttonsIndex;
}

+ (_Bool)isFirstMonday;
+ (void)setFirstMonday:(_Bool)arg1;
+ (float)getDayViewHeightOffset;
+ (float)getDayViewWidthOffset;
+ (float)getDayViewHeight;
+ (float)getDayViewWidth;
+ (void)initialize;
@property(retain) NSArray *buttonsIndex; // @synthesize buttonsIndex=_buttonsIndex;
@property(retain) NSArray *datesIndex; // @synthesize datesIndex=_datesIndex;
@property(retain) CalendarLogic *calendarLogic; // @synthesize calendarLogic=_calendarLogic;
@property(nonatomic) __weak UIView *contentView; // @synthesize contentView=_contentView;
@property(retain) NSDate *selectedDate; // @synthesize selectedDate;
@property(nonatomic) long long selectedButton; // @synthesize selectedButton;
@property(nonatomic) long long numberOfDaysInWeek; // @synthesize numberOfDaysInWeek;
- (void).cxx_destruct;
- (void)selectButtonForDate:(id)arg1;
- (id)buttonWithDate:(id)arg1;
- (id)selectedButtonView;
- (void)reloadShow;
- (void)resetCalendarLogic:(id)arg1;
- (int)monthRowCount;
- (void)reloadCalendarLogic;
- (void)longpressedGesture:(id)arg1;
- (void)dayButtonDoublePressed:(id)arg1;
- (void)dayButtonPressed:(id)arg1;
- (void)doubleTapGesture:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 logic:(id)arg2;
- (void)dealloc;

@end

