//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IMYAccountBaseVC.h"

@class IMYAccount, IMYSimpleTableView;

@interface IMYAccountPhoneChangeVC : IMYAccountBaseVC
{
    IMYAccount *_account;
    CDUnknownBlockType _completion;
    IMYSimpleTableView *_tableView;
}

@property(retain, nonatomic) IMYSimpleTableView *tableView; // @synthesize tableView=_tableView;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(retain, nonatomic) IMYAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (double)getHeaderHeight:(id)arg1;
- (void)initTableViewData;
- (void)createUI;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)init;

@end

