//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IMYCellModel.h"

#import "IMYAnalyzeCellModelProtocol-Protocol.h"

@class IMYAnalyzeBabySymptomRecord, NSArray, NSMutableDictionary, NSString;

@interface IMYAnalyzeBabySymptomsCellModel : IMYCellModel <IMYAnalyzeCellModelProtocol>
{
    NSMutableDictionary *_orignalData;
    unsigned long long _sortKey;
    NSString *_detailText;
    IMYAnalyzeBabySymptomRecord *_record;
    NSArray *_symptoms;
}

@property(retain, nonatomic) NSArray *symptoms; // @synthesize symptoms=_symptoms;
@property(retain, nonatomic) IMYAnalyzeBabySymptomRecord *record; // @synthesize record=_record;
@property(copy, nonatomic) NSString *detailText; // @synthesize detailText=_detailText;
@property(nonatomic) unsigned long long sortKey; // @synthesize sortKey=_sortKey;
@property(nonatomic) __weak NSMutableDictionary *orignalData; // @synthesize orignalData=_orignalData;
- (void).cxx_destruct;
- (void)requestDataWithCallback:(CDUnknownBlockType)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

