//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIImageView, UILabel, UITextField;

@interface IMYAccountCell : UITableViewCell
{
    UILabel *_l_title;
    UITextField *_tf_value;
    UITextField *_tf_value1;
    UIImageView *_iv_arrow;
}

@property(nonatomic) __weak UIImageView *iv_arrow; // @synthesize iv_arrow=_iv_arrow;
@property(nonatomic) __weak UITextField *tf_value1; // @synthesize tf_value1=_tf_value1;
@property(nonatomic) __weak UITextField *tf_value; // @synthesize tf_value=_tf_value;
@property(nonatomic) __weak UILabel *l_title; // @synthesize l_title=_l_title;
- (void).cxx_destruct;
- (void)setAccountCell:(_Bool)arg1 indexPath:(id)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

