//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IMYPublicBaseViewController.h"

#import "IMYAssetListViewControllerDelegate-Protocol.h"

@class IMYAssetListViewController, IMYAssetsGroupListViewController, IMYAssetsGroupModel, IMYCaptionView, NSMutableArray, NSString, UIImageView, UILabel, UIView;
@protocol IMYAssetPickerControllerDelegate;

@interface IMYAssetPickerController : IMYPublicBaseViewController <IMYAssetListViewControllerDelegate>
{
    _Bool _allowsMultipleSelection;
    _Bool _isAnimating;
    id <IMYAssetPickerControllerDelegate> _delegate;
    NSMutableArray *_selectedAssetArray;
    NSString *_trackEventPrefix;
    unsigned long long _styleType;
    unsigned long long _minimumNumberOfSelection;
    unsigned long long _maximumNumberOfSelection;
    IMYAssetListViewController *_assetListChildVC;
    IMYAssetsGroupListViewController *_assetsGroupListChildVC;
    UIView *_assetsGroupListContainerView;
    UILabel *_navigationBarTitleLabel;
    IMYCaptionView *_captionView;
    UIImageView *_arrowImageView;
    UILabel *_titleLabel;
    IMYAssetsGroupModel *_currentAssetsGroup;
    NSMutableArray *_assetsGroupArray;
}

@property(nonatomic) _Bool isAnimating; // @synthesize isAnimating=_isAnimating;
@property(retain, nonatomic) NSMutableArray *assetsGroupArray; // @synthesize assetsGroupArray=_assetsGroupArray;
@property(retain, nonatomic) IMYAssetsGroupModel *currentAssetsGroup; // @synthesize currentAssetsGroup=_currentAssetsGroup;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *arrowImageView; // @synthesize arrowImageView=_arrowImageView;
@property(retain, nonatomic) IMYCaptionView *captionView; // @synthesize captionView=_captionView;
@property(retain, nonatomic) UILabel *navigationBarTitleLabel; // @synthesize navigationBarTitleLabel=_navigationBarTitleLabel;
@property(retain, nonatomic) UIView *assetsGroupListContainerView; // @synthesize assetsGroupListContainerView=_assetsGroupListContainerView;
@property(retain, nonatomic) IMYAssetsGroupListViewController *assetsGroupListChildVC; // @synthesize assetsGroupListChildVC=_assetsGroupListChildVC;
@property(retain, nonatomic) IMYAssetListViewController *assetListChildVC; // @synthesize assetListChildVC=_assetListChildVC;
@property(nonatomic) unsigned long long maximumNumberOfSelection; // @synthesize maximumNumberOfSelection=_maximumNumberOfSelection;
@property(nonatomic) unsigned long long minimumNumberOfSelection; // @synthesize minimumNumberOfSelection=_minimumNumberOfSelection;
@property(nonatomic) _Bool allowsMultipleSelection; // @synthesize allowsMultipleSelection=_allowsMultipleSelection;
@property(nonatomic) unsigned long long styleType; // @synthesize styleType=_styleType;
@property(copy, nonatomic) NSString *trackEventPrefix; // @synthesize trackEventPrefix=_trackEventPrefix;
@property(retain, nonatomic) NSMutableArray *selectedAssetArray; // @synthesize selectedAssetArray=_selectedAssetArray;
@property(nonatomic) __weak id <IMYAssetPickerControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)trackEventWithName:(id)arg1 attribute:(id)arg2;
- (void)assetListViewControllerWillCancelling:(id)arg1;
- (void)assetListViewControllerDidFinishSelection:(id)arg1;
- (void)assetListViewController:(id)arg1 didDeselectAsset:(id)arg2;
- (void)assetListViewController:(id)arg1 didSelectAsset:(id)arg2;
- (void)navigationBarTitleTapAction:(id)arg1;
- (void)imy_topLeftButtonTouchupInside;
- (void)passSelectedAssetsToDelegate;
- (void)cancel:(id)arg1;
- (void)unfoldOrFoldAssetsGroupChildVC;
- (void)updateNavigationBarTitle:(id)arg1;
- (void)setupNavTitleView;
- (void)updateEmptyView;
- (void)setupUI;
- (void)fetchAssetsGroup;
- (void)setupData;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

