//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "YYJSONHelperProtocol-Protocol.h"

@class NSString;

@interface IMYATAvatarModel : NSObject <YYJSONHelperProtocol>
{
    NSString *largeDiskUrl;
    NSString *mediumDiskUrl;
    NSString *smallDiskUrl;
    NSString *_large;
    NSString *_medium;
    NSString *_small;
}

@property(copy, nonatomic) NSString *small; // @synthesize small=_small;
@property(copy, nonatomic) NSString *medium; // @synthesize medium=_medium;
@property(copy, nonatomic) NSString *large; // @synthesize large=_large;
- (void).cxx_destruct;
- (id)smallDiskUrl;
- (id)mediumDiskUrl;
- (id)largeDiskUrl;

@end

