//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class IMYBuRuCommonHeadView, IMYRecordRoundButton;
@protocol IMYBuRuBottleFeedHeadViewDelegate;

@interface IMYBuRuBottleFeedHeadView : UIView
{
    id <IMYBuRuBottleFeedHeadViewDelegate> _delegate;
    IMYBuRuCommonHeadView *_bottleView;
    IMYRecordRoundButton *_saveButton;
}

@property(nonatomic) __weak IMYRecordRoundButton *saveButton; // @synthesize saveButton=_saveButton;
@property(retain, nonatomic) IMYBuRuCommonHeadView *bottleView; // @synthesize bottleView=_bottleView;
@property(nonatomic) __weak id <IMYBuRuBottleFeedHeadViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)saveButtonPressed:(id)arg1;
- (void)createSaveButton;
- (void)setUpUI;
- (void)awakeFromNib;

@end

