//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IMYCalendarViewController_v2, IMYShowMessageQueue, LKCalendarButton, NSArray, NSDate;

@interface IMYCalendarHelper_v2 : NSObject
{
    _Bool _pushToMoodDiary;
    _Bool _isUpdate;
    IMYShowMessageQueue *_showMessageQueue;
    IMYCalendarViewController_v2 *_CCController;
    LKCalendarButton *_currentButton;
    NSDate *_selectedDate;
    NSDate *_showDate;
    NSArray *_serverDayActivities;
}

+ (long long)daysToShowPregnancyCell;
+ (id)sharedHelper;
@property(retain, nonatomic) NSArray *serverDayActivities; // @synthesize serverDayActivities=_serverDayActivities;
@property _Bool isUpdate; // @synthesize isUpdate=_isUpdate;
@property _Bool pushToMoodDiary; // @synthesize pushToMoodDiary=_pushToMoodDiary;
@property(retain, nonatomic) NSDate *showDate; // @synthesize showDate=_showDate;
@property(retain, nonatomic) NSDate *selectedDate; // @synthesize selectedDate=_selectedDate;
@property(nonatomic) __weak LKCalendarButton *currentButton; // @synthesize currentButton=_currentButton;
@property(nonatomic) __weak IMYCalendarViewController_v2 *CCController; // @synthesize CCController=_CCController;
@property(retain, nonatomic) IMYShowMessageQueue *showMessageQueue; // @synthesize showMessageQueue=_showMessageQueue;
- (void).cxx_destruct;
- (id)dayMessage:(id)arg1;
- (void)movetoselect;
- (_Bool)isHideToastBar;
- (void)setHideToastBar:(_Bool)arg1;
- (void)pushMessage:(id)arg1 delay:(double)arg2 tag:(int)arg3 level:(int)arg4;
- (void)pushMessageModelWithTag:(unsigned long long)arg1 date:(id)arg2;
- (id)messageModelWithTag:(unsigned long long)arg1 date:(id)arg2;
- (void)requestServerDayActivities;
- (id)init;

@end

