//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "IMYIAdvertiserViewBuilder-Protocol.h"

@class IMYAdvertiserInfo, NSString, UITableViewCell, UIView;
@protocol IMYAdvertiserViewEventDelegate, IMYIAdvertiserModel;

@interface IMYCommonAdViewBuilder : NSObject <IMYIAdvertiserViewBuilder>
{
    _Bool _isValid;
    IMYAdvertiserInfo *_adInfo;
    id <IMYIAdvertiserModel> _currentModel;
    CDUnknownBlockType _loadComplatedBlock;
    id <IMYAdvertiserViewEventDelegate> _eventDelegate;
    UIView *_view;
    UITableViewCell *_tableViewCell;
    double _adViewHeight;
}

@property(nonatomic) double adViewHeight; // @synthesize adViewHeight=_adViewHeight;
@property(retain, nonatomic) UITableViewCell *tableViewCell; // @synthesize tableViewCell=_tableViewCell;
@property(retain, nonatomic) UIView *view; // @synthesize view=_view;
@property(nonatomic) __weak id <IMYAdvertiserViewEventDelegate> eventDelegate; // @synthesize eventDelegate=_eventDelegate;
@property(copy, nonatomic) CDUnknownBlockType loadComplatedBlock; // @synthesize loadComplatedBlock=_loadComplatedBlock;
@property(nonatomic) _Bool isValid; // @synthesize isValid=_isValid;
@property(readonly, nonatomic) id <IMYIAdvertiserModel> currentModel; // @synthesize currentModel=_currentModel;
@property(readonly, nonatomic) IMYAdvertiserInfo *adInfo; // @synthesize adInfo=_adInfo;
- (void).cxx_destruct;
- (void)playVideoWithModel:(id)arg1 sender:(id)arg2 userInfo:(id)arg3;
- (void)statisticExternalAdvertisement:(id)arg1 action:(long long)arg2;
- (void)postViewDidLoadedEvent:(id)arg1;
- (void)otherActionModel:(id)arg1 action:(long long)arg2 sender:(id)arg3 userInfo:(id)arg4;
- (void)loadedWithModel:(id)arg1 sender:(id)arg2 userInfo:(id)arg3;
- (void)dismissWithModel:(id)arg1 sender:(id)arg2 userInfo:(id)arg3;
- (void)closeWithModel:(id)arg1 sender:(id)arg2 userInfo:(id)arg3;
- (void)clickWithModel:(id)arg1 sender:(id)arg2 userInfo:(id)arg3;
- (void)displayWithModel:(id)arg1 sender:(id)arg2 userInfo:(id)arg3;
- (id)exitedAdView;
- (double)getHeight;
- (id)createTableViewCell;
- (id)getTableViewCell;
- (id)getView;
- (_Bool)isContainADView:(id)arg1;
- (void)setCurrentModel:(id)arg1;
- (id)initWithADInfo:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

