//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IMYPublicBaseViewController.h"

#import "IMYGridViewControllerDataSource-Protocol.h"
#import "IMYGridViewControllerDataTarget-Protocol.h"

@class IMYAlbum, IMYButton, IMYCaptionView, IMYGridViewController, NSMutableDictionary, NSString;

@interface IMYDaduPhotoVC : IMYPublicBaseViewController <IMYGridViewControllerDataSource, IMYGridViewControllerDataTarget>
{
    IMYAlbum *_album;
    IMYButton *_complectionBtn;
    IMYGridViewController *_gridController;
    NSMutableDictionary *_targetAssetsDictionary;
    IMYCaptionView *_captionView;
    id _pickUIDelegate;
    NSMutableDictionary *_weekDatesDict;
}

@property(retain, nonatomic) NSMutableDictionary *weekDatesDict; // @synthesize weekDatesDict=_weekDatesDict;
@property(nonatomic) __weak id pickUIDelegate; // @synthesize pickUIDelegate=_pickUIDelegate;
@property(retain, nonatomic) IMYCaptionView *captionView; // @synthesize captionView=_captionView;
@property(retain, nonatomic) NSMutableDictionary *targetAssetsDictionary; // @synthesize targetAssetsDictionary=_targetAssetsDictionary;
@property(retain, nonatomic) IMYGridViewController *gridController; // @synthesize gridController=_gridController;
@property(nonatomic) __weak IMYButton *complectionBtn; // @synthesize complectionBtn=_complectionBtn;
@property(retain, nonatomic) IMYAlbum *album; // @synthesize album=_album;
- (void).cxx_destruct;
- (id)selectedAssets;
- (long long)assetsCount;
- (id)sortAssets:(id)arg1;
- (_Bool)containsAsset:(id)arg1;
- (void)removeAllAsset;
- (void)removeAsset:(id)arg1;
- (_Bool)addAsset:(id)arg1;
- (long long)numberOfItemInRowInController:(id)arg1;
- (void)updateWithAlbum:(id)arg1;
- (id)attributedStringWithString:(id)arg1 range:(struct _NSRange)arg2 defaultColor:(id)arg3 color:(id)arg4;
- (void)setupBottomView;
- (void)setupGridVC:(id)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (void)viewWillAppear:(_Bool)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

