//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSMutableArray, NSString, UIColor, UITableView;
@protocol JMDropMenuDelegate;

@interface IMYEBDetailDropView : UIView <UITableViewDelegate, UITableViewDataSource>
{
    UIColor *_titleColor;
    UIColor *_lineColor;
    double _arrowOffset;
    long long _LayoutType;
    UIColor *_arrowColor;
    NSString *_arrowColor16;
    id <JMDropMenuDelegate> _delegate;
    UIView *_cover;
    UITableView *_tableView;
    NSMutableArray *_titleImageArrM;
    double _rowHeight;
    NSMutableArray *_RGBStrValueArr;
    long long _type;
}

+ (id)showDropMenuFrame:(struct CGRect)arg1 ArrowOffset:(double)arg2 TitleArr:(id)arg3 ImageArr:(id)arg4 Type:(long long)arg5 LayoutType:(long long)arg6 RowHeight:(double)arg7 Delegate:(id)arg8;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(retain, nonatomic) NSMutableArray *RGBStrValueArr; // @synthesize RGBStrValueArr=_RGBStrValueArr;
@property(nonatomic) double rowHeight; // @synthesize rowHeight=_rowHeight;
@property(retain, nonatomic) NSMutableArray *titleImageArrM; // @synthesize titleImageArrM=_titleImageArrM;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UIView *cover; // @synthesize cover=_cover;
@property(nonatomic) __weak id <JMDropMenuDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSString *arrowColor16; // @synthesize arrowColor16=_arrowColor16;
@property(retain, nonatomic) UIColor *arrowColor; // @synthesize arrowColor=_arrowColor;
@property(nonatomic) long long LayoutType; // @synthesize LayoutType=_LayoutType;
@property(nonatomic) double arrowOffset; // @synthesize arrowOffset=_arrowOffset;
@property(retain, nonatomic) UIColor *lineColor; // @synthesize lineColor=_lineColor;
@property(retain, nonatomic) UIColor *titleColor; // @synthesize titleColor=_titleColor;
- (void).cxx_destruct;
- (id)hexStringToColor:(id)arg1;
- (id)changeUIColorToRGB:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)removeDropMenu;
- (void)tapCoverClick;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)initWithFrame:(struct CGRect)arg1 ArrowOffset:(double)arg2 TitleArr:(id)arg3 ImageArr:(id)arg4 Type:(long long)arg5 LayoutType:(long long)arg6 RowHeight:(double)arg7 Delegate:(id)arg8;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

