//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface IMYEBItemUtils : NSObject
{
    id _lastItemModel;
    NSString *_lastItemID;
    NSString *_lastGotoNumIID;
    NSString *_lastGotoOpenIID;
    NSString *_lastRequestURLString;
}

+ (id)sharedInstance;
@property(copy, nonatomic) NSString *lastRequestURLString; // @synthesize lastRequestURLString=_lastRequestURLString;
@property(copy, nonatomic) NSString *lastGotoOpenIID; // @synthesize lastGotoOpenIID=_lastGotoOpenIID;
@property(copy, nonatomic) NSString *lastGotoNumIID; // @synthesize lastGotoNumIID=_lastGotoNumIID;
@property(copy, nonatomic) NSString *lastItemID; // @synthesize lastItemID=_lastItemID;
@property(retain, nonatomic) id lastItemModel; // @synthesize lastItemModel=_lastItemModel;
- (void).cxx_destruct;
- (void)clearItemInfo;
- (_Bool)isNewUserItem;

@end

