//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IMYEBBaseViewModel.h"

@class IMYEBHomeListModel;

@interface IMYEBHomeListUpdateVM : IMYEBBaseViewModel
{
    _Bool _isRefresh;
    IMYEBHomeListModel *_model;
}

+ (double)getExpireTimestmap;
+ (void)setExpireTimestmap:(double)arg1;
+ (void)setIsLastPage:(_Bool)arg1;
+ (_Bool)isLastPage;
+ (long long)getCurrentPage;
+ (void)setCurrentPage:(long long)arg1;
@property(nonatomic) _Bool isRefresh; // @synthesize isRefresh=_isRefresh;
@property(retain, nonatomic) IMYEBHomeListModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)requestWithPage;
- (void)requestNextPage;
- (void)requestData;
- (void)refreshData;
- (void)packUp;
- (id)ebCacheKey;

@end

