//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UIImageView, UILabel;

@interface IMYEBToLoginView : UIView
{
    UIImageView *_tipImageView;
    UILabel *_tipLabel;
    UIButton *_toLoginButton;
}

@property(retain, nonatomic) UIButton *toLoginButton; // @synthesize toLoginButton=_toLoginButton;
@property(retain, nonatomic) UILabel *tipLabel; // @synthesize tipLabel=_tipLabel;
@property(retain, nonatomic) UIImageView *tipImageView; // @synthesize tipImageView=_tipImageView;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

