//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface IMYFindAccountModel : NSObject
{
    long long _time;
    NSString *_username;
    NSString *_userID;
    unsigned long long _platform;
}

+ (void)initialize;
@property(nonatomic) unsigned long long platform; // @synthesize platform=_platform;
@property(copy, nonatomic) NSString *userID; // @synthesize userID=_userID;
@property(copy, nonatomic) NSString *username; // @synthesize username=_username;
@property(nonatomic) long long time; // @synthesize time=_time;
- (void).cxx_destruct;

@end

