//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class IMYButton, UILabel, UIScrollView;

@interface IMYFadeNavigationBar : UIView
{
    _Bool _disableFade;
    UIScrollView *_scrollView;
    IMYButton *_leftButton;
    IMYButton *_rightButton;
    UILabel *_titleLabel;
    CDUnknownBlockType _leftButtonActionBlock;
    CDUnknownBlockType _rightButtonActionBlock;
    double _fadeOffSet;
    UIView *_bg;
}

@property(retain, nonatomic) UIView *bg; // @synthesize bg=_bg;
@property(nonatomic) _Bool disableFade; // @synthesize disableFade=_disableFade;
@property(nonatomic) double fadeOffSet; // @synthesize fadeOffSet=_fadeOffSet;
@property(copy, nonatomic) CDUnknownBlockType rightButtonActionBlock; // @synthesize rightButtonActionBlock=_rightButtonActionBlock;
@property(copy, nonatomic) CDUnknownBlockType leftButtonActionBlock; // @synthesize leftButtonActionBlock=_leftButtonActionBlock;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) IMYButton *rightButton; // @synthesize rightButton=_rightButton;
@property(retain, nonatomic) IMYButton *leftButton; // @synthesize leftButton=_leftButton;
@property(nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void).cxx_destruct;
- (void)initViews;
- (id)initWithScrollView:(id)arg1;

@end

