//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AFHTTPSessionManager, NSMutableArray, NSURL;

@interface IMYHTTPTaskManager : NSObject
{
    CDUnknownBlockType _taskDidResumeBlock;
    NSMutableArray *_tasks;
    AFHTTPSessionManager *_sessionManager;
}

+ (id)task;
+ (id)manager;
@property(retain, nonatomic) AFHTTPSessionManager *sessionManager; // @synthesize sessionManager=_sessionManager;
@property(retain, nonatomic) NSMutableArray *tasks; // @synthesize tasks=_tasks;
@property(copy, nonatomic) CDUnknownBlockType taskDidResumeBlock; // @synthesize taskDidResumeBlock=_taskDidResumeBlock;
- (void).cxx_destruct;
- (void)cancelAll;
- (void)cancel:(id)arg1;
- (void)enqueueTask:(id)arg1;
@property(nonatomic) long long maxConcurrentCount;
- (id)task;
@property(readonly, nonatomic) NSURL *baseURL;
- (id)initWithBaseURL:(id)arg1;
- (id)init;
- (void)dealloc;
- (void)taskDidResume:(id)arg1;
- (void)removeTask:(id)arg1;

@end

