//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IMYAOPCollectionViewDataSource-Protocol.h"
#import "IMYAOPCollectionViewDelegate-Protocol.h"
#import "IMYIAdManager-Protocol.h"

@class IMYAOPCollectionViewUtils, UICollectionView;

@protocol IMYICollectionAdManager <IMYIAdManager, IMYAOPCollectionViewDelegate, IMYAOPCollectionViewDataSource>
@property(readonly, nonatomic) __weak IMYAOPCollectionViewUtils *aopUtils;
@property(nonatomic) __weak UICollectionView *collectionView;
@end

