//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IMYAdvertiserViewEventDelegate-Protocol.h"
#import "NSObject-Protocol.h"

@class IMYAdvertiserInfo, NSArray, NSString;
@protocol IMYIAdRawDataRequest;

@protocol IMYIAdManager <NSObject, IMYAdvertiserViewEventDelegate>
@property(readonly, nonatomic) _Bool hasAdsData;
@property(copy, nonatomic) NSString *lastRawIds;
@property(readonly, nonatomic) id <IMYIAdRawDataRequest> request;
@property(readonly, nonatomic) IMYAdvertiserInfo *adInfo;
- (long long)fixedAdsIndex;
- (NSArray *)getFeedsArrayFromRequestArray:(NSArray *)arg1;
- (void)loadMoreDataState:(long long)arg1;
- (void)loadMoreData:(long long)arg1;
- (void)loadMoreData:(long long)arg1 appendCount:(long long)arg2;
- (void)resetData;
- (void)updateData;
- (void)clearData;
- (void)refreshData;
- (void)removeAllAppendServices;
- (void)appendServicesWithRawModels:(NSArray *)arg1 isFilter:(_Bool)arg2;
- (void)setupPositionStatics;
- (void)updateServicesWithRawModels:(NSArray *)arg1;
- (void)setupServicesWithRawModels:(NSArray *)arg1;
- (id)initWithADInfo:(IMYAdvertiserInfo *)arg1;
@end

