//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSMutableDictionary;

@interface IMYJumpManager : NSObject
{
    NSMutableDictionary *_jumpMap;
    NSMutableArray *_observerArray;
}

+ (id)shareJumpManager;
+ (void)gotoLogin;
@property(retain, nonatomic) NSMutableArray *observerArray; // @synthesize observerArray=_observerArray;
@property(retain, nonatomic) NSMutableDictionary *jumpMap; // @synthesize jumpMap=_jumpMap;
- (void).cxx_destruct;
- (void)interceptJumpWithBlock:(CDUnknownBlockType)arg1 forMap:(id)arg2 andTypes:(long long)arg3;
- (void)interceptJumpWithObserver:(id)arg1 forMap:(id)arg2 andTypes:(long long)arg3;
- (id)createIntercepObjectForMap:(id)arg1 andTypes:(long long)arg2 andList:(char *)arg3;
- (void)jumptoPageWithType:(long long)arg1 currentVC:(id)arg2 params:(id)arg3 map:(id)arg4;
- (void)addConfigFilePath:(id)arg1;
- (id)init;

@end

