//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface IMYLineChartUtilService : NSObject
{
}

+ (id)getPointsPathWithPoints:(id)arg1 raidus:(double)arg2;
+ (id)getPointPathWithPoint:(struct CGPoint)arg1 radius:(double)arg2;
+ (struct CGPoint)getMaxRight:(id)arg1;
+ (struct CGPoint)getMaxRightPointWithAllDatas:(id)arg1;
+ (struct CGPoint)getPointAtIndex:(long long)arg1 points:(id)arg2;
+ (id)getPathWithData:(id)arg1 isCurve:(_Bool)arg2 isClose:(_Bool)arg3;

@end

