//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IMYLaunchBaseVC.h"

@class MPMoviePlayerController, NSString, UIButton;

@interface IMYLaunchMoviePlayVC : IMYLaunchBaseVC
{
    _Bool _isMovieLoopPlay;
    _Bool _isMovieAutoHide;
    NSString *_moviePath;
    UIButton *_startButton;
    MPMoviePlayerController *_mediaPlayer;
    NSString *_startButtonImageName;
    NSString *_startButtonHighlightImageName;
    double _bottomMargin;
}

@property(nonatomic) double bottomMargin; // @synthesize bottomMargin=_bottomMargin;
@property(copy, nonatomic) NSString *startButtonHighlightImageName; // @synthesize startButtonHighlightImageName=_startButtonHighlightImageName;
@property(copy, nonatomic) NSString *startButtonImageName; // @synthesize startButtonImageName=_startButtonImageName;
@property(retain, nonatomic) MPMoviePlayerController *mediaPlayer; // @synthesize mediaPlayer=_mediaPlayer;
@property(retain, nonatomic) UIButton *startButton; // @synthesize startButton=_startButton;
@property(nonatomic) _Bool isMovieAutoHide; // @synthesize isMovieAutoHide=_isMovieAutoHide;
@property(nonatomic) _Bool isMovieLoopPlay; // @synthesize isMovieLoopPlay=_isMovieLoopPlay;
@property(copy, nonatomic) NSString *moviePath; // @synthesize moviePath=_moviePath;
- (void).cxx_destruct;
- (void)onStartButtonPressed;
- (void)replayMovie:(id)arg1;
- (void)hideMovie;
- (void)playMovie;
- (void)initMovieData;
- (_Bool)displayLaunchStatusBarHidden;
- (void)viewDidLoad;
- (void)_initMyself;

@end

