//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface IMYLaunchVideoPreModel : NSObject
{
    _Bool _isExpire;
    long long _planid;
    long long _material_id;
    NSArray *_material_url;
    double _expire_at;
}

@property(nonatomic) _Bool isExpire; // @synthesize isExpire=_isExpire;
@property(nonatomic) double expire_at; // @synthesize expire_at=_expire_at;
@property(retain, nonatomic) NSArray *material_url; // @synthesize material_url=_material_url;
@property(nonatomic) long long material_id; // @synthesize material_id=_material_id;
@property(nonatomic) long long planid; // @synthesize planid=_planid;
- (void).cxx_destruct;

@end

