//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface IMYNewsRootSegmentRedDocModel : NSObject
{
    _Bool _isActived;
    long long _redId;
    long long _redTag;
    NSString *_redIdentifier;
    CDUnknownBlockType _disappearBlock;
    CDUnknownBlockType _displayBlock;
}

@property(copy, nonatomic) CDUnknownBlockType displayBlock; // @synthesize displayBlock=_displayBlock;
@property(copy, nonatomic) CDUnknownBlockType disappearBlock; // @synthesize disappearBlock=_disappearBlock;
@property(copy, nonatomic) NSString *redIdentifier; // @synthesize redIdentifier=_redIdentifier;
@property(nonatomic) _Bool isActived; // @synthesize isActived=_isActived;
@property(nonatomic) long long redTag; // @synthesize redTag=_redTag;
@property(nonatomic) long long redId; // @synthesize redId=_redId;
- (void).cxx_destruct;

@end

