//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IMYNewsCollectionViewController.h"

#import "CHTCollectionViewDelegateWaterfallLayout-Protocol.h"
#import "IMYNewsRootContainerActionProtocol-Protocol.h"
#import "IMYNewsXiaoShiPinPlayViewControllerDelegate-Protocol.h"
#import "IMY_ThemeChangeProtocol-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class IMYAdSignal, IMYNewsRefreshHeader, IMYNewsXiaoShiPinCell, IMYNewsXiaoShiPinPromptDeleteView, NSArray, NSIndexPath, NSString, UIView;
@protocol IMYIAdManager;

@interface IMYNewsRootXiaoShiPinViewController : IMYNewsCollectionViewController <UICollectionViewDelegate, UICollectionViewDataSource, IMY_ThemeChangeProtocol, IMYNewsXiaoShiPinPlayViewControllerDelegate, CHTCollectionViewDelegateWaterfallLayout, IMYNewsRootContainerActionProtocol>
{
    _Bool _videoFeeds;
    _Bool _isShowAD;
    _Bool _isRefresh;
    _Bool _needFirstRequest;
    _Bool _dataRequestFinished;
    _Bool _isShowed;
    _Bool _isLoadMore;
    _Bool _isViewAppeared;
    _Bool _needRetryRequest;
    IMYNewsRefreshHeader *_headerRefreshView;
    unsigned long long _newsCategoryId;
    unsigned long long _feedsType;
    long long _refreshLoadDataCount;
    long long _bi_entrance;
    UIView *_containerView;
    NSIndexPath *_selIndexPath;
    unsigned long long _refreshCount;
    unsigned long long _loadMoreCount;
    unsigned long long _news_time;
    unsigned long long _responseTime;
    CDUnknownBlockType _loadMoreCallback;
    IMYNewsXiaoShiPinCell *_secondCell;
    IMYNewsXiaoShiPinPromptDeleteView *_promptView;
    NSArray *_cellBackgroundColors;
    id <IMYIAdManager> _adManager;
    NSArray *_adArray;
    IMYAdSignal *_adPositionSignal;
}

@property(nonatomic) _Bool needRetryRequest; // @synthesize needRetryRequest=_needRetryRequest;
@property(retain, nonatomic) IMYAdSignal *adPositionSignal; // @synthesize adPositionSignal=_adPositionSignal;
@property(retain, nonatomic) NSArray *adArray; // @synthesize adArray=_adArray;
@property(retain, nonatomic) id <IMYIAdManager> adManager; // @synthesize adManager=_adManager;
@property(retain, nonatomic) NSArray *cellBackgroundColors; // @synthesize cellBackgroundColors=_cellBackgroundColors;
@property(nonatomic) _Bool isViewAppeared; // @synthesize isViewAppeared=_isViewAppeared;
@property(retain, nonatomic) IMYNewsXiaoShiPinPromptDeleteView *promptView; // @synthesize promptView=_promptView;
@property(nonatomic) __weak IMYNewsXiaoShiPinCell *secondCell; // @synthesize secondCell=_secondCell;
@property(copy, nonatomic) CDUnknownBlockType loadMoreCallback; // @synthesize loadMoreCallback=_loadMoreCallback;
@property(nonatomic) _Bool isLoadMore; // @synthesize isLoadMore=_isLoadMore;
@property(nonatomic) unsigned long long responseTime; // @synthesize responseTime=_responseTime;
@property(nonatomic) unsigned long long news_time; // @synthesize news_time=_news_time;
@property(nonatomic) _Bool isShowed; // @synthesize isShowed=_isShowed;
@property(nonatomic) _Bool dataRequestFinished; // @synthesize dataRequestFinished=_dataRequestFinished;
@property(nonatomic) _Bool needFirstRequest; // @synthesize needFirstRequest=_needFirstRequest;
@property(nonatomic) unsigned long long loadMoreCount; // @synthesize loadMoreCount=_loadMoreCount;
@property(nonatomic) unsigned long long refreshCount; // @synthesize refreshCount=_refreshCount;
@property(retain, nonatomic) NSIndexPath *selIndexPath; // @synthesize selIndexPath=_selIndexPath;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(nonatomic) long long bi_entrance; // @synthesize bi_entrance=_bi_entrance;
@property(nonatomic) _Bool isRefresh; // @synthesize isRefresh=_isRefresh;
@property(nonatomic) long long refreshLoadDataCount; // @synthesize refreshLoadDataCount=_refreshLoadDataCount;
@property(nonatomic) _Bool isShowAD; // @synthesize isShowAD=_isShowAD;
@property(nonatomic) _Bool videoFeeds; // @synthesize videoFeeds=_videoFeeds;
@property(nonatomic) unsigned long long feedsType; // @synthesize feedsType=_feedsType;
@property(nonatomic) unsigned long long newsCategoryId; // @synthesize newsCategoryId=_newsCategoryId;
@property(retain, nonatomic) IMYNewsRefreshHeader *headerRefreshView; // @synthesize headerRefreshView=_headerRefreshView;
- (void).cxx_destruct;
- (void)clickReportWithCell:(id)arg1 forItemAtIndex:(long long)arg2;
- (void)displayReportAction:(long long)arg1 onCell:(id)arg2;
- (void)footerEndRefreshing;
- (void)setMXScrollViewOffset:(double)arg1 scrollView:(id)arg2;
- (void)setRefreshViwOffset:(double)arg1 scrollView:(id)arg2;
- (void)endRefresh:(_Bool)arg1 count:(unsigned long long)arg2;
- (void)firstRequestRefresh;
- (void)autoLoadMoreAction;
- (void)setLastRefreshTime;
- (unsigned long long)lastRefreshTime;
- (_Bool)feedCacheControl;
- (void)delCacheDataAction;
- (void)cacheDataAction:(id)arg1;
- (void)calculateItemSizeInDatasource:(id)arg1;
- (void)loadCacheAction;
- (void)requestDataAction:(_Bool)arg1 loadPre:(_Bool)arg2 fromTab:(_Bool)arg3;
- (void)handleRequestDataSuccess:(id)arg1 loadPre:(_Bool)arg2;
- (void)handleRequestDataError:(id)arg1 loadPre:(_Bool)arg2;
- (id)getRequestParameter:(_Bool)arg1 loadPre:(_Bool)arg2;
- (void)prepareData;
- (_Bool)checkNeedRefresh;
- (void)refreshAction:(_Bool)arg1;
- (void)refreshAction;
- (void)scrollToTop;
- (void)showPromptDeleteView;
- (void)unlikeCell:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (id)imymj_capture:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (id)modelAtIndexPath:(id)arg1;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)IMYNewsXiaoShiPinPlayViewControllerHideImage;
- (void)IMYNewsXiaoShiPinPlayViewControllerScrollToIndex:(long long)arg1 loadMoreBack:(CDUnknownBlockType)arg2;
- (void)IMYNewsXiaoShiPinPlayViewControllerScrollToIndex:(long long)arg1 callBack:(CDUnknownBlockType)arg2;
- (void)initAdmanager;
- (id)collectionLayout;
- (void)prepareUI;
- (void)imy_themeChanged;
- (void)viewDidLayoutSubviews;
- (void)didReceiveMemoryWarning;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)init;
- (id)ga_appendParams;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

