//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UITextViewDelegate-Protocol.h"

@class IMYButton, IMYTouchEXImageView, NSString, UILabel, UITextView;

@interface IMYNewsDislikeInputView : UIView <UITextViewDelegate>
{
    CDUnknownBlockType _backAction;
    CDUnknownBlockType _submitAction;
    IMYButton *_submitButton;
    UILabel *_titleLabel;
    IMYTouchEXImageView *_backImageView;
    UITextView *_textView;
}

@property(retain, nonatomic) UITextView *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) IMYTouchEXImageView *backImageView; // @synthesize backImageView=_backImageView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) IMYButton *submitButton; // @synthesize submitButton=_submitButton;
@property(copy, nonatomic) CDUnknownBlockType submitAction; // @synthesize submitAction=_submitAction;
@property(copy, nonatomic) CDUnknownBlockType backAction; // @synthesize backAction=_backAction;
- (void).cxx_destruct;
- (void)updateSubmitButtonStatus:(_Bool)arg1;
- (void)setupUI;
- (void)textViewDidChange:(id)arg1;
- (void)submitButtonClicked:(id)arg1;
- (void)backTap:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

