//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IMYDragableNavBaseView.h"

@interface IMYNewsXiaoShiPinCommentView : IMYDragableNavBaseView
{
    CDUnknownBlockType _hideCallBack;
    CDUnknownBlockType _dragginBlock;
    CDUnknownBlockType _dragginEndBlock;
}

@property(copy, nonatomic) CDUnknownBlockType dragginEndBlock; // @synthesize dragginEndBlock=_dragginEndBlock;
@property(copy, nonatomic) CDUnknownBlockType dragginBlock; // @synthesize dragginBlock=_dragginBlock;
@property(copy, nonatomic) CDUnknownBlockType hideCallBack; // @synthesize hideCallBack=_hideCallBack;
- (void).cxx_destruct;
- (void)dragEndWithPoint:(struct CGPoint)arg1 shouldHideView:(_Bool)arg2;
- (void)dragingWithPoint:(struct CGPoint)arg1;
- (void)dragBeginWithPoint:(struct CGPoint)arg1;
- (void)initTopViewsWithTitle:(id)arg1;
- (void)viewDidDisappear;
- (void)startHide;

@end

