//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class DACircularProgressView, IMYTouchEXButton, UIImageView, UILabel;

@interface IMYNewsXiaoShiPinLoadingStateView : UIView
{
    UIView *_loadingStateView;
    DACircularProgressView *_progressView;
    UILabel *_loadingStateLabel;
    UIView *_errorStateView;
    IMYTouchEXButton *_retryButton;
    UILabel *_errorStateLabel;
    UIView *_successStateView;
    UIImageView *_successStateIcon;
    UILabel *_successStateLabel;
    UIView *_lastStateView;
}

@property(retain, nonatomic) UIView *lastStateView; // @synthesize lastStateView=_lastStateView;
@property(retain, nonatomic) UILabel *successStateLabel; // @synthesize successStateLabel=_successStateLabel;
@property(retain, nonatomic) UIImageView *successStateIcon; // @synthesize successStateIcon=_successStateIcon;
@property(retain, nonatomic) UIView *successStateView; // @synthesize successStateView=_successStateView;
@property(retain, nonatomic) UILabel *errorStateLabel; // @synthesize errorStateLabel=_errorStateLabel;
@property(retain, nonatomic) IMYTouchEXButton *retryButton; // @synthesize retryButton=_retryButton;
@property(retain, nonatomic) UIView *errorStateView; // @synthesize errorStateView=_errorStateView;
@property(retain, nonatomic) UILabel *loadingStateLabel; // @synthesize loadingStateLabel=_loadingStateLabel;
@property(retain, nonatomic) DACircularProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) UIView *loadingStateView; // @synthesize loadingStateView=_loadingStateView;
- (void).cxx_destruct;
- (void)hideAll;
- (void)showErrorStateWithText:(id)arg1;
- (void)showSuccessStateWithText:(id)arg1;
- (void)showLoadingStateWithText:(id)arg1 progress:(double)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

