//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IMYTableViewCell.h"

@class UIImageView, UILabel;

@interface IMYNewsRecommendPicCell : IMYTableViewCell
{
    UILabel *_contentLabel;
    UILabel *_authorLabel;
    UILabel *_videoTimeLabel;
    UILabel *_viewTimesLabel;
    UIImageView *_imgView;
    UIImageView *_videoTimeBg;
}

@property(retain, nonatomic) UIImageView *videoTimeBg; // @synthesize videoTimeBg=_videoTimeBg;
@property(retain, nonatomic) UIImageView *imgView; // @synthesize imgView=_imgView;
@property(retain, nonatomic) UILabel *viewTimesLabel; // @synthesize viewTimesLabel=_viewTimesLabel;
@property(retain, nonatomic) UILabel *videoTimeLabel; // @synthesize videoTimeLabel=_videoTimeLabel;
@property(retain, nonatomic) UILabel *authorLabel; // @synthesize authorLabel=_authorLabel;
@property(retain, nonatomic) UILabel *contentLabel; // @synthesize contentLabel=_contentLabel;
- (void).cxx_destruct;
- (double)showLineLeftMargin;
- (void)reloadDisplay;
- (void)initContentView;
- (void)_initMyself;

@end

