//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IMYBaseAdPoolManager.h"

@protocol IMYIAdTool;

@interface IMYPopupAdManager : IMYBaseAdPoolManager
{
    _Bool _canDisplay;
    _Bool _haveRefreshData;
    long long _currPositionId;
    id <IMYIAdTool> _popupAdTool;
}

+ (void)load;
@property(nonatomic) _Bool haveRefreshData; // @synthesize haveRefreshData=_haveRefreshData;
@property(nonatomic) _Bool canDisplay; // @synthesize canDisplay=_canDisplay;
@property(retain, nonatomic) id <IMYIAdTool> popupAdTool; // @synthesize popupAdTool=_popupAdTool;
@property(nonatomic) long long currPositionId; // @synthesize currPositionId=_currPositionId;
- (void).cxx_destruct;
- (void)poolFinishFreshView:(id)arg1;
- (id)poolKeyWithModel:(id)arg1 poolMap:(id)arg2;
- (void)setupServicesWithRawModels:(id)arg1;
- (void)appendServicesWithRawModels:(id)arg1 isFilter:(_Bool)arg2;
- (void)removeAllAppendServices;
- (void)refreshData;
- (id)initWithADInfo:(id)arg1;

@end

