//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class UIImageView;

@interface IMYPariseAnimation : NSObject
{
    UIImageView *_praiseImageView;
}

+ (void)showAnimationWithLocation:(struct CGPoint)arg1 inView:(id)arg2;
@property(retain, nonatomic) UIImageView *praiseImageView; // @synthesize praiseImageView=_praiseImageView;
- (void).cxx_destruct;

@end

