//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UINavigationController.h>

#import "IMYViewControllerProtocol-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"

@class NSString, UIPanGestureRecognizer;
@protocol UINavigationControllerDelegate;

@interface IMYPublicBaseNavigationController : UINavigationController <UIGestureRecognizerDelegate, UINavigationControllerDelegate, IMYViewControllerProtocol>
{
    _Bool isCalledInitMyself;
    _Bool _canAction;
    _Bool _enableFullPanGestureRecognizer;
    _Bool _respondsFullPanEnableSEL;
    _Bool _isViewWillAppeared;
    _Bool _isViewDidAppeared;
    _Bool _isViewActived;
    _Bool _isTopItemsFixing;
    id <UINavigationControllerDelegate> _wrapDelegate;
    UIPanGestureRecognizer *_fullPanGestureRecognizer;
    double _panReceiveTouchWidth;
    double _panBeginTouchWidth;
}

+ (void)initialize;
+ (void)addAllNavigationIgnoreControllerName:(id)arg1;
+ (void)setupBarBackgroundImageWithNavVC:(id)arg1 configs:(id)arg2;
+ (void)setAllNavigationBarBackgroundImage:(id)arg1 titleAttributes:(id)arg2 tintColor:(id)arg3;
+ (void)setAllNavigationBarBackgroundImage:(id)arg1 titleColor:(id)arg2 tintColor:(id)arg3;
+ (id)allNavigationControllerIgnoreNames;
+ (id)allNavigationViewControllers;
+ (id)globalNavigationBarMap;
@property(nonatomic) _Bool isTopItemsFixing; // @synthesize isTopItemsFixing=_isTopItemsFixing;
@property(nonatomic) _Bool isViewActived; // @synthesize isViewActived=_isViewActived;
@property(nonatomic) _Bool isViewDidAppeared; // @synthesize isViewDidAppeared=_isViewDidAppeared;
@property(nonatomic) _Bool isViewWillAppeared; // @synthesize isViewWillAppeared=_isViewWillAppeared;
@property(nonatomic) double panBeginTouchWidth; // @synthesize panBeginTouchWidth=_panBeginTouchWidth;
@property(nonatomic) double panReceiveTouchWidth; // @synthesize panReceiveTouchWidth=_panReceiveTouchWidth;
@property(nonatomic) _Bool respondsFullPanEnableSEL; // @synthesize respondsFullPanEnableSEL=_respondsFullPanEnableSEL;
@property(nonatomic) _Bool enableFullPanGestureRecognizer; // @synthesize enableFullPanGestureRecognizer=_enableFullPanGestureRecognizer;
@property(retain, nonatomic) UIPanGestureRecognizer *fullPanGestureRecognizer; // @synthesize fullPanGestureRecognizer=_fullPanGestureRecognizer;
@property(nonatomic) __weak id <UINavigationControllerDelegate> wrapDelegate; // @synthesize wrapDelegate=_wrapDelegate;
@property(nonatomic) _Bool canAction; // @synthesize canAction=_canAction;
- (void).cxx_destruct;
- (long long)preferredInterfaceOrientationForPresentation;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldBeRequiredToFailByGestureRecognizer:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldBeRequiredToFailByGestureRecognizer:(id)arg2;
- (_Bool)shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRequireFailureOfGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (_Bool)fullPanGestureRecognizerShouldBegin:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)fullPanGestureRecognizerHandler:(id)arg1;
- (double)defaultFullPanRightMinBeginWidth;
- (double)defaultFullPanLeftMaxBeginWidth;
- (void)checkNavigationBarItems;
- (void)checkGestureStatus:(id)arg1;
- (id)forwardingTargetForSelector:(SEL)arg1;
- (_Bool)respondsToSelector:(SEL)arg1;
- (id)navigationController:(id)arg1 animationControllerForOperation:(long long)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;
- (void)navigationController:(id)arg1 didShowViewController:(id)arg2 animated:(_Bool)arg3;
- (void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(_Bool)arg3;
@property(nonatomic) __weak id <UINavigationControllerDelegate> delegate; // @dynamic delegate;
- (void)setViewWillAppearInjectNavBarHidenBlockInVC:(id)arg1;
- (void)setViewControllers:(id)arg1 animated:(_Bool)arg2;
- (void)setViewControllers:(id)arg1;
- (void)pushViewController:(id)arg1 animated:(_Bool)arg2;
- (id)popViewControllerAnimated:(_Bool)arg1;
- (id)popToRootViewControllerAnimated:(_Bool)arg1;
- (id)popToViewController:(id)arg1 animated:(_Bool)arg2;
- (_Bool)checkWillPopActionWithAnimated:(_Bool *)arg1;
- (void)resetActionMark;
- (void)actionDelayResetMark;
- (id)actionDelayResetQueueKey;
- (void)dealloc;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
@property(readonly, nonatomic) _Bool isViewLoaded;
- (id)interactivePopGestureRecognizer;
- (void)setCurrentPageEnableFullPanGestureRecognizer:(_Bool)arg1;
- (void)setupFullscreenPopGesture;
- (void)viewDidLoad;
- (void)_initMyself;
- (void)callInitMyself;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithCoder:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

