//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MJRefreshStateHeader.h"

#import "IMY_ThemeChangeProtocol-Protocol.h"

@class CALayer, NSString, UILabel, UIView;

@interface IMYRNStripHeadRefresh : MJRefreshStateHeader <IMY_ThemeChangeProtocol>
{
    _Bool _rotation;
    UILabel *_tipLabel;
    CALayer *_groupLayer;
    CALayer *_topPointLayer;
    CALayer *_bottomPointLayer;
    UIView *_imageBGView;
    UILabel *_messageLabel;
    UIView *_messageBackView;
}

@property(retain, nonatomic) UIView *messageBackView; // @synthesize messageBackView=_messageBackView;
@property(retain, nonatomic) UILabel *messageLabel; // @synthesize messageLabel=_messageLabel;
@property(retain, nonatomic) UIView *imageBGView; // @synthesize imageBGView=_imageBGView;
@property(nonatomic) _Bool rotation; // @synthesize rotation=_rotation;
@property(retain, nonatomic) CALayer *bottomPointLayer; // @synthesize bottomPointLayer=_bottomPointLayer;
@property(retain, nonatomic) CALayer *topPointLayer; // @synthesize topPointLayer=_topPointLayer;
@property(retain, nonatomic) CALayer *groupLayer; // @synthesize groupLayer=_groupLayer;
@property(retain, nonatomic) UILabel *tipLabel; // @synthesize tipLabel=_tipLabel;
- (void).cxx_destruct;
- (void)innerEndRefreshing:(unsigned char)arg1;
- (void)endRefreshing;
- (void)executeRefreshingCallback;
- (void)setPullingPercent:(double)arg1;
- (void)setState:(long long)arg1;
- (void)scrollViewPanStateDidChange:(id)arg1;
- (void)scrollViewContentSizeDidChange:(id)arg1;
- (void)scrollViewContentOffsetDidChange:(id)arg1;
- (void)placeSubviews;
- (void)setMessage:(id)arg1;
- (void)addRotationAniToLayer:(id)arg1;
- (void)setLineLayerStrokeWithProgress:(double)arg1;
- (id)layerWithPoint:(struct CGPoint)arg1;
- (void)imy_themeChanged;
- (void)prepare;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

