//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "IMYChouChouChartCellDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSString, UICollectionView, UICollectionViewFlowLayout, UILabel;
@protocol IMYRecordChartViewDelegate;

@interface IMYRecordChartView : UIView <UICollectionViewDelegate, UICollectionViewDataSource, IMYChouChouChartCellDelegate>
{
    NSArray *_YLabels;
    NSArray *_barColors;
    NSString *_topText;
    NSString *_rightText;
    double _barWidth;
    double _barMargin;
    UICollectionView *_collectionView;
    unsigned long long _selectionStyle;
    NSArray *_items;
    id <IMYRecordChartViewDelegate> _delegate;
    UILabel *_topTextLabel;
    UILabel *_rightTextLabel;
    UICollectionViewFlowLayout *_collectionViewFlowLayout;
    NSMutableArray *_yLabelsArray;
}

@property(retain, nonatomic) NSMutableArray *yLabelsArray; // @synthesize yLabelsArray=_yLabelsArray;
@property(retain, nonatomic) UICollectionViewFlowLayout *collectionViewFlowLayout; // @synthesize collectionViewFlowLayout=_collectionViewFlowLayout;
@property(retain, nonatomic) UILabel *rightTextLabel; // @synthesize rightTextLabel=_rightTextLabel;
@property(retain, nonatomic) UILabel *topTextLabel; // @synthesize topTextLabel=_topTextLabel;
@property(nonatomic) __weak id <IMYRecordChartViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSArray *items; // @synthesize items=_items;
@property(nonatomic) unsigned long long selectionStyle; // @synthesize selectionStyle=_selectionStyle;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(readonly, nonatomic) double barMargin; // @synthesize barMargin=_barMargin;
@property(readonly, nonatomic) double barWidth; // @synthesize barWidth=_barWidth;
@property(retain, nonatomic) NSString *rightText; // @synthesize rightText=_rightText;
@property(retain, nonatomic) NSString *topText; // @synthesize topText=_topText;
@property(retain, nonatomic) NSArray *barColors; // @synthesize barColors=_barColors;
@property(retain, nonatomic) NSArray *YLabels; // @synthesize YLabels=_YLabels;
- (void).cxx_destruct;
@property(readonly, nonatomic) long long visibleBarNum;
- (void)scrollViewDidScroll:(id)arg1;
- (void)chartBarButtonPressed:(id)arg1;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)p_strokeYLabels;
- (id)p_createLabelWithText:(id)arg1;
- (id)p_createCollectionView;
- (void)p_init;
- (void)reloadData;
- (id)initWithFrame:(struct CGRect)arg1 barWidth:(double)arg2 barMargin:(double)arg3 barColors:(id)arg4 items:(id)arg5 topText:(id)arg6 yLabels:(id)arg7 selectionStyle:(unsigned long long)arg8;
- (id)initWithFrame:(struct CGRect)arg1 barWidth:(double)arg2 barMargin:(double)arg3 selectionStyle:(unsigned long long)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

