//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface IMYRecordUtils : NSObject
{
}

+ (id)ovulateDateDict;
+ (id)baby3YearsOldDate;
+ (id)calendarMaxDate;
+ (id)calendarMinDate;
+ (long long)monthDiff:(id)arg1 newDate:(id)arg2;
+ (id)userId;
+ (_Bool)isTempUser;
+ (id)selectedPregnancy;
+ (_Bool)needShowQQ;
+ (_Bool)needShowWeChat;
+ (_Bool)isPregnancyEndNotComplete;
+ (_Bool)showBGCIsAnalyze:(_Bool)arg1;
+ (id)intervalToBabyBirthDay:(id)arg1;
+ (double)dateBeforeBaby3YearsOld;
+ (double)dateAfterBabyBirth;
+ (id)babyBirthDate;

@end

