//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class IMYRecordChartCell, IMYRecordChartView;

@protocol IMYRecordChartViewDelegate <NSObject>

@optional
- (void)recordChartView:(IMYRecordChartView *)arg1 disPlayingCellWithRange:(struct _NSRange)arg2;
- (void)recordChartViewPressed:(IMYRecordChartView *)arg1;
- (void)recordChartView:(IMYRecordChartView *)arg1 BarButtonPressed:(IMYRecordChartCell *)arg2 index:(long long)arg3;
@end

