//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IMYSimpleCellModel.h"

@interface IMYSimpleSwitchModel : IMYSimpleCellModel
{
    _Bool _on;
    CDUnknownBlockType _onSwitchStateChanged;
}

@property(copy, nonatomic) CDUnknownBlockType onSwitchStateChanged; // @synthesize onSwitchStateChanged=_onSwitchStateChanged;
@property _Bool on; // @synthesize on=_on;
- (void).cxx_destruct;
- (id)init;

@end

