//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IMYTLViewController.h"

#import "IMYTLGalleryInputHeaderReusableViewDelegate-Protocol.h"
#import "IMYTLPhotoBrowserDelegate-Protocol.h"
#import "MWPhotoBrowserDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UIViewControllerTransitioningDelegate-Protocol.h"

@class IMYCaptionView, IMYPickerView, IMYTLCollectionView, IMYTLGalleryBottomView, IMYTLGalleryCell, IMYTLGalleryInputHeaderReusableView, IMYTLGalleryVM, IMYTLHomeListVM, IMYTLPhotoBrowser, IMYTLPhotoDismissInteractive, NSIndexPath, NSLayoutConstraint, NSString;

@interface IMYTLGalleryViewController : IMYTLViewController <UICollectionViewDataSource, UICollectionViewDelegate, MWPhotoBrowserDelegate, IMYTLPhotoBrowserDelegate, IMYTLGalleryInputHeaderReusableViewDelegate, UIViewControllerTransitioningDelegate>
{
    _Bool _isManage;
    _Bool _needReloadCell;
    _Bool _automaticallyRefresh;
    IMYTLCollectionView *_collectionView;
    double _time;
    IMYTLGalleryCell *_currentDisplayCell;
    IMYTLHomeListVM *_viewModel;
    IMYTLGalleryVM *_galleryVM;
    IMYTLGalleryBottomView *_bottomView;
    IMYCaptionView *_captionView;
    IMYTLPhotoBrowser *_browser;
    NSLayoutConstraint *_bottomMarginConstraint;
    NSString *_birthTitle;
    IMYTLGalleryInputHeaderReusableView *_headerReusableView;
    IMYTLPhotoDismissInteractive *_dismissInteractive;
    NSIndexPath *_currentDisplayCellIndexPath;
    IMYPickerView *_updateTimePicker;
    NSString *_lastBabyStory;
}

@property(copy, nonatomic) NSString *lastBabyStory; // @synthesize lastBabyStory=_lastBabyStory;
@property(retain, nonatomic) IMYPickerView *updateTimePicker; // @synthesize updateTimePicker=_updateTimePicker;
@property(nonatomic) _Bool automaticallyRefresh; // @synthesize automaticallyRefresh=_automaticallyRefresh;
@property(nonatomic) _Bool needReloadCell; // @synthesize needReloadCell=_needReloadCell;
@property(retain, nonatomic) NSIndexPath *currentDisplayCellIndexPath; // @synthesize currentDisplayCellIndexPath=_currentDisplayCellIndexPath;
@property(retain, nonatomic) IMYTLPhotoDismissInteractive *dismissInteractive; // @synthesize dismissInteractive=_dismissInteractive;
@property(retain, nonatomic) IMYTLGalleryInputHeaderReusableView *headerReusableView; // @synthesize headerReusableView=_headerReusableView;
@property(copy, nonatomic) NSString *birthTitle; // @synthesize birthTitle=_birthTitle;
@property(retain, nonatomic) NSLayoutConstraint *bottomMarginConstraint; // @synthesize bottomMarginConstraint=_bottomMarginConstraint;
@property(nonatomic) __weak IMYTLPhotoBrowser *browser; // @synthesize browser=_browser;
@property(retain, nonatomic) IMYCaptionView *captionView; // @synthesize captionView=_captionView;
@property(retain, nonatomic) IMYTLGalleryBottomView *bottomView; // @synthesize bottomView=_bottomView;
@property(nonatomic) _Bool isManage; // @synthesize isManage=_isManage;
@property(retain, nonatomic) IMYTLGalleryVM *galleryVM; // @synthesize galleryVM=_galleryVM;
@property(retain, nonatomic) IMYTLHomeListVM *viewModel; // @synthesize viewModel=_viewModel;
@property(retain, nonatomic) IMYTLGalleryCell *currentDisplayCell; // @synthesize currentDisplayCell=_currentDisplayCell;
@property(nonatomic) double time; // @synthesize time=_time;
@property(retain, nonatomic) IMYTLCollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (void).cxx_destruct;
- (void)showUpdateTimePickerWithConfirmBlock:(CDUnknownBlockType)arg1 cancelBlock:(CDUnknownBlockType)arg2;
- (void)resetManageStatus;
- (void)handleFinishPhotoChangeWithToRemoveArray:(id)arg1 toRemoveIndexPathArray:(id)arg2 toRemoveIndexArray:(id)arg3 isDelete:(long long)arg4;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (id)interactionControllerForDismissal:(id)arg1;
- (id)interactionControllerForPresentation:(id)arg1;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (void)setSimpleMode;
- (void)setNormalMode;
- (void)updatePhotosTime:(id)arg1 photos:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)updateSelectePhotosTime:(id)arg1;
- (void)deletePhotos:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)deleteSelectePhotos;
- (void)editAction;
- (void)requestData;
- (void)galleryInputHeaderReusableView:(id)arg1 didChangeToHeight:(float)arg2;
- (void)galleryInputHeaderReusableView:(id)arg1 willChangeToHeight:(float)arg2;
- (void)galleryInputHeaderReusableViewDidEndEditing:(id)arg1;
- (void)galleryInputHeaderReusableViewDidBeginEditing:(id)arg1;
- (_Bool)galleryInputHeaderReusableViewShouldBeginEditing:(id)arg1;
- (_Bool)galleryInputHeaderReusableViewShouldReturn:(id)arg1;
- (void)saveBabyStory:(id)arg1;
- (void)updatePhotoTime:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)deletePhoto:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)photoBrowser:(id)arg1 updatePhotoTimeAtIndex:(unsigned long long)arg2;
- (void)photoBrowser:(id)arg1 deletePhotoAtIndex:(unsigned long long)arg2;
- (void)photoBrowser:(id)arg1 addTag:(id)arg2 photoAtIndex:(unsigned long long)arg3;
- (_Bool)photoBrowser:(id)arg1 shouldEditAtIndex:(unsigned long long)arg2 editType:(int)arg3 reason:(int *)arg4;
- (void)photoBrowser:(id)arg1 didDisplayPhotoAtIndex:(unsigned long long)arg2;
- (id)photoBrowser:(id)arg1 titleForPhotoAtIndex:(unsigned long long)arg2;
- (id)photoBrowser:(id)arg1 photoAtIndex:(unsigned long long)arg2;
- (unsigned long long)numberOfPhotosInPhotoBrowser:(id)arg1;
- (_Bool)isLoadNextPage:(id)arg1;
- (void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)initData;
- (void)initUI;
- (void)viewDidLayoutSubviews;
- (void)dealloc;
- (void)viewDidLoad;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

