//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSString, RACSignal;

@protocol IMYTLPersistProtocol <NSObject>
+ (RACSignal *)persistDelete:(NSArray *)arg1 fromUser:(_Bool)arg2 transaction:(_Bool)arg3;
+ (RACSignal *)persistMarkDelete:(NSArray *)arg1 deleteFlags:(NSArray *)arg2 fromUser:(_Bool)arg3 transaction:(_Bool)arg4;
+ (RACSignal *)persistUpdate:(NSArray *)arg1 fromUser:(_Bool)arg2 transaction:(_Bool)arg3;
+ (RACSignal *)persistCreate:(NSArray *)arg1 fromUser:(_Bool)arg2 transaction:(_Bool)arg3;
+ (unsigned long long)persistDataCountGetFromLocalWithWhere:(id)arg1;
+ (NSArray *)persistGetFromLocalWithWhere:(id)arg1 orderBy:(NSString *)arg2 offset:(unsigned long long)arg3 count:(unsigned long long)arg4;
+ (NSArray *)persistGetFromLocalWithWhere:(id)arg1;
+ (NSArray *)persistGetAllChangedFromLocal;
+ (NSArray *)persistGetAllFromLocal;
+ (NSString *)persistDataChagedNotificationKey;
+ (NSString *)persistTableName;
+ (NSArray *)persistKeepKeys;
+ (NSString *)persistLocalPrimaryKey;
+ (NSString *)persistPrimaryKey;
@property(copy, nonatomic) CDUnknownBlockType persistDidDeleteBlock;
@property(copy, nonatomic) CDUnknownBlockType persistDidUpdateBlock;
@property(copy, nonatomic) CDUnknownBlockType persistWillUpdateBlock;
@property(copy, nonatomic) CDUnknownBlockType persistDidCreateBlock;
@property(copy, nonatomic) CDUnknownBlockType persistWillCreateBlock;
@property(nonatomic) double persistStart_at;
@property(nonatomic) double persistUpdated_at;
@property(nonatomic) double persistCreated_at;
@property(nonatomic) long long persistID;
@property(nonatomic) long long persistModified;
@property(nonatomic) _Bool persistDeleteFlag;
- (unsigned long long)persistDeleteFromLocal:(_Bool)arg1;
- (unsigned long long)persistMarkDeleteToLocal:(_Bool)arg1 fromUser:(_Bool)arg2;
- (unsigned long long)persistUpdateToLocal:(_Bool)arg1;
- (unsigned long long)persistCreateToLocal:(_Bool)arg1;
@end

