//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IMYTLModel.h"

@class NSArray, NSString;
@protocol IMYTLRecordModel;

@interface IMYTLTimeListModel : IMYTLModel
{
    _Bool _is_last_page;
    _Bool _type;
    double _day;
    NSString *_title;
    NSArray<IMYTLRecordModel> *_time_line;
    double _last_taken_at;
    long long _last_id;
    long long _last_taken_count;
    long long _baby_id;
    double _taken_date;
    long long _event_id;
    long long _event_user;
    long long _identity_id;
    NSString *_identity_name;
    double _created_at;
    NSArray *_comments;
    NSArray *_timelines;
    long long _mark_id;
    NSString *_mark_name;
}

+ (id)imy_yyjsonPropertyGenericClass;
@property(retain, nonatomic) NSString *mark_name; // @synthesize mark_name=_mark_name;
@property(nonatomic) long long mark_id; // @synthesize mark_id=_mark_id;
@property(retain, nonatomic) NSArray *timelines; // @synthesize timelines=_timelines;
@property(retain, nonatomic) NSArray *comments; // @synthesize comments=_comments;
@property(nonatomic) double created_at; // @synthesize created_at=_created_at;
@property(retain, nonatomic) NSString *identity_name; // @synthesize identity_name=_identity_name;
@property(nonatomic) long long identity_id; // @synthesize identity_id=_identity_id;
@property(nonatomic) _Bool type; // @synthesize type=_type;
@property(nonatomic) long long event_user; // @synthesize event_user=_event_user;
@property(nonatomic) long long event_id; // @synthesize event_id=_event_id;
@property(nonatomic) double taken_date; // @synthesize taken_date=_taken_date;
@property(nonatomic) long long baby_id; // @synthesize baby_id=_baby_id;
@property(nonatomic) long long last_taken_count; // @synthesize last_taken_count=_last_taken_count;
@property(nonatomic) _Bool is_last_page; // @synthesize is_last_page=_is_last_page;
@property(nonatomic) long long last_id; // @synthesize last_id=_last_id;
@property(nonatomic) double last_taken_at; // @synthesize last_taken_at=_last_taken_at;
@property(retain, nonatomic) NSArray<IMYTLRecordModel> *time_line; // @synthesize time_line=_time_line;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) double day; // @synthesize day=_day;
- (void).cxx_destruct;

@end

