//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface IMYTLHomeYunCommentSerice : NSObject
{
}

+ (id)createComments:(id)arg1;
+ (void)deleteCommentBabyId:(long long)arg1 comments:(id)arg2 completed:(CDUnknownBlockType)arg3;
+ (void)sendCommentBabyId:(long long)arg1 comments:(id)arg2 completed:(CDUnknownBlockType)arg3;

@end

