//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IMYTLHucaiPrintEidtVC.h"

@interface IMYTLHucaiPrintPhotosEidtVC : IMYTLHucaiPrintEidtVC
{
}

- (void)commitToService:(CDUnknownBlockType)arg1 fail:(CDUnknownBlockType)arg2;
- (void)deleteModel;
- (void)deleteBtnAction:(id)arg1;
- (void)selectPhotoAction:(id)arg1 isReplace:(_Bool)arg2;
- (void)registerCollectionViewCell;
- (void)updateTitleView;
- (void)initVM;
- (void)setupTitleView;
- (void)initData;
- (void)viewDidLoad;

@end

