//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class IMYTLCBFamilyMangeResultModel, UIImageView, UILabel;

@interface IMYTLCBFamilyManageCell : UITableViewCell
{
    _Bool _showArrow;
    UIImageView *_avaterImgView;
    UILabel *_titleLabel;
    UILabel *_inviteCountLable;
    UILabel *_lastInviteLabel;
    UIImageView *_arrowImgView;
    IMYTLCBFamilyMangeResultModel *_model;
}

+ (double)cellHeight;
@property(nonatomic) _Bool showArrow; // @synthesize showArrow=_showArrow;
@property(retain, nonatomic) IMYTLCBFamilyMangeResultModel *model; // @synthesize model=_model;
@property(nonatomic) __weak UIImageView *arrowImgView; // @synthesize arrowImgView=_arrowImgView;
@property(nonatomic) __weak UILabel *lastInviteLabel; // @synthesize lastInviteLabel=_lastInviteLabel;
@property(nonatomic) __weak UILabel *inviteCountLable; // @synthesize inviteCountLable=_inviteCountLable;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak UIImageView *avaterImgView; // @synthesize avaterImgView=_avaterImgView;
- (void).cxx_destruct;
- (id)resetVisitCountString:(long long)arg1;
- (id)resetLastVisitString:(double)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

