//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSHashTable, NSMutableDictionary, NSTimer;

@interface IMYTimerHelper : NSObject
{
    double timeInterval;
    NSHashTable *objectTable;
    NSMutableDictionary *blockMap;
    NSTimer *timer;
}

+ (id)timerHelperWithInterval:(double)arg1;
+ (id)runingTimerMapTable;
+ (id)defaultTimerHelper;
- (void).cxx_destruct;
- (void)removeTimerForKey:(id)arg1;
- (void)removeTimerForObject:(id)arg1;
- (void)addTimerForBlock:(CDUnknownBlockType)arg1 key:(id)arg2;
- (void)addTimerForObject:(id)arg1;
- (void)_timerRuning;
- (void)dealloc;
- (void)checkNeedStopTimer_main;
- (void)checkNeedStopTimer;
- (void)checkNeedStartTimer_main;
- (void)checkNeedStartTimer;
@property(readonly, nonatomic) double interval;
- (id)initPrivateWithTimeInterval:(double)arg1;
- (id)initWithTimeInterval:(double)arg1;
- (id)init;
- (void)_updateView;

@end

