//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "IMYVideoViewDelegate-Protocol.h"

@class HLVideoPlayerView, IMYTLBrowserVideoModel, IMYVideoModel, IMYVideoView, NSString, RACDisposable, UIColor, UIImage, UITapGestureRecognizer;

@interface IMYTLBrowserVideoPlayer : UIView <IMYVideoViewDelegate>
{
    _Bool _navBarIsHiden;
    _Bool _userSeeking;
    _Bool _isInCelluarTip;
    _Bool _hideControlls;
    _Bool _isSeekLeadToPlay;
    _Bool _forceShowNav;
    _Bool _isFirstPlay;
    IMYTLBrowserVideoModel *_model;
    CDUnknownBlockType _didFinishPlay;
    CDUnknownBlockType _userTap;
    IMYVideoView *_videoView;
    IMYVideoModel *_videoModel;
    HLVideoPlayerView *_videoHL;
    double _userSeekTime;
    double _lastFrameTime;
    UIView *_loadingLocalSourceHud;
    RACDisposable *_bottomHideDisposable;
    RACDisposable *_netChangeDisposable;
    RACDisposable *_scrubberDisposable;
    UIImage *_hintOrignalImage;
    UIColor *_hintOrignalBgColor;
    UITapGestureRecognizer *_hintTapGes;
}

@property(retain, nonatomic) UITapGestureRecognizer *hintTapGes; // @synthesize hintTapGes=_hintTapGes;
@property(retain, nonatomic) UIColor *hintOrignalBgColor; // @synthesize hintOrignalBgColor=_hintOrignalBgColor;
@property(retain, nonatomic) UIImage *hintOrignalImage; // @synthesize hintOrignalImage=_hintOrignalImage;
@property(retain, nonatomic) RACDisposable *scrubberDisposable; // @synthesize scrubberDisposable=_scrubberDisposable;
@property(retain, nonatomic) RACDisposable *netChangeDisposable; // @synthesize netChangeDisposable=_netChangeDisposable;
@property(retain, nonatomic) RACDisposable *bottomHideDisposable; // @synthesize bottomHideDisposable=_bottomHideDisposable;
@property(retain, nonatomic) UIView *loadingLocalSourceHud; // @synthesize loadingLocalSourceHud=_loadingLocalSourceHud;
@property(nonatomic) _Bool isFirstPlay; // @synthesize isFirstPlay=_isFirstPlay;
@property(nonatomic) _Bool forceShowNav; // @synthesize forceShowNav=_forceShowNav;
@property(nonatomic) double lastFrameTime; // @synthesize lastFrameTime=_lastFrameTime;
@property(nonatomic) double userSeekTime; // @synthesize userSeekTime=_userSeekTime;
@property(nonatomic) _Bool isSeekLeadToPlay; // @synthesize isSeekLeadToPlay=_isSeekLeadToPlay;
@property(retain, nonatomic) HLVideoPlayerView *videoHL; // @synthesize videoHL=_videoHL;
@property(retain, nonatomic) IMYVideoModel *videoModel; // @synthesize videoModel=_videoModel;
@property(retain, nonatomic) IMYVideoView *videoView; // @synthesize videoView=_videoView;
@property(nonatomic) _Bool hideControlls; // @synthesize hideControlls=_hideControlls;
@property(nonatomic) _Bool isInCelluarTip; // @synthesize isInCelluarTip=_isInCelluarTip;
@property(nonatomic) _Bool userSeeking; // @synthesize userSeeking=_userSeeking;
@property(copy, nonatomic) CDUnknownBlockType userTap; // @synthesize userTap=_userTap;
@property(copy, nonatomic) CDUnknownBlockType didFinishPlay; // @synthesize didFinishPlay=_didFinishPlay;
@property(nonatomic) _Bool navBarIsHiden; // @synthesize navBarIsHiden=_navBarIsHiden;
@property(retain, nonatomic) IMYTLBrowserVideoModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)dealloc;
@property(readonly, nonatomic) double videoCurrentFrame;
- (void)checkPlayerEndTime:(double)arg1;
- (void)customViewPlayerControllsUI;
- (void)updateVideoPlayerBottomProgress:(double)arg1;
- (void)updateVideoPlayerBottomTotalTime;
- (void)autoHideControls;
- (void)playerView:(id)arg1 didFailWithError:(id)arg2;
- (void)playerView:(id)arg1 didControlByEvent:(long long)arg2;
- (void)playerView:(id)arg1 didPlayFrame:(double)arg2;
- (void)playerView:(id)arg1 durationDidLoad:(id)arg2;
- (void)playerViewDidFinishPlaying:(id)arg1;
- (void)playerView:(id)arg1 didChangeStateFrom:(long long)arg2;
- (void)playerViewDidStartPlaying:(id)arg1;
- (void)playerViewWillStartPlaying:(id)arg1;
- (void)setupVideoView;
- (void)hintTapAction:(id)arg1;
- (void)setupPlayModel;
- (_Bool)isPlaying;
- (void)clear;
- (void)stop;
- (void)pause;
- (void)resume;
- (void)play;
- (id)initWithFrame:(struct CGRect)arg1 model:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

