//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIImage;

@interface IMYTLBabyMangeSiderBottomModel : NSObject
{
    _Bool _enable;
    long long _type;
    NSString *_title;
    UIImage *_img;
}

@property(nonatomic) _Bool enable; // @synthesize enable=_enable;
@property(retain, nonatomic) UIImage *img; // @synthesize img=_img;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) long long type; // @synthesize type=_type;
- (void).cxx_destruct;

@end

