//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IMYFeedsAdManager.h"

@class NSArray;
@protocol IMYIAdTool;

@interface IMYTTQHomeFeedsAdManager : IMYFeedsAdManager
{
    _Bool _isFeeds;
    _Bool _haveFeedsHot;
    long long _round;
    NSArray *_adfeedsInfos;
    long long _lastReadIndex;
    CDUnknownBlockType _haveLineBlock;
    CDUnknownBlockType _hiddenHeaderBlock;
    CDUnknownBlockType _hiddenFooterBlock;
    id <IMYIAdTool> _bannerAdTool;
    id <IMYIAdTool> _signInTool;
    long long _prePagetype;
    long long _pagetype;
}

@property(nonatomic) long long pagetype; // @synthesize pagetype=_pagetype;
@property(nonatomic) long long prePagetype; // @synthesize prePagetype=_prePagetype;
@property(retain, nonatomic) id <IMYIAdTool> signInTool; // @synthesize signInTool=_signInTool;
@property(retain, nonatomic) id <IMYIAdTool> bannerAdTool; // @synthesize bannerAdTool=_bannerAdTool;
@property(copy, nonatomic) CDUnknownBlockType hiddenFooterBlock; // @synthesize hiddenFooterBlock=_hiddenFooterBlock;
@property(copy, nonatomic) CDUnknownBlockType hiddenHeaderBlock; // @synthesize hiddenHeaderBlock=_hiddenHeaderBlock;
@property(copy, nonatomic) CDUnknownBlockType haveLineBlock; // @synthesize haveLineBlock=_haveLineBlock;
@property(nonatomic) long long lastReadIndex; // @synthesize lastReadIndex=_lastReadIndex;
@property(nonatomic) _Bool haveFeedsHot; // @synthesize haveFeedsHot=_haveFeedsHot;
@property(retain, nonatomic) NSArray *adfeedsInfos; // @synthesize adfeedsInfos=_adfeedsInfos;
@property(nonatomic) long long round; // @synthesize round=_round;
@property(nonatomic) _Bool isFeeds; // @synthesize isFeeds=_isFeeds;
- (void).cxx_destruct;
- (void)loadedWithModel:(id)arg1 sender:(id)arg2 userInfo:(id)arg3;
- (void)dismissWithModel:(id)arg1 sender:(id)arg2 userInfo:(id)arg3;
- (void)closeWithModel:(id)arg1 sender:(id)arg2 userInfo:(id)arg3;
- (void)clickWithModel:(id)arg1 sender:(id)arg2 userInfo:(id)arg3;
- (void)displayWithModel:(id)arg1 sender:(id)arg2 userInfo:(id)arg3;
- (void)setupEmptyData:(id)arg1;
- (void)aopTableUtils:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)getAdTableViewCellForPosition:(id)arg1;
- (void)removeAdPosition:(id)arg1;
- (void)setupPositionMapWithArray:(id)arg1;
- (void)setupAdPositionsWithSectionNumber:(long long)arg1;
- (void)poolFinishFreshView:(id)arg1;
- (void)setupServicesWithRawModels:(id)arg1;
- (void)onRequestParamsBuilding:(id)arg1;
- (void)refreshData;
- (id)initWithADInfo:(id)arg1;

@end

