//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IMYTLSyncModel.h"

@class NSArray, NSString;
@protocol IMYTLDayValueModel, IMYTLRecordModel, IMYTLUploadInfoModel;

@interface IMYTLListResponse : IMYTLSyncModel
{
    long long _upload_result;
    long long _sync_result;
    NSString *_babySN;
    NSArray<IMYTLRecordModel> *_time_line;
    NSArray<IMYTLDayValueModel> *_day_title;
    NSArray<IMYTLUploadInfoModel> *_upload_info;
}

+ (id)syncTimestampKey;
+ (void)initialize;
@property(retain, nonatomic) NSArray<IMYTLUploadInfoModel> *upload_info; // @synthesize upload_info=_upload_info;
@property(retain, nonatomic) NSArray<IMYTLDayValueModel> *day_title; // @synthesize day_title=_day_title;
@property(retain, nonatomic) NSArray<IMYTLRecordModel> *time_line; // @synthesize time_line=_time_line;
@property(retain, nonatomic) NSString *babySN; // @synthesize babySN=_babySN;
@property(nonatomic) long long sync_result; // @synthesize sync_result=_sync_result;
@property(nonatomic) long long upload_result; // @synthesize upload_result=_upload_result;
- (void).cxx_destruct;

@end

