//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface IMYTLHomeBubbleTipModel : NSObject
{
}

+ (void)saveUserBubbleInfos:(id)arg1;
+ (id)getUserBubbleInfos;
+ (_Bool)checkHasTimelines;
+ (_Bool)checkPower;
+ (void)updateHomeBubbleTipLastShowTime:(double)arg1;
+ (void)updateHomeBubbleTipInterval:(double)arg1;
+ (_Bool)needShowHomeBubbleTimeEnd;
+ (_Bool)needShowHomeBubbleNoPhotos;

@end

