//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IMYTTQVDetailBaseViewController.h"

#import "IMYTTQVCommentContainerDelegate-Protocol.h"

@class IMYSimpleTableView, IMYTTQVCommentContainer, IMYTouchEXButton, NSString, RACSignal, RACSubject, UIView;
@protocol IMYITableViewAdManager;

@interface IMYTTQVContentDetailBaseController : IMYTTQVDetailBaseViewController <IMYTTQVCommentContainerDelegate>
{
    _Bool _isNoShowAd;
    _Bool _isAudioNews;
    _Bool _isJumpCommentArea;
    _Bool _autoPopCommentViewWhenNoCommentDatas;
    _Bool _autoScrollToCommentArea;
    NSString *_url;
    IMYSimpleTableView *_tableView;
    IMYTouchEXButton *_topRightButton;
    IMYTTQVCommentContainer *_commentContainer;
    double _headerMaxOffset;
    unsigned long long _fromType;
    RACSubject *_newsWebDidLoadSubject;
    UIView *_headerView;
    id <IMYITableViewAdManager> _adManager;
    long long _storeHeaderOffsetY;
    long long _storeCommentOffsetY;
    double _webDidScrollY;
    RACSignal *_newsWebDidLoadSignal;
}

@property(retain, nonatomic) RACSignal *newsWebDidLoadSignal; // @synthesize newsWebDidLoadSignal=_newsWebDidLoadSignal;
@property(nonatomic) double webDidScrollY; // @synthesize webDidScrollY=_webDidScrollY;
@property(nonatomic) long long storeCommentOffsetY; // @synthesize storeCommentOffsetY=_storeCommentOffsetY;
@property(nonatomic) long long storeHeaderOffsetY; // @synthesize storeHeaderOffsetY=_storeHeaderOffsetY;
@property(retain, nonatomic) id <IMYITableViewAdManager> adManager; // @synthesize adManager=_adManager;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) RACSubject *newsWebDidLoadSubject; // @synthesize newsWebDidLoadSubject=_newsWebDidLoadSubject;
@property(nonatomic) unsigned long long fromType; // @synthesize fromType=_fromType;
@property(nonatomic) _Bool autoScrollToCommentArea; // @synthesize autoScrollToCommentArea=_autoScrollToCommentArea;
@property(nonatomic) _Bool autoPopCommentViewWhenNoCommentDatas; // @synthesize autoPopCommentViewWhenNoCommentDatas=_autoPopCommentViewWhenNoCommentDatas;
@property(nonatomic) _Bool isJumpCommentArea; // @synthesize isJumpCommentArea=_isJumpCommentArea;
@property(nonatomic) _Bool isAudioNews; // @synthesize isAudioNews=_isAudioNews;
@property(nonatomic) _Bool isNoShowAd; // @synthesize isNoShowAd=_isNoShowAd;
@property(nonatomic) double headerMaxOffset; // @synthesize headerMaxOffset=_headerMaxOffset;
@property(retain, nonatomic) IMYTTQVCommentContainer *commentContainer; // @synthesize commentContainer=_commentContainer;
@property(retain, nonatomic) IMYTouchEXButton *topRightButton; // @synthesize topRightButton=_topRightButton;
@property(retain, nonatomic) IMYSimpleTableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
- (void).cxx_destruct;
- (void)refreshAction;
- (void)networkErrorRetryAction;
- (void)commentContainer:(id)arg1 didFinishLoadData:(id)arg2;
- (void)commentContainer:(id)arg1 scrollViewDidEndDecelerating:(id)arg2;
- (void)commentContainer:(id)arg1 scrollViewDidScroll:(id)arg2;
- (void)commentContainer:(id)arg1 didSendCommentModel:(id)arg2;
- (void)prepareData;
- (void)jumpCommentAreaAction;
- (void)commentsButtonAction:(id)arg1;
- (void)setViewModel:(id)arg1;
- (void)updateHeaderViewHeight:(double)arg1;
- (void)setupcommentContainer;
- (void)setupNavigationView;
- (id)createHeaView;
- (void)prepareUI;
- (id)setupNavPublisherView;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)checkStatusBarStyle;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

