//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString;

@interface IMYURIPathMap : NSObject
{
    NSString *_path;
    NSString *_className;
    NSDictionary *_paramsToProperty;
}

+ (id)pathMapWithPath:(id)arg1 className:(id)arg2 binding:(id)arg3;
+ (id)pathMapWithPath:(id)arg1 className:(id)arg2;
@property(copy, nonatomic) NSDictionary *paramsToProperty; // @synthesize paramsToProperty=_paramsToProperty;
@property(copy, nonatomic) NSString *className; // @synthesize className=_className;
@property(copy, nonatomic) NSString *path; // @synthesize path=_path;
- (void).cxx_destruct;
@property(readonly, nonatomic) Class classNameToClass;

@end

