//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IMYTableViewCell.h"

@class NSString, UIImageView, UILabel;

@interface IMYYBOrder2CoinLoginCell : IMYTableViewCell
{
    NSString *_prompt_for_login;
    NSString *_bg_image;
    UILabel *_title_label;
    UIImageView *_bg_imgV;
}

+ (double)cellHeight;
+ (id)cellWithTableView:(id)arg1;
@property(nonatomic) __weak UIImageView *bg_imgV; // @synthesize bg_imgV=_bg_imgV;
@property(nonatomic) __weak UILabel *title_label; // @synthesize title_label=_title_label;
@property(copy, nonatomic) NSString *bg_image; // @synthesize bg_image=_bg_image;
@property(copy, nonatomic) NSString *prompt_for_login; // @synthesize prompt_for_login=_prompt_for_login;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setFrame:(struct CGRect)arg1;
- (void)awakeFromNib;

@end

