//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "IMYViewCacheReuseProtocol-Protocol.h"

@class IMYRoundButton, IMYYBCountDownView, IMYYBSessionDetailModel, UIButton, UIImageView, UILabel;

@interface IMYYBSessionCell : UIView <IMYViewCacheReuseProtocol>
{
    _Bool _soldOut;
    _Bool _selectedToEdit;
    _Bool _editing;
    _Bool _showSoldout;
    UIImageView *_goodImageView;
    UILabel *_titleLabel;
    UILabel *_currentPriceLabel;
    UILabel *_originalPriceLabel;
    UILabel *_customTagLabel;
    UIView *_customTagBG;
    UIImageView *_tmall_icon;
    UIImageView *_taobao_icon;
    IMYRoundButton *_rightTagButton;
    UIButton *_deleteButton;
    IMYYBCountDownView *_countDownView;
    UILabel *_priceLabel;
    UIImageView *_coinImageView;
    CDUnknownBlockType _selectBlock;
    IMYYBSessionDetailModel *_model;
}

+ (struct CGSize)cellSize;
+ (id)imy_loadFromXIB;
+ (void)load;
@property(retain, nonatomic) IMYYBSessionDetailModel *model; // @synthesize model=_model;
@property(nonatomic) _Bool showSoldout; // @synthesize showSoldout=_showSoldout;
@property(copy, nonatomic) CDUnknownBlockType selectBlock; // @synthesize selectBlock=_selectBlock;
@property(nonatomic) _Bool editing; // @synthesize editing=_editing;
@property(nonatomic) _Bool selectedToEdit; // @synthesize selectedToEdit=_selectedToEdit;
@property(nonatomic) _Bool soldOut; // @synthesize soldOut=_soldOut;
@property(nonatomic) __weak UIImageView *coinImageView; // @synthesize coinImageView=_coinImageView;
@property(retain, nonatomic) UILabel *priceLabel; // @synthesize priceLabel=_priceLabel;
@property(nonatomic) __weak IMYYBCountDownView *countDownView; // @synthesize countDownView=_countDownView;
@property(nonatomic) __weak UIButton *deleteButton; // @synthesize deleteButton=_deleteButton;
@property(nonatomic) __weak IMYRoundButton *rightTagButton; // @synthesize rightTagButton=_rightTagButton;
@property(nonatomic) __weak UIImageView *taobao_icon; // @synthesize taobao_icon=_taobao_icon;
@property(nonatomic) __weak UIImageView *tmall_icon; // @synthesize tmall_icon=_tmall_icon;
@property(nonatomic) __weak UIView *customTagBG; // @synthesize customTagBG=_customTagBG;
@property(nonatomic) __weak UILabel *customTagLabel; // @synthesize customTagLabel=_customTagLabel;
@property(retain, nonatomic) UILabel *originalPriceLabel; // @synthesize originalPriceLabel=_originalPriceLabel;
@property(retain, nonatomic) UILabel *currentPriceLabel; // @synthesize currentPriceLabel=_currentPriceLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *goodImageView; // @synthesize goodImageView=_goodImageView;
- (void).cxx_destruct;
- (void)setTimer:(id)arg1;
- (void)setStock:(id)arg1;
- (void)setPrice:(id)arg1;
- (void)setRightTag:(id)arg1;
- (void)setTitle:(id)arg1;
- (void)layoutWithModel:(id)arg1;
- (void)awakeFromNib;
- (void)dealloc;
- (void)prepareForInit;
- (void)prepareForReuse;

@end

