//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface IMYYoubiTryReportViewModel : NSObject
{
}

+ (void)commitTryReportWithQuestion:(id)arg1 pid:(long long)arg2 aid:(long long)arg3 pic:(id)arg4 WithSuccess:(CDUnknownBlockType)arg5 fail:(CDUnknownBlockType)arg6;
+ (void)requstTryReportWithProductId:(long long)arg1 Aid:(long long)arg2 WithSuccess:(CDUnknownBlockType)arg3 fail:(CDUnknownBlockType)arg4;

@end

