//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSMutableArray, NSString, UINavigationController, UIViewController;

@interface LKAppManager : NSObject
{
    _Bool isIOS5After;
    _Bool isIphone5;
    _Bool _isGetUserAddressSuccess;
    _Bool _isMySyncmlRemindNumber;
    _Bool _isLoginAndRegist;
    _Bool _isShowYoubiSign;
    _Bool _isShowYoubiSignTab;
    _Bool _bRefreshHaoYunZhi;
    _Bool _bUserChangeModelShowShare;
    _Bool _isShowHospitalPrompt;
    int _defaultAnimationType;
    int _sizeType;
    UIViewController *_rootViewControoler;
    NSMutableArray *_allCollectTipsID;
    NSString *_avatarURL;
    NSString *_curSinaUid;
    NSString *_youbiCenterText;
    long long _youbiCount;
    long long _findTimes;
    NSMutableArray *_showsnavigations;
}

+ (void)removeViewControllerInNavigationForVC:(id)arg1;
+ (void)youbiShareSuccessPostService;
+ (void)getUserAddress:(CDUnknownBlockType)arg1;
+ (_Bool)shouldAlertInviteReview;
+ (id)sharedAppManager;
+ (struct CGRect)getFullViewController;
+ (struct CGRect)getFullWindow;
@property(retain, nonatomic) NSMutableArray *showsnavigations; // @synthesize showsnavigations=_showsnavigations;
@property(nonatomic) _Bool isShowHospitalPrompt; // @synthesize isShowHospitalPrompt=_isShowHospitalPrompt;
@property(nonatomic) long long findTimes; // @synthesize findTimes=_findTimes;
@property(nonatomic) _Bool bUserChangeModelShowShare; // @synthesize bUserChangeModelShowShare=_bUserChangeModelShowShare;
@property(nonatomic) _Bool bRefreshHaoYunZhi; // @synthesize bRefreshHaoYunZhi=_bRefreshHaoYunZhi;
@property(nonatomic) long long youbiCount; // @synthesize youbiCount=_youbiCount;
@property(nonatomic) _Bool isShowYoubiSignTab; // @synthesize isShowYoubiSignTab=_isShowYoubiSignTab;
@property(nonatomic) _Bool isShowYoubiSign; // @synthesize isShowYoubiSign=_isShowYoubiSign;
@property(retain, nonatomic) NSString *youbiCenterText; // @synthesize youbiCenterText=_youbiCenterText;
@property(retain, nonatomic) NSString *curSinaUid; // @synthesize curSinaUid=_curSinaUid;
@property(retain, nonatomic) NSString *avatarURL; // @synthesize avatarURL=_avatarURL;
@property(nonatomic) _Bool isLoginAndRegist; // @synthesize isLoginAndRegist=_isLoginAndRegist;
@property(nonatomic) _Bool isMySyncmlRemindNumber; // @synthesize isMySyncmlRemindNumber=_isMySyncmlRemindNumber;
@property(readonly) int sizeType; // @synthesize sizeType=_sizeType;
@property(nonatomic) _Bool isGetUserAddressSuccess; // @synthesize isGetUserAddressSuccess=_isGetUserAddressSuccess;
@property(retain, nonatomic) NSMutableArray *allCollectTipsID; // @synthesize allCollectTipsID=_allCollectTipsID;
@property int defaultAnimationType; // @synthesize defaultAnimationType=_defaultAnimationType;
@property(nonatomic) __weak UIViewController *rootViewControoler; // @synthesize rootViewControoler=_rootViewControoler;
@property(readonly) _Bool isIphone5; // @synthesize isIphone5;
@property(readonly) _Bool isIOS5After; // @synthesize isIOS5After;
- (void).cxx_destruct;
- (void)getUserAddress:(CDUnknownBlockType)arg1;
- (void)startGetUserAddress;
- (void)dealloc;
@property(readonly) NSDate *lastAppStartDate;
- (void)popViewControllerAnimation:(int)arg1;
- (void)popToViewController:(id)arg1 Animation:(int)arg2;
- (void)popToForwardCount:(int)arg1 Animation:(int)arg2;
- (void)popViewController:(CDUnknownBlockType)arg1 Animation:(int)arg2;
- (void)popViewController;
- (void)popToRootControllerAnimation:(int)arg1;
- (void)popToRootController;
- (void)popToControllerClass:(Class)arg1;
- (void)pushViewController:(id)arg1 animation:(int)arg2;
- (void)pushViewController:(id)arg1 anim:(_Bool)arg2;
- (void)pushViewController:(id)arg1;
- (id)pushControllerClass:(Class)arg1;
- (void)exitController;
- (void)runBlockInRootIsTabbar:(CDUnknownBlockType)arg1 forKey:(id)arg2;
- (void)runBlockInRootIsTabbar:(CDUnknownBlockType)arg1;
- (id)switchForType:(id)arg1;
- (void)loginSuccess;
- (id)init;
@property(readonly) UIViewController *currentController;
- (id)searchNavigation:(id)arg1;
@property(readonly) UINavigationController *navigation;
@property(readonly) _Bool networkEnable;
@property(readonly) _Bool is2G_3G;
@property(readonly) _Bool isWifi;
- (void)refreshCollectID;
- (void)addFavID:(int)arg1;
- (void)removeFavID:(int)arg1;

@end

