//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSDate.h>

@interface NSDate (SYModel)
+ (id)toDay;
+ (id)shareCNCalendar;
- (id)dateBy_SY_AddingTimeInterval:(long long)arg1;
- (id)secondToZero;
- (id)todayWithHourAndMinute;
- (id)getWeekString2;
- (id)getWeekString;
- (id)getMMddString;
- (id)getNongliMD;
- (id)getCNDateString;
- (id)getUTCDateString;
- (id)getOnlyDateString1;
- (id)getOnlyDateString;
- (id)getDateTimeString;
- (id)getDateAndHourMinutesString;
- (id)getDateString;
- (long long)getDayCountAfterWithYear:(long long)arg1 month:(long long)arg2 day:(long long)arg3;
- (id)getDiff:(id)arg1 calendarUnit:(unsigned long long)arg2;
- (id)getYearMonthAndDayDiff:(id)arg1;
- (id)getMonthAndDayDiff:(id)arg1;
- (long long)getMonthDiff:(id)arg1;
- (long long)imy_getDayDiff:(id)arg1;
- (long long)getDayDiff:(id)arg1;
- (id)getAfterMonthOneDay;
- (id)getForwardMonthOneDay;
- (id)getAfterWithDay:(long long)arg1;
- (id)getAfterWithMonth:(long long)arg1;
- (id)getYMDate;
- (id)getDate;
- (id)stringWithTimeDateFormatter;
- (long long)compare_day:(id)arg1;
- (void)dateChangedListender;
@end

