//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIImageView, UILabel;

@interface SYBusinessMessageTimeCell : UITableViewCell
{
    UIImageView *_timeView;
    UILabel *_timeLabel;
}

+ (double)timeCellHeight;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UIImageView *timeView; // @synthesize timeView=_timeView;
- (void).cxx_destruct;
- (void)setTime:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

