//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IMYBaseTableViewCell.h"

@class IMYRecommendCardModel, SYHomeCardImageView, SYHomeCardYesNoButton, UILabel;
@protocol IMYNewsRecordToolCardViewModel;

@interface SYHomeCardCell : IMYBaseTableViewCell
{
    _Bool _isYes;
    _Bool _fold;
    SYHomeCardYesNoButton *_yesNoButton;
    SYHomeCardImageView *_imageViews;
    long long _img_type;
    long long _switchType;
    UILabel *_titleLabel;
    id <IMYNewsRecordToolCardViewModel> _viewModel;
    IMYRecommendCardModel *_model;
}

+ (double)cellHeight:(_Bool)arg1 imgType:(unsigned long long)arg2;
@property(nonatomic) _Bool fold; // @synthesize fold=_fold;
@property(retain, nonatomic) IMYRecommendCardModel *model; // @synthesize model=_model;
@property(retain, nonatomic) id <IMYNewsRecordToolCardViewModel> viewModel; // @synthesize viewModel=_viewModel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) long long switchType; // @synthesize switchType=_switchType;
@property(nonatomic) _Bool isYes; // @synthesize isYes=_isYes;
@property(nonatomic) long long img_type; // @synthesize img_type=_img_type;
@property(retain, nonatomic) SYHomeCardImageView *imageViews; // @synthesize imageViews=_imageViews;
@property(retain, nonatomic) SYHomeCardYesNoButton *yesNoButton; // @synthesize yesNoButton=_yesNoButton;
- (void).cxx_destruct;
- (void)foldAnimation:(_Bool)arg1;
- (void)updateUIWithModel:(id)arg1 animate:(_Bool)arg2;
- (void)setCellModel:(id)arg1;
- (void)prepareForReuse;
- (void)initViews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

