//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SYLocalNotificationManager : NSObject
{
    _Bool _hasShowNoPushAlertView;
    int _userModeType;
    long long _minutesOffset;
}

+ (void)reqLocalMessgeEventTrack:(long long)arg1 type:(long long)arg2 pushDate:(id)arg3 pushFlag:(long long)arg4;
+ (void)clearApplicationIconBadgeNumber;
+ (void)showLocalNotice:(unsigned long long)arg1;
+ (void)fireOvulateDateWithClockDate:(id)arg1 handler:(CDUnknownBlockType)arg2;
+ (id)fireOvulateDateWithClockTime:(id)arg1;
+ (void)checkSystemNotificationState;
+ (id)shareManager;
@property(nonatomic) int userModeType; // @synthesize userModeType=_userModeType;
@property(nonatomic) _Bool hasShowNoPushAlertView; // @synthesize hasShowNoPushAlertView=_hasShowNoPushAlertView;
@property(readonly, nonatomic) long long minutesOffset; // @synthesize minutesOffset=_minutesOffset;
- (void)localPushWithFireDate:(id)arg1 text:(id)arg2 key:(id)arg3 repeatInterval:(unsigned long long)arg4 userInfo:(id)arg5;
- (void)showLocalNoticeNotification:(id)arg1;
- (void)showAlertViewWithNotication:(id)arg1;
@property(readonly, nonatomic) _Bool hasPregnantForLongTime;
- (void)handleReceiveLocalNotification:(id)arg1;
- (void)didReceiveLocalNotification:(id)arg1 fromLaunch:(_Bool)arg2;
- (void)didFinishLaunchingWithOptions:(id)arg1;
- (void)cancelAllNativePush;
- (void)updateAllNotifications;
- (id)notificationWithType:(unsigned long long)arg1;
- (id)getDefaultNotifications;
- (id)getNotificationsWithUserMode;
- (id)getAllNotifications;
- (void)resetNotifications;
- (void)checkDatabase;
- (id)init;

@end

