//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface SYMensesInfoModel : NSObject
{
    long long _parsMensesDay;
    long long _parsInterval;
    NSString *_lastTimeMenses;
}

@property(copy, nonatomic) NSString *lastTimeMenses; // @synthesize lastTimeMenses=_lastTimeMenses;
@property(nonatomic) long long parsInterval; // @synthesize parsInterval=_parsInterval;
@property(nonatomic) long long parsMensesDay; // @synthesize parsMensesDay=_parsMensesDay;
- (void).cxx_destruct;

@end

