//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SYBaseViewController.h"

@class SYSelectAllCellView, UITableView;
@protocol SYMsgVCEditDelegate;

@interface SYMsgBaseVC : SYBaseViewController
{
    _Bool _isEdit;
    SYSelectAllCellView *_v_bottom;
    UITableView *_tableView;
    id <SYMsgVCEditDelegate> _delegate;
}

@property(nonatomic) __weak id <SYMsgVCEditDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) _Bool isEdit; // @synthesize isEdit=_isEdit;
@property(retain, nonatomic) SYSelectAllCellView *v_bottom; // @synthesize v_bottom=_v_bottom;
- (void).cxx_destruct;
- (void)setReadAllButtonHide:(_Bool)arg1;
- (void)editTableView:(_Bool)arg1;
- (void)setEditBtn:(_Bool)arg1;
- (void)setupBottomView;
- (void)setupTopRightButton;
- (void)setupTableView;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

