//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface SYMyNotifyTodayTipModel : NSObject
{
    int _userMode;
    long long _notifyid;
    long long _topicId;
    NSString *_topicTitle;
    NSString *_notifyWords;
    NSString *_topicURL;
    NSString *_topicImage;
    long long _periodDay;
    long long _periodType;
}

+ (id)getPrimaryKey;
+ (id)getTableName;
+ (id)getUsingLKDBHelper;
@property(nonatomic) long long periodType; // @synthesize periodType=_periodType;
@property(nonatomic) int userMode; // @synthesize userMode=_userMode;
@property(nonatomic) long long periodDay; // @synthesize periodDay=_periodDay;
@property(copy, nonatomic) NSString *topicImage; // @synthesize topicImage=_topicImage;
@property(copy, nonatomic) NSString *topicURL; // @synthesize topicURL=_topicURL;
@property(copy, nonatomic) NSString *notifyWords; // @synthesize notifyWords=_notifyWords;
@property(copy, nonatomic) NSString *topicTitle; // @synthesize topicTitle=_topicTitle;
@property(nonatomic) long long topicId; // @synthesize topicId=_topicId;
@property(nonatomic) long long notifyid; // @synthesize notifyid=_notifyid;
- (void).cxx_destruct;

@end

