//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSDictionary, NSMutableArray, RACSignal;

@interface SYMyNotifyViewModel : NSObject
{
    RACSignal *_updatedContentSignal;
    NSMutableArray *_datalist;
    double _ovulateFireTime;
    NSDictionary *_iconDictionary;
    long long _minutesOffset;
    NSDate *_latestVaccineDate;
    NSDate *_latestGravidityDate;
}

+ (void)reqMessgeEventTrack;
+ (id)modelTypeToEventTrcak:(long long)arg1;
@property(retain, nonatomic) NSDate *latestGravidityDate; // @synthesize latestGravidityDate=_latestGravidityDate;
@property(retain, nonatomic) NSDate *latestVaccineDate; // @synthesize latestVaccineDate=_latestVaccineDate;
@property(nonatomic) long long minutesOffset; // @synthesize minutesOffset=_minutesOffset;
@property(retain, nonatomic) NSDictionary *iconDictionary; // @synthesize iconDictionary=_iconDictionary;
@property(nonatomic) double ovulateFireTime; // @synthesize ovulateFireTime=_ovulateFireTime;
@property(retain, nonatomic) NSMutableArray *datalist; // @synthesize datalist=_datalist;
@property(readonly, nonatomic) RACSignal *updatedContentSignal; // @synthesize updatedContentSignal=_updatedContentSignal;
- (void).cxx_destruct;
- (void)checkFireTimeOfChanJian;
- (void)checkFireTimeOfBaoBaoYiMiao;
- (void)checkFireTimeOfOvulate;
- (id)selectArrayAtIndexPath:(id)arg1;
- (_Bool)willHideArrowAtIndexPath:(id)arg1;
- (id)dateWtihHour:(id)arg1 min:(id)arg2;
- (void)pickerSelectedArray:(id)arg1 indexPath:(id)arg2;
- (id)pickerDataSourceAtIndexPath:(id)arg1;
- (id)uriAtIndexPath:(id)arg1;
- (_Bool)setSwitchActive:(_Bool)arg1 atIndexPath:(id)arg2;
- (_Bool)isActiveAtIndexPath:(id)arg1;
- (id)fireTimeAtIndexPath:(id)arg1;
- (id)remainTimeAtIndexPath:(id)arg1;
- (id)nameStringAtIndexPath:(id)arg1;
- (id)imageStringAtIndexPath:(id)arg1;
- (unsigned long long)numberOfRowsInSection:(unsigned long long)arg1;
- (void)updateAllNotifications;
- (void)initData;
- (id)init;
- (void)dealloc;

@end

