//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface SYUserModeInputCellModel : NSObject
{
    _Bool _isExpend;
    _Bool _isLastCell;
    _Bool _isPregnant;
    NSString *_title;
    NSString *_content;
    unsigned long long _cellType;
    unsigned long long _type;
    double _cellHeight;
    long long _row;
    CDUnknownBlockType _onTextFieldCreated;
    CDUnknownBlockType _onTextFieldBeginEditing;
    CDUnknownBlockType _onCellPressed;
}

+ (id)modelWithTitle:(id)arg1 content:(id)arg2;
@property(copy, nonatomic) CDUnknownBlockType onCellPressed; // @synthesize onCellPressed=_onCellPressed;
@property(copy, nonatomic) CDUnknownBlockType onTextFieldBeginEditing; // @synthesize onTextFieldBeginEditing=_onTextFieldBeginEditing;
@property(copy, nonatomic) CDUnknownBlockType onTextFieldCreated; // @synthesize onTextFieldCreated=_onTextFieldCreated;
@property(nonatomic) _Bool isPregnant; // @synthesize isPregnant=_isPregnant;
@property(nonatomic) _Bool isLastCell; // @synthesize isLastCell=_isLastCell;
@property(nonatomic) long long row; // @synthesize row=_row;
@property(nonatomic) double cellHeight; // @synthesize cellHeight=_cellHeight;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(nonatomic) unsigned long long cellType; // @synthesize cellType=_cellType;
@property(nonatomic) _Bool isExpend; // @synthesize isExpend=_isExpend;
@property(retain, nonatomic) NSString *content; // @synthesize content=_content;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)initWithTitle:(id)arg1 content:(id)arg2;

@end

