//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GCDQueue.h"

@class RACScheduler;

@interface TCPQueue : GCDQueue
{
    RACScheduler *_scheduler;
}

+ (id)tcpScheduler;
+ (id)sharedTCPQueue;
@property(retain, nonatomic) RACScheduler *scheduler; // @synthesize scheduler=_scheduler;
- (void).cxx_destruct;
- (void)queueBlock:(CDUnknownBlockType)arg1;
- (id)initWithDispatchQueue:(id)arg1;

@end

