//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "YYJSONHelperProtocol-Protocol.h"

@class NSArray, NSString, TTQPublisherModel;
@protocol TTQCommentModel;

@interface TTQCommentModel : NSObject <YYJSONHelperProtocol>
{
    _Bool hasCheckUseNormalLabel;
    NSString *_removeUrlString;
    _Bool _is_deleted;
    _Bool _has_praise;
    _Bool _is_hot;
    _Bool _useThird;
    _Bool _isUserAdded;
    unsigned long long _cellHeight;
    long long _topic_id;
    NSString *_content;
    long long _privilege;
    long long _commentID;
    NSArray *_images;
    NSString *_updated_date;
    NSArray<TTQCommentModel> *_referenceds;
    TTQPublisherModel *_publisher;
    long long _floor_no;
    TTQPublisherModel *_replygoal;
    long long _referenced_num;
    long long _praise_num;
    NSString *_appoint;
}

+ (_Bool)YYSuper;
+ (id)getTableName;
+ (id)getUsingLKDBHelper;
+ (id)getPrimaryKey;
+ (_Bool)dbWillInsert:(id)arg1;
+ (void)initialize;
@property(nonatomic) _Bool isUserAdded; // @synthesize isUserAdded=_isUserAdded;
@property(nonatomic) _Bool useThird; // @synthesize useThird=_useThird;
@property(copy, nonatomic) NSString *appoint; // @synthesize appoint=_appoint;
@property(nonatomic) _Bool is_hot; // @synthesize is_hot=_is_hot;
@property(nonatomic) _Bool has_praise; // @synthesize has_praise=_has_praise;
@property(nonatomic) long long praise_num; // @synthesize praise_num=_praise_num;
@property(nonatomic) long long referenced_num; // @synthesize referenced_num=_referenced_num;
@property(retain, nonatomic) TTQPublisherModel *replygoal; // @synthesize replygoal=_replygoal;
@property(nonatomic) long long floor_no; // @synthesize floor_no=_floor_no;
@property(retain, nonatomic) TTQPublisherModel *publisher; // @synthesize publisher=_publisher;
@property(retain, nonatomic) NSArray<TTQCommentModel> *referenceds; // @synthesize referenceds=_referenceds;
@property(nonatomic) _Bool is_deleted; // @synthesize is_deleted=_is_deleted;
@property(copy, nonatomic) NSString *updated_date; // @synthesize updated_date=_updated_date;
@property(copy, nonatomic) NSArray *images; // @synthesize images=_images;
@property(nonatomic) long long commentID; // @synthesize commentID=_commentID;
@property(nonatomic) long long privilege; // @synthesize privilege=_privilege;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
@property(nonatomic) long long topic_id; // @synthesize topic_id=_topic_id;
@property(nonatomic) unsigned long long cellHeight; // @synthesize cellHeight=_cellHeight;
- (void).cxx_destruct;
- (id)removeUrlString;

@end

