//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class IMYAvatarImageView, UILabel;

@interface TTQForumBroadcastInfoView : UIView
{
    IMYAvatarImageView *_iconImageView;
    UILabel *_name;
    UILabel *_introuduce;
}

@property(retain, nonatomic) UILabel *introuduce; // @synthesize introuduce=_introuduce;
@property(retain, nonatomic) UILabel *name; // @synthesize name=_name;
@property(retain, nonatomic) IMYAvatarImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
- (void).cxx_destruct;
- (void)bindModel:(id)arg1;

@end

