//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class TTQForumButton;

@interface TTQHome5ForumsView : UIView
{
    CDUnknownBlockType _onActionBlock;
    CDUnknownBlockType _forumsShowBlock;
    TTQForumButton *_addForumButton;
}

@property(retain, nonatomic) TTQForumButton *addForumButton; // @synthesize addForumButton=_addForumButton;
@property(copy, nonatomic) CDUnknownBlockType forumsShowBlock; // @synthesize forumsShowBlock=_forumsShowBlock;
@property(copy, nonatomic) CDUnknownBlockType onActionBlock; // @synthesize onActionBlock=_onActionBlock;
- (void).cxx_destruct;
- (void)biForHead:(long long)arg1 action:(long long)arg2 position:(long long)arg3 redirect_url:(id)arg4;
- (id)getAddForumImage:(struct CGSize)arg1;
- (void)onActionWith:(id)arg1;
- (double)setWith:(id)arg1;

@end

