//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TTQEditDelViewModel.h"

@class NSMutableArray;

@interface TTQMyCollectViewModel : TTQEditDelViewModel
{
    long long _myCollectType;
    NSMutableArray *_historyStatistics;
    long long _showFloor;
}

+ (id)allCellReuseIdentifier;
@property(nonatomic) long long showFloor; // @synthesize showFloor=_showFloor;
@property(retain, nonatomic) NSMutableArray *historyStatistics; // @synthesize historyStatistics=_historyStatistics;
@property(nonatomic) long long myCollectType; // @synthesize myCollectType=_myCollectType;
- (void).cxx_destruct;
- (id)convertStandardHistoryData:(id)arg1;
- (id)httpBuilderForNextPage:(_Bool)arg1 andInput:(id)arg2;
- (id)requestRemoteDataForType:(long long)arg1 params:(id)arg2;
- (void)updateAllSelState:(_Bool)arg1;
- (id)identifierRowAtIndexPath:(id)arg1;
- (void)checkHistoryDayStateAfterSelectAtIndexPath:(id)arg1;
- (void)checkHistoryDayStateAfterSelectAtSection:(long long)arg1;
- (_Bool)deleteCollectTopic:(long long)arg1;
- (void)markTopicDeleteAtIndexPath:(id)arg1;
- (void)deleteHistoryData:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)deleteCollectData:(CDUnknownBlockType)arg1;
- (_Bool)hasDeleteData;
- (id)init;

@end

