//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TTQTableViewCell.h"

#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UITextViewDelegate-Protocol.h"

@class NSIndexPath, NSString, SZTextView, TTQPublishTextModel, UITableView, UITapGestureRecognizer;
@protocol TTQPublishTextEditDelegate;

@interface TTQPublishTextCell : TTQTableViewCell <UIGestureRecognizerDelegate, UITextViewDelegate>
{
    _Bool _isEditing;
    id <TTQPublishTextEditDelegate> _delegate;
    SZTextView *_textView;
    TTQPublishTextModel *_textModel;
    UITableView *_containerTable;
    NSIndexPath *_indexPath;
    UITapGestureRecognizer *_textViewTapGesture;
    long long _editTime;
}

@property(nonatomic) long long editTime; // @synthesize editTime=_editTime;
@property(retain, nonatomic) UITapGestureRecognizer *textViewTapGesture; // @synthesize textViewTapGesture=_textViewTapGesture;
@property(retain, nonatomic) NSIndexPath *indexPath; // @synthesize indexPath=_indexPath;
@property(retain, nonatomic) UITableView *containerTable; // @synthesize containerTable=_containerTable;
@property(nonatomic) _Bool isEditing; // @synthesize isEditing=_isEditing;
@property(retain, nonatomic) TTQPublishTextModel *textModel; // @synthesize textModel=_textModel;
@property(retain, nonatomic) SZTextView *textView; // @synthesize textView=_textView;
@property(nonatomic) __weak id <TTQPublishTextEditDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)textViewDidChangeSelection:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidEndEditing:(id)arg1;
- (_Bool)textViewShouldEndEditing:(id)arg1;
- (void)textViewDidBeginEditing:(id)arg1;
- (_Bool)textViewShouldBeginEditing:(id)arg1;
- (void)textViewDidChange:(id)arg1;
- (void)textViewDidChangeForNoOverflow;
- (void)computerTextH;
- (void)handlePlaceholder;
- (_Bool)rectVisible:(struct CGRect)arg1;
- (void)scrollToCursorForTextView:(id)arg1;
- (id)splitedTextArrWithPreFlag:(_Bool *)arg1 postFlag:(_Bool *)arg2;
@property(nonatomic) struct _NSRange selectedRange;
- (_Bool)isFirstResponder;
- (_Bool)resignFirstResponder;
- (_Bool)becomeFirstResponder;
- (void)updateWith:(id)arg1 indexPath:(id)arg2;
- (void)didTapTextView;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)commonInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

