//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class UIColor, UIFont;

@interface TTQPopMenuConfiguration : NSObject
{
    double _arrowMargin;
    double _menuMargin;
    double _arrowCornerRadius;
    double _menuCornerRadius;
    double _menuTitleMargin;
    double _menuIconMargin;
    double _menuIconSize;
    double _menuRowHeight;
    double _menuWidth;
    UIColor *_destructiveTextColor;
    UIColor *_textColor;
    UIColor *_tintColor;
    UIColor *_borderColor;
    double _borderWidth;
    UIFont *_textFont;
    UIFont *_destructiveTextFont;
    long long _destructiveTag;
    long long _alignment;
    double _animationDuration;
    struct UIEdgeInsets _separatorInset;
}

+ (id)defaultConfiguration;
@property(nonatomic) double animationDuration; // @synthesize animationDuration=_animationDuration;
@property(nonatomic) long long alignment; // @synthesize alignment=_alignment;
@property(nonatomic) long long destructiveTag; // @synthesize destructiveTag=_destructiveTag;
@property(retain, nonatomic) UIFont *destructiveTextFont; // @synthesize destructiveTextFont=_destructiveTextFont;
@property(retain, nonatomic) UIFont *textFont; // @synthesize textFont=_textFont;
@property(nonatomic) double borderWidth; // @synthesize borderWidth=_borderWidth;
@property(retain, nonatomic) UIColor *borderColor; // @synthesize borderColor=_borderColor;
@property(retain, nonatomic) UIColor *tintColor; // @synthesize tintColor=_tintColor;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
@property(retain, nonatomic) UIColor *destructiveTextColor; // @synthesize destructiveTextColor=_destructiveTextColor;
@property(nonatomic) double menuWidth; // @synthesize menuWidth=_menuWidth;
@property(nonatomic) double menuRowHeight; // @synthesize menuRowHeight=_menuRowHeight;
@property(nonatomic) double menuIconSize; // @synthesize menuIconSize=_menuIconSize;
@property(nonatomic) double menuIconMargin; // @synthesize menuIconMargin=_menuIconMargin;
@property(nonatomic) double menuTitleMargin; // @synthesize menuTitleMargin=_menuTitleMargin;
@property(nonatomic) double menuCornerRadius; // @synthesize menuCornerRadius=_menuCornerRadius;
@property(nonatomic) double arrowCornerRadius; // @synthesize arrowCornerRadius=_arrowCornerRadius;
@property(nonatomic) double menuMargin; // @synthesize menuMargin=_menuMargin;
@property(nonatomic) double arrowMargin; // @synthesize arrowMargin=_arrowMargin;
@property(nonatomic) struct UIEdgeInsets separatorInset; // @synthesize separatorInset=_separatorInset;
- (void).cxx_destruct;

@end

