//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@interface UIButton (IMYTheme)
- (void)imy_setTitleColorForKey:(id)arg1 andState:(unsigned long long)arg2;
- (void)imy_setBackgroudImageForKey:(id)arg1 stretchableImageWithLeftCapWidth:(long long)arg2 topCapHeight:(long long)arg3 forState:(unsigned long long)arg4;
- (void)imy_setCenterResiseBackgroudImageForKey:(id)arg1 andState:(unsigned long long)arg2;
- (void)imy_setBackgroundImageForKey:(id)arg1 andState:(unsigned long long)arg2;
- (void)imy_setCenterResizeImageForKey:(id)arg1 andState:(unsigned long long)arg2;
- (void)imy_setImageForKey:(id)arg1 andState:(unsigned long long)arg2 stretchableImageWithLeftCapWidth:(long long)arg3 topCapHeight:(long long)arg4;
- (void)imy_setImageForKey:(id)arg1 andState:(unsigned long long)arg2;
@end

