//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImage.h>

@interface UIImage (ForceDecode)
+ (struct CGImage *)sd_imageCreateDecodedCopy:(struct CGImage *)arg1 antialiasing:(_Bool)arg2;
+ (id)sd_decodedImageWithImage:(id)arg1 antialiasing:(_Bool)arg2;
+ (_Bool)sd_shouldDecodedImageWithCGImage:(struct CGImage *)arg1;
+ (id)decodedImageWithImage:(id)arg1;
@property(nonatomic) _Bool isDecodedForDisplay;
@end

