//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UILabel;

@interface YBBHomeGlobalSearchTopicCell : UITableViewCell
{
    UILabel *_nameLabel;
    UILabel *_contentLabel;
    UILabel *_sourceLabel;
    UILabel *_timeLabel;
    UILabel *_commentLabel;
    UILabel *_forumIconLabel;
    UILabel *_commIconLabel;
}

@property(nonatomic) __weak UILabel *commIconLabel; // @synthesize commIconLabel=_commIconLabel;
@property(nonatomic) __weak UILabel *forumIconLabel; // @synthesize forumIconLabel=_forumIconLabel;
@property(nonatomic) __weak UILabel *commentLabel; // @synthesize commentLabel=_commentLabel;
@property(nonatomic) __weak UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(nonatomic) __weak UILabel *sourceLabel; // @synthesize sourceLabel=_sourceLabel;
@property(nonatomic) __weak UILabel *contentLabel; // @synthesize contentLabel=_contentLabel;
@property(nonatomic) __weak UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
- (void).cxx_destruct;
- (void)awakeFromNib;

@end

