//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "YBBTipModel.h"

@class NSString;

@interface YBBHomeGlobalSearchTipModel : YBBTipModel
{
    long long _mid;
    long long _category;
    NSString *_title;
    NSString *_introduction;
    NSString *_thumbnails;
    NSString *_url;
}

@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(copy, nonatomic) NSString *thumbnails; // @synthesize thumbnails=_thumbnails;
@property(copy, nonatomic) NSString *introduction; // @synthesize introduction=_introduction;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) long long category; // @synthesize category=_category;
@property(nonatomic) long long mid; // @synthesize mid=_mid;
- (void).cxx_destruct;

@end

