//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface YBBHomeFlipView : UIView
{
    _Bool displayingPrimary;
    float spinTime;
    UIView *_frontView;
    UIView *_backView;
}

@property float spinTime; // @synthesize spinTime;
@property(retain, nonatomic) UIView *backView; // @synthesize backView=_backView;
@property(retain, nonatomic) UIView *frontView; // @synthesize frontView=_frontView;
- (void).cxx_destruct;
- (void)flipTouched:(id)arg1;
- (id)initWithFrontView:(id)arg1 andBackView:(id)arg2 inFrame:(struct CGRect)arg3;
- (id)initWithCoder:(id)arg1;

@end

