//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, UILabel;

@interface YBBHomeMotherChangeHeader : UIView
{
    UILabel *_contentLabel;
    UIImageView *_iconView;
}

@property(nonatomic) __weak UIImageView *iconView; // @synthesize iconView=_iconView;
@property(nonatomic) __weak UILabel *contentLabel; // @synthesize contentLabel=_contentLabel;
- (void).cxx_destruct;
- (void)setURL:(id)arg1 content:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

