//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "YBBOldHomeModel-Protocol.h"

@class NSArray, NSDate, NSString;
@protocol YBBOldTodayTicDetailItem;

@interface YBBOldHomeTodayTicModel : NSObject <YBBOldHomeModel>
{
    _Bool _isDefault;
    _Bool _is_finish;
    _Bool _isPrefetched;
    _Bool _didTrack;
    long long _m_id;
    NSString *_title;
    NSString *_introduction;
    NSString *_thumbnails;
    NSString *_img;
    long long _category_id;
    NSString *_category;
    NSString *_icon;
    NSString *_url;
    NSDate *_updated_date;
    long long _forum_id;
    long long _topic_id;
    long long _tsc_id;
    NSString *_tsc_name;
    NSString *_categoryName;
    NSArray<YBBOldTodayTicDetailItem> *_detail;
    long long _type;
}

+ (void)initialize;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(retain, nonatomic) NSArray<YBBOldTodayTicDetailItem> *detail; // @synthesize detail=_detail;
@property(nonatomic) _Bool didTrack; // @synthesize didTrack=_didTrack;
@property(nonatomic) _Bool isPrefetched; // @synthesize isPrefetched=_isPrefetched;
@property(copy, nonatomic) NSString *categoryName; // @synthesize categoryName=_categoryName;
@property(copy, nonatomic) NSString *tsc_name; // @synthesize tsc_name=_tsc_name;
@property(nonatomic) long long tsc_id; // @synthesize tsc_id=_tsc_id;
@property(nonatomic) _Bool is_finish; // @synthesize is_finish=_is_finish;
@property(nonatomic) long long topic_id; // @synthesize topic_id=_topic_id;
@property(nonatomic) long long forum_id; // @synthesize forum_id=_forum_id;
@property(retain, nonatomic) NSDate *updated_date; // @synthesize updated_date=_updated_date;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(copy, nonatomic) NSString *icon; // @synthesize icon=_icon;
@property(copy, nonatomic) NSString *category; // @synthesize category=_category;
@property(nonatomic) long long category_id; // @synthesize category_id=_category_id;
@property(copy, nonatomic) NSString *img; // @synthesize img=_img;
@property(copy, nonatomic) NSString *thumbnails; // @synthesize thumbnails=_thumbnails;
@property(copy, nonatomic) NSString *introduction; // @synthesize introduction=_introduction;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) long long m_id; // @synthesize m_id=_m_id;
@property(nonatomic) _Bool isDefault; // @synthesize isDefault=_isDefault;
- (void).cxx_destruct;
- (void)prefetchDetailContentData;
- (id)targetWithContext:(id)arg1;
@property(nonatomic) double rowHeight;
@property(copy, nonatomic) NSString *cellClass;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

