//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class IMYButton, NSLayoutConstraint, UIImageView, UILabel, YBBOldHomeTLPhotoListModel;

@interface YBBOldHomeTLUpdatePhotoCell : UITableViewCell
{
    NSLayoutConstraint *_titleHeighContraint;
    UILabel *_title;
    IMYButton *_uploadBtn;
    UIImageView *_imgView;
    YBBOldHomeTLPhotoListModel *_model;
    CDUnknownBlockType _uploadActionBlock;
    CDUnknownBlockType _titleTapActionBlock;
    CDUnknownBlockType _imgViewTapActionBlock;
}

@property(copy, nonatomic) CDUnknownBlockType imgViewTapActionBlock; // @synthesize imgViewTapActionBlock=_imgViewTapActionBlock;
@property(copy, nonatomic) CDUnknownBlockType titleTapActionBlock; // @synthesize titleTapActionBlock=_titleTapActionBlock;
@property(copy, nonatomic) CDUnknownBlockType uploadActionBlock; // @synthesize uploadActionBlock=_uploadActionBlock;
@property(retain, nonatomic) YBBOldHomeTLPhotoListModel *model; // @synthesize model=_model;
@property(nonatomic) __weak UIImageView *imgView; // @synthesize imgView=_imgView;
@property(nonatomic) __weak IMYButton *uploadBtn; // @synthesize uploadBtn=_uploadBtn;
@property(nonatomic) __weak UILabel *title; // @synthesize title=_title;
@property(nonatomic) NSLayoutConstraint *titleHeighContraint; // @synthesize titleHeighContraint=_titleHeighContraint;
- (void).cxx_destruct;
- (void)updateAction:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

