//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class YBBOldLamaHeaderPhotoVideoPlayer, YBBOldLamaTimelineModel;

@protocol YBBOldLamaHeaderPhotoVideoPlayerDelegate <NSObject>
- (void)videoPlayer:(YBBOldLamaHeaderPhotoVideoPlayer *)arg1 videoLoadTimeOut:(YBBOldLamaTimelineModel *)arg2;
- (void)videoPlayer:(YBBOldLamaHeaderPhotoVideoPlayer *)arg1 playError:(YBBOldLamaTimelineModel *)arg2;
- (void)videoPlayer:(YBBOldLamaHeaderPhotoVideoPlayer *)arg1 videoDidFinishPlay:(YBBOldLamaTimelineModel *)arg2;
- (void)videoPlayer:(YBBOldLamaHeaderPhotoVideoPlayer *)arg1 didPlay:(YBBOldLamaTimelineModel *)arg2;
@end

