//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface YBBOldHomeGravidityCheckResultItem : NSObject
{
    _Bool _didSet;
    long long _startDay;
    long long _endDay;
    NSString *_time;
    NSString *_mark;
    long long _gravidity_check_time;
    NSArray *_dateArray;
    id _oriModel;
}

@property(retain, nonatomic) id oriModel; // @synthesize oriModel=_oriModel;
@property(retain, nonatomic) NSArray *dateArray; // @synthesize dateArray=_dateArray;
@property(nonatomic) long long gravidity_check_time; // @synthesize gravidity_check_time=_gravidity_check_time;
@property(nonatomic) _Bool didSet; // @synthesize didSet=_didSet;
@property(copy, nonatomic) NSString *mark; // @synthesize mark=_mark;
@property(copy, nonatomic) NSString *time; // @synthesize time=_time;
@property(nonatomic) long long endDay; // @synthesize endDay=_endDay;
@property(nonatomic) long long startDay; // @synthesize startDay=_startDay;
- (void).cxx_destruct;
- (id)initWithModel:(id)arg1;

@end

