//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface YBBToolsSearchEventTrackResultItem : NSObject
{
    NSString *_keyword;
    NSString *_searchKey;
    unsigned long long _searchType;
    unsigned long long _searchFromType;
    long long _typeIndex;
    long long _typeID;
    NSArray *_topicsArray;
    NSArray *_tipsArray;
    NSArray *_canEatsArray;
    NSArray *_canDosArray;
    NSArray *_groupsArray;
    NSArray *_toolsArray;
    NSArray *_relatesArray;
    NSString *_product;
}

@property(copy, nonatomic) NSString *product; // @synthesize product=_product;
@property(retain, nonatomic) NSArray *relatesArray; // @synthesize relatesArray=_relatesArray;
@property(retain, nonatomic) NSArray *toolsArray; // @synthesize toolsArray=_toolsArray;
@property(retain, nonatomic) NSArray *groupsArray; // @synthesize groupsArray=_groupsArray;
@property(retain, nonatomic) NSArray *canDosArray; // @synthesize canDosArray=_canDosArray;
@property(retain, nonatomic) NSArray *canEatsArray; // @synthesize canEatsArray=_canEatsArray;
@property(retain, nonatomic) NSArray *tipsArray; // @synthesize tipsArray=_tipsArray;
@property(retain, nonatomic) NSArray *topicsArray; // @synthesize topicsArray=_topicsArray;
@property(nonatomic) long long typeID; // @synthesize typeID=_typeID;
@property(nonatomic) long long typeIndex; // @synthesize typeIndex=_typeIndex;
@property(nonatomic) unsigned long long searchFromType; // @synthesize searchFromType=_searchFromType;
@property(nonatomic) unsigned long long searchType; // @synthesize searchType=_searchType;
@property(copy, nonatomic) NSString *searchKey; // @synthesize searchKey=_searchKey;
@property(copy, nonatomic) NSString *keyword; // @synthesize keyword=_keyword;
- (void).cxx_destruct;

@end

