//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface YBBToolsURIRunner : NSObject
{
}

+ (id)getToolsLocalUrl:(id)arg1;
+ (void)handlePuthWithURLString:(id)arg1 model:(id)arg2;
+ (void)pushToolWithModel:(id)arg1;

@end

