//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIColor;

@interface YBBToolsDrawLine : UIView
{
    _Bool _isDashed;
    double _lineWidth;
    UIColor *_lineColor;
    struct CGPoint _pointA;
    struct CGPoint _pointB;
}

+ (id)drawLineIsDashed:(_Bool)arg1 WithWidth:(double)arg2 andColor:(id)arg3 fromBegining:(struct CGPoint)arg4 toEnd:(struct CGPoint)arg5;
@property(nonatomic) _Bool isDashed; // @synthesize isDashed=_isDashed;
@property(retain, nonatomic) UIColor *lineColor; // @synthesize lineColor=_lineColor;
@property(nonatomic) double lineWidth; // @synthesize lineWidth=_lineWidth;
@property(nonatomic) struct CGPoint pointB; // @synthesize pointB=_pointB;
@property(nonatomic) struct CGPoint pointA; // @synthesize pointA=_pointA;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (id)drawLineIsDashed:(_Bool)arg1 WithWidth:(double)arg2 andColor:(id)arg3 fromBegining:(struct CGPoint)arg4 toEnd:(struct CGPoint)arg5;

@end

