//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IMYPublicBaseViewController.h"

@class UIButton, UIView, YBBToolsMusicAssitantContainerVC;

@interface YQListentViewController : IMYPublicBaseViewController
{
    UIView *_searchView;
    UIButton *_searchButton;
    YBBToolsMusicAssitantContainerVC *_musicAssitantVC;
}

@property(retain, nonatomic) YBBToolsMusicAssitantContainerVC *musicAssitantVC; // @synthesize musicAssitantVC=_musicAssitantVC;
@property(retain, nonatomic) UIButton *searchButton; // @synthesize searchButton=_searchButton;
@property(retain, nonatomic) UIView *searchView; // @synthesize searchView=_searchView;
- (void).cxx_destruct;
- (void)initUI;
- (void)searchAction;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

@end

