//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SYBaseViewModel.h"

@class NSArray;

@interface YQPhotoMessageVM : SYBaseViewModel
{
    _Bool _hasEndLoadMore;
    NSArray *_tableDatas;
    unsigned long long _pageIndex;
}

@property(nonatomic) unsigned long long pageIndex; // @synthesize pageIndex=_pageIndex;
@property(nonatomic) _Bool hasEndLoadMore; // @synthesize hasEndLoadMore=_hasEndLoadMore;
@property(retain, nonatomic) NSArray *tableDatas; // @synthesize tableDatas=_tableDatas;
- (void).cxx_destruct;
- (void)setCellHeight:(id)arg1;
- (void)reqDownMoreDatas:(CDUnknownBlockType)arg1;
- (void)reqUpMoreDatas:(CDUnknownBlockType)arg1;
- (void)reqDatas:(CDUnknownBlockType)arg1;

@end

