//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SYBaseViewController.h"

#import "IMYDayRecordUploadDelegate-Protocol.h"
#import "SYSyncmlProgressViewDelegate-Protocol.h"

@class IMYAccountModel, IMYDayRecordUpload, NSString, RTLabel, SYBadgeButton, SYSyncmlBottomView, SYSyncmlProgressView, UILabel;

@interface YQRecordSyncmlVC : SYBaseViewController <IMYDayRecordUploadDelegate, SYSyncmlProgressViewDelegate>
{
    _Bool _isRegistUser;
    _Bool _isChangeAccount;
    _Bool _syncmlSuccess;
    unsigned long long _cloudRecordCounts;
    IMYAccountModel *_accountModel;
    long long _loginType;
    NSString *_virtualUserId;
    CDUnknownBlockType _finishedBlock;
    RTLabel *_remindTimeLabel;
    UILabel *_remindTipsLabel;
    SYSyncmlProgressView *_progressView;
    SYSyncmlBottomView *_bottomView;
    SYBadgeButton *_syncmlNumber;
    IMYDayRecordUpload *_normalUpload;
    long long _notifyType;
}

@property(nonatomic) long long notifyType; // @synthesize notifyType=_notifyType;
@property(nonatomic, getter=isSyncmlSuccess) _Bool syncmlSuccess; // @synthesize syncmlSuccess=_syncmlSuccess;
@property(retain, nonatomic) IMYDayRecordUpload *normalUpload; // @synthesize normalUpload=_normalUpload;
@property(retain, nonatomic) SYBadgeButton *syncmlNumber; // @synthesize syncmlNumber=_syncmlNumber;
@property(retain, nonatomic) SYSyncmlBottomView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) SYSyncmlProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) UILabel *remindTipsLabel; // @synthesize remindTipsLabel=_remindTipsLabel;
@property(retain, nonatomic) RTLabel *remindTimeLabel; // @synthesize remindTimeLabel=_remindTimeLabel;
@property(copy, nonatomic) CDUnknownBlockType finishedBlock; // @synthesize finishedBlock=_finishedBlock;
@property(copy, nonatomic) NSString *virtualUserId; // @synthesize virtualUserId=_virtualUserId;
@property(nonatomic) long long loginType; // @synthesize loginType=_loginType;
@property(retain, nonatomic) IMYAccountModel *accountModel; // @synthesize accountModel=_accountModel;
@property(nonatomic) unsigned long long cloudRecordCounts; // @synthesize cloudRecordCounts=_cloudRecordCounts;
@property(nonatomic) _Bool isChangeAccount; // @synthesize isChangeAccount=_isChangeAccount;
@property(nonatomic) _Bool isRegistUser; // @synthesize isRegistUser=_isRegistUser;
- (void).cxx_destruct;
- (void)addLayout;
- (void)addGradientLayer;
- (void)initUI;
- (void)saveUserInfo;
- (void)syncmlSuccessSetUserInfo;
- (void)syncmlSuccessDo;
- (void)popToHome;
- (void)popAnimated:(_Bool)arg1;
- (void)startUseBtnDo;
- (void)syncmlSuccessSetUserInfoText;
- (void)syncmlUnsuccessDo;
- (void)drawAndRefreshSyncmlNumber;
- (void)refreshViewData;
- (void)retryButtonDisplay;
- (void)downloadData;
- (_Bool)uploadVirtualUserData;
- (void)syncmlDataDo;
- (void)syncmAnimationFinished;
- (void)dayRecordError:(id)arg1;
- (void)dayRecordFinished;
- (void)dayRecordProgress:(double)arg1;
- (void)startSyncmlAction;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (_Bool)enableFullPopGestureRecognizer;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

